### ISSUE TITLE
New Zulip Icon looks "wrong" in MacOS Dock

### ISSUE THREAD

**Issue by strifel** [zulip/zulip-desktop#1003]
**Describe the bug**
The new Zulip Icon seems to bigger than other Icons in the Dock.

**To Reproduce**
0. Use MacOS
1. Download Zulip
2. Open Zulip

**Expected behavior**
The Zulip Icon should have the same Size as other round Icons in the Dock.
Maybe there should even be a white boarder like on the other circular Icons.

**Screenshots**
![ZulipIconSize](https://user-images.githubusercontent.com/24608706/88102642-30135280-cba0-11ea-9b3a-ecc9ed348c7c.png)
I drew two red lines for reference:
![ZulipIconSize](https://user-images.githubusercontent.com/24608706/88102472-e7f43000-cb9f-11ea-8436-d5723b3a2b1c.png)

**Desktop (please complete the following information):**
 - Operating System: 
MacOS 10.15.3
 - Zulip Desktop Version:
v5.4.0

**Comment by schrej** [comment]
same as before 😄 #787
