### ISSUE TITLE
Old Tray icon color displayed when receiving notification

### ISSUE THREAD

**Issue by shaderecker** [zulip/zulip-desktop#1004]
**Describe the bug**

When I receive a notification the new blue tray icon switches to the old green tray icon with the number on it.

**To Reproduce**

1. Have no notifications
2. Receive a notification

**Expected behavior**

The icon should stay blue I guess.

**Screenshots**

Without a notification:
![image](https://user-images.githubusercontent.com/16366556/88186640-be85e380-cc35-11ea-9c03-37b7f424f844.png)

With a notification:
![image](https://user-images.githubusercontent.com/16366556/88187338-ab274800-cc36-11ea-9629-c011f5c593f1.png)

**Desktop (please complete the following information):**
 - Operating System: 
Windows 10 (1809)
 - Zulip Desktop Version:
v5.4.0

**Comment by abhigyank** [comment]
Yeah I had thought about this. I suppose Zulip has not moved from its green colour scheme to a blue colour scheme yet on a global level, so I an not sure if this should change. 
Thoughts @timabbott ?

**Comment by timabbott** [comment]
We should definitely change this to either (1) the blue/purple color scheme or (2) the new logo with a red dot in the corner (which would I think would be more consistent with how other apps request attention in this context?).  I've always thought the number in a circle thing to be weird.  

@andersk thoughts?

**Comment by shaderecker** [comment]
This was tackled in the latest update (v5.5.0). Fixed in #1025
![image](https://user-images.githubusercontent.com/16366556/101327888-9eb32d00-386f-11eb-81c5-7878ceaeb040.png)
