### ISSUE TITLE
[Windows] Context menu immediately closes on right click

### ISSUE THREAD

**Issue by dylnuge** [zulip/zulip-desktop#1010]
**Describe the bug**
On Windows, right clicking opens a context menu which then quickly closes. Sometimes it closes too quickly for the interaction to be visible, other times you can make out the shadow of the context menu quickly being drawn and removed from the screen, especially when right clicking many times in quick succession.

**To Reproduce**
1. Right click anywhere (a misspelled word, some selected text, or anywhere else).

**Expected behavior**
A context menu should open and remain open.

**Desktop (please complete the following information):**
Windows 10 Home (1903)
Zulip Desktop v5.3.0

**Additional context**
This may be related to #662, though the platforms are dramatically different. I don't know if this is a regression, as I was not using Zulip Desktop on Windows before today.

**Comment by dylnuge** [comment]
~~I upgraded to v5.4.0 and that seems to have fixed the issue.~~ For what it's worth, the [download link on this page](https://zulipchat.com/apps/windows) is still going to the v5.3.0 download making it unclear there's a newer version

**Comment by dylnuge** [comment]
Issue persists in v5.4.0 but is not present on startup, and restarting the app solves the problem. I'll update here if I find a consistent repro beyond just "run it for a while."

**Comment by timabbott** [comment]
(Just noting that it's now 5.4.0 on the download page).

**Comment by khalilfazal** [comment]
Issue is still present in v5.4.3 and restarting temporarily resolves the issue.

**Comment by piermaz** [comment]
Issue still in 5.6.0

**Comment by jtconsol** [comment]
Still present in 5.8.0, and still temporarily fixable by restart.
