### ISSUE TITLE
Add dismiss/close button for MacOS notifications

### ISSUE THREAD

**Issue by ElliotSilver** [zulip/zulip-desktop#1026]
**Problem Description**
The current desktop notifications appear, and stay for several seconds before sliding away. During this time, the chat message is displayed on the screen, and the notification "tile" blocks access to any screen content under the tile. I have no way to dismiss the tile early.

**Proposed Solution**
As well as the current "reply" button, please add a "dismiss" (or close) button to the tile.

**Describe alternatives you've considered**

**Additional context**

**Comment by akashnimare** [comment]
@manavmehta I think https://github.com/zulip/zulip-desktop/pull/1022/ fixes this, right?

**Comment by andersk** [comment]
We removed `node-mac-notifier` in 5.5.0 (#1046). Is this still an issue?

**Comment by ElliotSilver** [comment]
This looks like it's been addressed. Thanks.
