### ISSUE TITLE
Standard organization theme

### ISSUE THREAD

**Issue by JulianGro** [zulip/zulip-desktop#1029]
**Problem Description**
Our App and the Discord server we currently use are dark themed. It would give Zulip a lot better impression if it started out with a dark theme.

**Proposed Solution**
Adding the ability for an organization to set a different default theme. The themes are currently per organization anyways, so being able to set the theme for new people would make a lot of sense.

**Describe alternatives you've considered**
The default Zulip theme could be the dark theme, but that is obviously a taste thing.

**Comment by timabbott** [comment]
I personally prefer the dark theme as well. That said, Zulip's default theme is based on that of the underlying OS -- if one uses a dark OS theme, Zulip will use that (see https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).  For that reason, we don't have an easy way to change the "default" to the dark theme.
