### ISSUE TITLE
Blank screen on application launch

### ISSUE THREAD

**Issue by shlevy** [zulip/zulip-desktop#1035]
**Describe the bug**

I've just installed zulip for the first time using my distro's package manager. When I launch it the screen is blank.
**To Reproduce**

I can get it by running zulip
**Expected behavior**

Some sort of user interface appears
**Desktop (please complete the following information):**
 - Operating System: NixOS 20.09
 
 - Zulip Desktop Version: 5.4.3
 

**Additional context**

I am running exwm as my window manager. I've been looking for some way to run in debug mode, but so far nothing useful comes out on the terminal. I notice some failed icon/cursor lookups in the strace output, not sure how to translate that to a fix.

**Comment by shlevy** [comment]
This was a bug in my distro's sandboxing, sorry for the noise.

**Comment by timabbott** [comment]
@shlevy thanks for the follow-up.  It'd be great if you can post details on what the bug was, since it may help other users encountering the same bug on NixOS.

**Comment by shlevy** [comment]
https://github.com/NixOS/nixpkgs/pull/97264#issuecomment-704454645
