### ISSUE TITLE
Spellchecker cannot be disabled

### ISSUE THREAD

**Issue by simolev** [zulip/zulip-desktop#1036]
**Describe the bug**
Even after `Settings` `->` `General` `->` `Enable spellchecker (requires restart)` is set to OFF, words are underlined in red while typing (if not in the selected dictionaries). Restarting the app and restarting Windows do not seem to help.

**To Reproduce**
Set to OFF the switch for `Settings` `->` `General` `->` `Enable spellchecker (requires restart)`. Type a few words not in the selected dictionaries, such as `asdfgh`.

**Expected behavior**
No words should be underlined in red while typing.

**Desktop (please complete the following information):**
 - Operating System: 
Windows 10.0.18363.1082
 - Zulip Desktop Version:
Zulip Desktop v5.4.3

**Comment by abhigyank** [comment]
I can't reproduce on Linux, I am on the latest version though.
Can you try it in v5.4.0? If it still fails, could you share the output of  `%APPDATA%/Zulip/config/settings.json` in particularly thr value of `"enableSpellchecker"` key?

**Comment by simolev** [comment]
`"enableSpellchecker": false,` It seems the bug was not there on the older v5.4.0.

**Comment by akashnimare** [comment]
@simolev is this still reproducible on the latest version?

**Comment by simolev** [comment]
Happy to report the issue seems to not be there anymore on Zulip Desktop v5.5.0 (Window 10 and 7).
I'm going to close this :-)
