### ISSUE TITLE
Ctrl + = Zooms in by two steps instead of one.

### ISSUE THREAD

**Issue by tarun8718** [zulip/zulip-desktop#1060]
**Describe the bug**

`Ctrl` + `=` Zooms in by two steps instead of one. This can be checked as we need to press `Ctrl` + `-` **twice** in order to go back to the actual(default) size of window.

**To Reproduce**

1) Open Zulip Desktop App
2) Press  `Ctrl` + `=`  or `Ctrl` + `+`

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04 x64
 
 - Zulip Desktop Version: 5.5.0
 
![Zoomin](https://user-images.githubusercontent.com/40015660/103982332-4f7f5580-51a9-11eb-88c7-fb260ab835c6.gif)

**Comment by a-saksham** [comment]
I think that this issue is already there at [#1031](https://github.com/zulip/zulip-desktop/issues/1031). Check it out.

**Comment by a-saksham** [comment]
@zulipbot claim

**Comment by skshamagarwal** [comment]
#1063 **Issue fixed**

**Comment by drunlade** [comment]
@a-saksham 
Issue still exists. Zooming in is single step, zooming out goes two steps.
