### ISSUE TITLE
Complete distortion of Zulip app icon on a monitor connected to a macbook pro

### ISSUE THREAD

**Issue by gauravpandit91** [zulip/zulip-desktop#1069]
**Describe the bug**
I connect Macbook Pro running macOS Catalina (10.15.7) to a Samsung monitor C27F390 (27-inch (1920 x 1080)) using HDMI. When the display is switched to the Samsung monitor and I use the Finder to locate Zulip app in Applications folder, the Zulip icon looks completely distorted. I can't even recognize what is actually being displayed. However, on the Retina Display (13.3-inch (2560 x 1600)) of Macbook Pro itself, the icon is visible and works fine. But, as soon as the display is switched from the Retina Display to Samsung monitor, the icon looks like blasted. On the monitor, one can see the same behaviour using the Spotlight app too. But, at other places like Dock and the Zulip app window itself, the icons are displayed properly.

This is not happening with the other installed apps. Maybe there is an icon of a particular resolution which is missing in the Zulip app which causes this behaviour. Attaching some screenshots for your reference.

**To Reproduce**
1. Connect a Macbook Pro running macOS Catalina (10.15.7) to a Samsung monitor C27F390 (27-inch (1920 x 1080)) using HDMI.
2. Switch the display to the monitor
3. Check the Zulip app icon in the "Applications" folder in Finder.
4. Check the icon in Spotlight search list too.

**Expected behavior**
The Zulip icon  should appear clearly.

**Screenshots**
![Screenshot 2021-01-12 at 7 04 26 PM](https://user-images.githubusercontent.com/44113600/104795159-8ad2e300-57ac-11eb-83a7-860a0ccd5eda.png)
![Screenshot 2021-01-12 at 7 05 10 PM](https://user-images.githubusercontent.com/44113600/104795160-8c9ca680-57ac-11eb-8a94-34d020e48546.png)
![Screenshot 2021-01-12 at 7 04 15 PM](https://user-images.githubusercontent.com/44113600/104795161-8dcdd380-57ac-11eb-8b15-a072c92382e2.png)

**Desktop (please complete the following information):**
 - Operating System: 
 macOS Catalina 10.15.7

 - Zulip Desktop Version:
v5.5.0

**Additional context**
Finder version - 10.15.6

**Comment by evacchi** [comment]
I can confirm this, have you solved it somehow @gauravpandit91 ?

**Comment by gauravpandit91** [comment]
No, I couldn't solve it. But, since there was no comment on it, I thought that maybe it is not so important, so I closed the issue. @evacchi Please feel free to reopen the issue.

**Comment by maddiemort** [comment]
I still have this problem, when the icon is displayed inside the apps list of [Contexts](https://contexts.co/).
