### ISSUE TITLE
Occasionally high resource usage and memory saturation

### ISSUE THREAD

**Issue by exio82** [zulip/zulip-desktop#1102]
**Describe the bug**

Sometimes the Zulip process in background use too much CPU and grow up memory usage until saturation of all available RAM.

**To Reproduce**

Not identified steps to reproduce.
In my organization some people reported the problem in the following days:
2021-02-24 : 1 report
2021-03-03 : 3 report
2021-03-24 : 1 report
2021-03-27 : 1 report
2021-04-08 : 1 report
Not everyone have reported the problem so data is incomplete.

**Expected behavior**

The Zulip process should remain idle in background: CPU nearly 0% and RAM nearly constant.

**Screenshots**

Windows task manager showing the memory usage
![image](https://user-images.githubusercontent.com/1618138/114013427-ce972f00-9867-11eb-95d7-eb22157e5e0c.png)

**Desktop (please complete the following information):**

- Operating System:
Windows 10 Pro - 10.0.19042 Build 19042 - x64
- Zulip Desktop Version:
5.6.0

**Additional context**

Under normal operation there are 7 Zulip running processes in my PC: 1 father and 6 children.
The problematic process was outside this hierarchy, maybe it remained orphan from a previous app close.

The behaviour of this process is always the same: it remains in background consuming about 1 core of CPU all the time and slowly increase memory usage. 
After a few hours or maybe a day the memory usage grows up very quickly and saturates all the available memory.

On 2021-03-27 I noticed a background Zulip process that could probabily become a resource-killer and saved some debugging info and the commandline:
"C:\Program Files\Zulip\Zulip.exe" --type=renderer --force-color-profile=srgb --field-trial-handle=1556,16009612536436185094,14001065593348688730,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=it --app-path="C:\Program Files\Zulip\resources\app.asar" --node-integration --webview-tag --no-sandbox --no-zygote --enable-remote-module --background-color=#fff --enable-spellcheck --enable-websql --disable-electron-site-instance-overrides --device-scale-factor=1.5 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=2336 /prefetch:1

Debugging info: MiniDump and the Windows system event of memory exhaustion:
[2021-03-27_problem.zip](https://github.com/zulip/zulip-desktop/files/6278132/2021-03-27_problem.zip)

**Comment by timabbott** [comment]
@exio82 if you see this situation, can you use the "Developer tools" within the app to collect a profile?  The "Performance" tab allows doing so -- it works exactly like Chrome for that purpose: https://developer.chrome.com/docs/devtools/evaluate-performance/.

We've had a few reports like this, but have been unable to reproduce it, and it'd be really useful to know what code is running when you see this symptom.

Some details on your organization size (number of users, for example) might also help.

**Comment by exio82** [comment]
I have a problematic process running right now.

The performance devtools in Zulip Desktop (ctrl+shift+i) show it's idle, so it doesn't help.

Closing the app terminate the main processes hierarchy but not the problematic process, which remains active in background and does not have an associated window. 
So I can't use devtools on that process cause there is no window associated to it.

![image](https://user-images.githubusercontent.com/1618138/114381643-a1aa8b00-9b8b-11eb-9d28-4c1370f2358c.png)

Is there a way to attach to the running process and see the internals?
I'm trying to gather more info from windows debugger but need the debug symbols.
AFAIK Zulip Desktop is compiled with nodejs and contains a chromium runtime, correct?

Organization size: about 150 users

**Comment by piermaz** [comment]
Same problem here. Win10

**Comment by AtlasHands** [comment]
I will try to catch the heap the next time - but I've seen the same issue.  I've downgraded to 5.5.0 and it doesn't appear to happen anymore.

**Comment by exio82** [comment]
Found a way to reproduce (hopefully):
1. when Zulip is running right click on the icon on the task bar and select "Pin to taskbar"
2. close the app with "X" so it remains active in background
3. start the app using the pinned icon in the taskbar

Repeat steps 2 and 3 many times and maybe some processes remains orhpan in background.

The behaviour of launching Zulip is different between:
- launching from pinned taskbar: Explorer.exe starts a new Zulip process without command line arguments. Then the Zulip window of already running Zulip process is showed and the new process terminates
- launching from the system tray: no new process is created, only the Zulip windows is showed


Screenshot of how to pin to taskbar:
![Pin to taskbar](https://user-images.githubusercontent.com/1618138/115519251-51b57d80-a289-11eb-9494-0e20b8939ddd.jpg)


Screenshot of running Zulip in background in system tray:
![Windows Tray](https://user-images.githubusercontent.com/1618138/115519266-567a3180-a289-11eb-8598-f96a7f9a36d8.jpg)


Log of process creation and termination with highlighted the non terminated one:
[Process creation log.xlsx](https://github.com/zulip/zulip-desktop/files/6349167/Process.creation.log.xlsx)

**Comment by JacquelineMorrissette** [comment]
I had the issue happen to me a couple times and I captured a profile using the performance tab today. 
[Profile-20210421T161405.txt](https://github.com/zulip/zulip-desktop/files/6353658/Profile-20210421T161405.txt)
I hope this helps!

**Comment by andersk** [comment]
Thanks for the helpful reproduction recipe @exio82. I was able to reproduce a bug that could lead to spinning background processes on repeated launches. The bug was actually introduced years ago, but its symptoms may have changed recently. I’ll plan to release this fix as part of 5.7.0 within the coming days.

Obviously we can’t be sure this one bug explains all of these reported problems, so if you see a problem like this after the 5.7.0 release, please don’t hesitate to open another issue with as much information as you can get.

**Comment by andersk** [comment]
We just released Zulip Desktop 5.7.0 including that fix. Please do let us know if this continues to be a problem.
