### ISSUE TITLE
File browser text not display properly on desktop application (Fedora)

### ISSUE THREAD

**Issue by jahazieldom** [zulip/zulip-desktop#1103]
Hello everyone, in the desktop application the file browser does not work correctly and is practically unusable. I am using version 5.4.3 of the desktop application (AppImage) in Fedora 31. 

Screenshot of the problem:
![image](https://user-images.githubusercontent.com/3392725/95611751-20750e80-0a17-11eb-9f37-a3ebc2c4bc2f.png)

**Comment by timabbott** [comment]
@jahazieldom can you still reproduce this issue with the latest desktop app?

My guess is that this was a chromium bug that was fixed upstream.

**Comment by jahazieldom** [comment]
> @jahazieldom can you still reproduce this issue with the latest desktop app?
> 
> My guess is that this was a chromium bug that was fixed upstream.

With the new version the problem no longer occurs.
