### ISSUE TITLE
[Feature request] Make zulip urls be opened by the zulp app.

### ISSUE THREAD

**Issue by aramirezreyes** [zulip/zulip-desktop#1108]
I write this regarding the macOS desktop app, although it may also be relevant to other apps. 

Some desktop applications are associated to certain urls, for example: If I click on a zoom link, macOS will ask me if I want the zoom desktop app to open the link.

With Zulip, if someone shares a link to a Zulip stream or message, the web browser is directed to said webpage. In my case, I usually have the desktop app open and I am not logged in the browser, so basically clicking a zulip link is not useful, as I won't be able to see the message.

Additionally, if I am inside the zulip app and click a link to another zulip message, the link is opened in the browser and no in the app itself, which again is not very useful.

Is is possible to add these features to the zulip desktop app?

Thanks!

**Comment by timabbott** [comment]
This is a duplicate of https://github.com/zulip/zulip-desktop/issues/470.  I agree this is something we should add soon.

**Comment by aramirezreyes** [comment]
Thanks and sorry for the noise. It is indeed duplicated, I just didn't find it because I didn't know the correct terminology.
