### ISSUE TITLE
bad rendering on mac os x app

### ISSUE THREAD

**Issue by nikomatsakis** [zulip/zulip-desktop#1109]
I'm not sure if this is the repository for this sort of issue, but I am having a lot of troubles with Zulip's rendering in the OS X desktop app. Here is an example:

![image](https://user-images.githubusercontent.com/155238/114443094-48e2ee80-9b9b-11eb-85d3-d8ddfa65ce4e.png)

It is rendering the app somewhat useless for me. This is a recent development -- I always had problems these, but they were previously specific to the app's icon. They have now come to infect the messages themselves.

**Comment by timabbott** [comment]
Moved to the right repository for the desktop app, though if folks are seeing this in Chrome as well, it may affect the webapp in Chrome as well.

**Comment by andersk** [comment]
The chat\.zulip\.org report was for the webapp in Chrome. The real bug is [apparently](https://bugs.chromium.org/p/chromium/issues/detail?id=1068170#c234) in Apple’s AMD graphics driver.

**Comment by nikomatsakis** [comment]
The problem seems to have gone away for now, for whatever reason.

**Comment by andersk** [comment]
According to the upstream issue, Apple shipped this fix in macOS 11.4 (beta 2, 20F5055c) and 11.5 (beta 4, 20G5052c).

**Comment by AndrewRayCode** [comment]
I had a similar issue that persisted until a restart:

<img width="210" alt="Screen Shot 2021-11-19 at 6 32 15 PM" src="https://user-images.githubusercontent.com/79215/142711516-ec4e8295-3c9f-4d10-bc76-55f6b2f46229.png">

<img width="445" alt="Screen Shot 2021-11-19 at 6 32 07 PM" src="https://user-images.githubusercontent.com/79215/142711525-8e94970c-6d51-4868-a291-35a958b814bf.png">

Screenshots are of some specific clips. Note the garbled horizontal lines over text as well as the repeated image in places it shouldn't appear. This corruption affected the whole interface including the user sidebar.
