### ISSUE TITLE
Mac installer has old Zulip logo

### ISSUE THREAD

**Issue by alya** [zulip/zulip-desktop#1110]
**Describe the bug**

The Mac installer uses the old Zulip logo in the installation instructions.

**Screenshots**

<img width="498" alt="Zulip_5_6_0_and_Zulip_and_Security___Privacy" src="https://user-images.githubusercontent.com/2090066/114815550-3ddeb880-9d6b-11eb-9d74-670ef9b823ac.png">

**Desktop (please complete the following information):**

- Operating System: macOS 10.15.7

- Zulip Desktop Version: 5.6.0

**Comment by tarun8718** [comment]
@andersk I think this can be closed.

**Comment by andersk** [comment]
Fixed by #1112.
