### ISSUE TITLE
Request: show a confirmation dialog before being logged out when pressing CTRL+L

### ISSUE THREAD

**Issue by JobLeonard** [zulip/zulip-desktop#1115]
**Problem Description**

I often have the Zulip desktop client open on one monitor, my browser on the other. In browsers CTRL+L shifts focus to the URL bar, allowing one to quickly navigate to a new webpage without having to scroll the cursor.

Sadly, CTRL+L also logs one out of Zulip.

(I'm on Linux, by the way, with KDE Neon as my distro - perhaps these shortcuts are different on other operating systems)

It turns out that I'm a klutz who keeps making mistakes about which desktop application currently has focus. So I accidentally log out of Zulip all the time. To make matters worse, I use a generated password, which I then have to look up before being able to log in again.

**Proposed Solution**

Display an ***"Are you sure you wish to log out?"*** confirmation dialog before logging someone out of a Zulip chat room upon typing CTRL+L, instead of doing so instantly. Give it keyboard focus so one can just press enter to confirm, or escape to cancel.

**Describe alternatives you've considered**

1. *Just never make mistakes and always ensure the right program has focus!*

As much as I would *love* for this to be an effective solution, it just doesn't seem to work for me in practice. Believe me it's not a lack of motivation, I've been annoying myself for months now.

**Comment by andersk** [comment]
@akashnimare What was the motivation for adding the `Ctrl`+`L` shortcut? This doesn’t seem like a common operation that needs a keyboard shortcut at all.

**Comment by timabbott** [comment]
Yeah, I would be tempted to remove that shortcut, especially since we have `Ctrl+Shift+L` for adding a link when composing markdown.
