### ISSUE TITLE
Certificate error 

### ISSUE THREAD

**Issue by ali-yahyaoui** [zulip/zulip-desktop#1141]
This pop-up is shown when opening some streams on Zulip Desktop.
PS: We have a valid commercial SSL certificate for our domain.
![image](https://user-images.githubusercontent.com/60253677/127462272-cbf3e02e-a3cb-4a10-84fc-6effb6f63346.png)

**Comment by timabbott** [comment]
@ali-yahyaoui are you seeing this in the desktop app?  The problem is Zulip is trying to load a link preview of another domain that has an invalid certificate, and the desktop app error handling for this doesn't work.

**Comment by andersk** [comment]
Closing as duplicate of #1119.

**Comment by ali-yahyaoui** [comment]
@timabbott  Yes in Zulip Desktop v5.8.1, Okay thanks well understood.
