### ISSUE TITLE
I want to modify the tray icon.

### ISSUE THREAD

**Issue by SenlinOS** [zulip/zulip-desktop#1153]
I tried to change the tray icon, but I couldn't find it. (only want the white Z icon)
Where exactly is the tray icon?

Xubuntu 20.04, Zulip APT

Thank you.

![img](https://z3.ax1x.com/2021/10/19/5w70fK.png)

**Comment by andersk** [comment]
https://github.com/zulip/zulip-desktop/tree/main/app/resources/tray

**Comment by SenlinOS** [comment]
Thanks for the reply, but there is no such file, it seems to be packaged.
No problem, I hide the tray icon, use the shortcut Ctrl+Q to exit.
