### ISSUE TITLE
Unread message bug when topic contains numbers in parentheses

### ISSUE THREAD

**Issue by amative1** [zulip/zulip-desktop#1157]
**Describe the bug**

When using the App (both PC and Mac), any topic containing a positive number in parentheses is treated as an unread count.

**To Reproduce**

Create a thread with (10) in the topic title, server icon and app icon display 10 unread messages (even if less than 10 messages exist on the server

**Expected behavior**

Unread message count should not show 10 if topic contains (10)

**Screenshots**

<img width="523" alt="Screen Shot 2021-10-23 at 8 36 46 PM" src="https://user-images.githubusercontent.com/14666630/138575481-fccedcdd-a886-4193-9cd0-498a77013468.png">

**Desktop (please complete the following information):**

App: Zulip 5.8.1
Electron: 13.1.7 (Node v14.16.0)
Operating System: darwin x64 20.6.0

Was also tested by a separate user on a Windows PC

**Comment by amative1** [comment]
May be linked to #1034 but unsure as no context was mentioned

**Comment by manavmehta** [comment]
This is weird. But I am unable to reproduce it in Windows 11 and I no longer have a mac.'
![image](https://user-images.githubusercontent.com/31139861/138939659-f669756c-d18b-48e9-a2ad-33864431d7f3.png)

**Comment by amative1** [comment]
Does it still only show 2 unread when you click on **(10) test 1** to view that thread specifically (it looks as though you're viewing _#test here_ instead

**Comment by manavmehta** [comment]
Yes, if I view any opened stream/threads, it shows 2 still. The actual unread count.
@timabbott could you reproduce this?
I'll try reproducing for a custom zulipchat org.

**Comment by timabbott** [comment]
I don't have a mac but perhaps @alya can try reproducing on one.

**Comment by alya** [comment]
I can't replicate, sorry.

**Comment by amative1** [comment]
More data: I was able to replicate my bug in the Zulip Community server, in the existing (10) test 3 (10) and New Topic (2021) threads from the screenshot above.
<img width="289" alt="Screen Shot 2021-10-27 at 6 30 27 PM" src="https://user-images.githubusercontent.com/14666630/139157073-deef9331-3cd3-46b4-9d2b-6360382f63db.png">
<img width="276" alt="Screen Shot 2021-10-27 at 6 30 21 PM" src="https://user-images.githubusercontent.com/14666630/139157074-d29e2603-01da-4959-9d55-e0928f84f361.png">

**Comment by timabbott** [comment]
Thanks for the report @amative1!
