### ISSUE TITLE
allow control of GIF autoplay (e.g. stop after N seconds OR don't autoplay at all)

### ISSUE THREAD

**Issue by umataro** [zulip/zulip-desktop#1171]
**Problem Description**

GIFs consume too many resources. Even on new-ish laptops, a page with 2-3 animated GIFs uses 10-25% of CPU. This is immediately noticeable on battery life and fan noise. Some people also find them distracting/irritating. 

**Proposed Solution**

Possible solutions:
* per user setting to < disable | stop after N seconds | enable > gif autoplay
* per organisation setting to < disable | stop after N seconds | enable > gif autoplay
* per stream setting to < disable | stop after N seconds | enable > gif autoplay

GIF would then play  only when clicked on

**Comment by timabbott** [comment]
Yeah, this is a very annoying problem with animated GIFs across the web.  We're working on this issue in the Zulip webapp (and thus implicitly the desktop app as well); it's already been addressed for status emoji.  See e.g. https://github.com/zulip/zulip/issues/13434.

**Comment by yringler** [comment]
What's the status of this? I see it was closed, but I don't see the functionality.

**Comment by alya** [comment]
As noted in @timabbott 's comment above, this issue is tracked as https://github.com/zulip/zulip/issues/13434.
