### ISSUE TITLE
Windows client crashes shortly after starting

### ISSUE THREAD

**Issue by janakmulani** [zulip/zulip-desktop#1205]
**Describe the bug**

I installed Zulip 5.9.1 on Windows 11. But if I enter URL to my company server and clk Connect or even if I choose from menu Help > About Zulip, it just crashes! There is nothing in the error logs : <User Home>AppData\Roaming\Zulip\Logs\errors.log

**To Reproduce**

1. Install Zulip v 5.9.1 for windows desktop.
2. Start zulip
3. Choose Help > about Zulip from menu
4. Or enter server URL and clk connect
5. Zulip crashes

**Expected behavior**

Expected Zulip to show "About Zulip" dialog or connect to the specified server.

**Screenshots**
![image](https://user-images.githubusercontent.com/655389/164175732-abb2db7f-33c2-4ab6-a612-c2cf2cb39c65.png)

**Desktop (please complete the following information):**

- Operating System:
Windows 11
- Zulip Desktop Version:
v5.9.1

**Additional context**
Installed new version because old desktop version was crashing on starting the app. 
Have set Autoupdate to false in config json
Updates log has the following lines:

2022-04-20 12:51:00.155] [info]  Checking for update
[2022-04-20 12:51:00.162] [info]  Generated new staging user ID: e2c8b109-57f7-54f6-ab67-500c2636f740
[2022-04-20 12:51:01.793] [info]  Update for version 5.9.1 is not available (latest version: 5.9.1, downgrade is disallowed).

**Comment by andersk** [comment]
This was an upstream Electron bug that we previously reported at electron/electron#33693. It was fixed in Electron today, and we’ve released Zulip Desktop 5.9.2 including this fixed version of Electron.
