### ISSUE TITLE
5.9.3 will not run on MacOS 12.3.1

### ISSUE THREAD

**Issue by Nothorse** [zulip/zulip-desktop#1214]
**Describe the bug**

Release 5.9.3 on intel Mac will not start. The Finder pops a message that the app is damaged and needs to be moved to the trash.

**To Reproduce**

Download the dmg and try to install.

**Expected behavior**

I expect it to run.
**Screenshots**

**Desktop (please complete the following information):**

- Operating System:

MacOS 12.3.1 Intel Macbook

- Zulip Desktop Version:

5.9.3

**Comment by andersk** [comment]
That sounds bad. I can’t reproduce though.

Can you confirm the SHA-256 hash of the .dmg file you downloaded, just to make sure we’re talking about the same file and that it was downloaded correctly? You can do this in Terminal by running a command like:

```shell
shasum -a 256 ~/Downloads/Zulip-5.9.3-x64.dmg
```

**Comment by Nothorse** [comment]
`shasum -a 256 ../web/Zulip-5.9.3-x64.dmg
ac6f1aadc02dfe1ba04193f67f5f081b6f22d2bfde40c18956071e6cec9c390f  ../web/Zulip-5.9.3-x64.dmg`

**Comment by andersk** [comment]
Hmm, that’s the correct file.

This is going to sound silly, but have you tried rebooting? (Articles such as [this one](https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/) suggest that may resolve this error in some cases.)

Also check that your system clock and time zone are set correctly—go to https://time.gov and look below the analog clock for a message like “Your clock is off by: +0.045 s”.

**Comment by Nothorse** [comment]
OK, rebooting fixed it. 

The ways of MacOS are sometimes very mysterious. Thanks!
