### ISSUE TITLE
Zulip desktop on windows failed adding new organization while self-hosted zulip-server shutdown 

### ISSUE THREAD

**Issue by wilbq** [zulip/zulip-desktop#1215]
A zulip-desktop was installed on my windows computer, and connected to a self-hosted zulip-server.
It worked well until the zulip-server was shutdown.
Each time after the zulip-desktop start-up, it seems to try connecting to the old zulip-server which already
disappeared.
I can not remove the old organization, and can not add a new one either.
Even a re-installation did not solve the problom.

- Operating System:
  Windows 10
- Zulip Desktop Version:
  5.8.1 and 5.9.3

**Comment by foto-andreas** [comment]
Workaround: Edit %USER_HOME%\AppData\Roaming\Zulip\config\domain.json and remove the wrong domain. This is a total show stopper for the users!

Also happens on Mac. I think it can be changed under $HOME/Library/AppSupport/Zulip...

Andreas

**Comment by andersk** [comment]
Zulip Desktop 5.9.5 fixes a bug where the app would freeze in this case. It should now display the network error page and otherwise continue working normally.
