### ISSUE TITLE
Previous organization which no longer resolves in DNS shows an empty window at startup

### ISSUE THREAD

**Issue by alexmv** [zulip/zulip-desktop#1218]
**Describe the bug**

If the user previously had a working Zulip install at `https://chat.zulip-nonexistant.org/`, but it has since vanished fully form DNS, starting up produces a white window.

The logs do contain:
```
LOG | 4/26 38:9 |	 Error: https://chat.zulip-nonexistant.org does not appear to be a valid Zulip server. Make sure that
 • You can connect to that URL in a web browser.
 • If you need a proxy to connect to the Internet, that you've configured your proxy in the Network settings.
 • It's a Zulip server. (The oldest supported version is 1.6).
 • The server has a valid certificate.
 • The SSL is correctly configured for the certificate. Check out the SSL troubleshooting guide -
 https://zulip.readthedocs.io/en/stable/production/ssl-certificates.html
    at checkDomain (VM299 domain-util.js:138:15)
    at async Object.updateSavedServer (VM299 domain-util.js:153:31)
    at async VM116 main.js:279:17
    at async Promise.all (index 0)
    at async ServerManagerView.initTabs (VM116 main.js:273:13)
    at async ServerManagerView.init (VM116 main.js:103:9)
    at async VM116 main.js:926:5
```
...but that is not displayed to the user

**To Reproduce**

1. Log into a real Zulip server.
2. Quit the app.
3. Edit `domain.json` (e.g. in `~/Library/Application Support/Zulip/config/domain.json`) to point the `url` field to an invalid domain:
```json
{
    "domains": [
        {
            "icon": "/Users/chmrr/Library/Application Support/Zulip/server-icons/820503988.png",
            "url": "https://chat.zulip-nonexistant.org",
            "alias": "Zulip Community"
        }
    ]
}
```
4. Start the app.

**Expected behavior**

You would see the "network failed" message.

**Desktop (please complete the following information):**

- Zulip Desktop Version: 5.9.3

**Additional context**

Reported [here](https://chat.zulip.org/#narrow/stream/16-desktop/topic/Mac.20client.20hangs.20on.20discontinued.20organizations).

**Comment by dePoPo** [comment]
ran into this when moving from a local installation to a zulip cloud account. Additionaly, uninstalling the desktop client on windows does not remove the previous settings, so reinstalling does not help. 

Workaround: clearing out %appdata%\roaming\zulip folder (windows client) was needed to trigger a fresh configuration dialog.

**Comment by hvisage** [comment]
Yeah, same trouble macOS ;(
I can't now add, new organizations, neither delete the "faulty" one ;(

**Comment by andersk** [comment]
Zulip Desktop 5.9.5 fixes a bug where the app would freeze in this case. It should now display the network error page and otherwise continue working normally.
