### ISSUE TITLE
Keeps loading when starting up on login when no internet is available yet

### ISSUE THREAD

**Issue by AndreasBackx** [zulip/zulip-desktop#1220]
I start Zulip when I login with [swaywm](https://swaywm.org/), see [my config](https://github.com/AndreasBackx/dotfiles/blob/master/.config/sway/base#L129). Zulip seems to be then forever stuck in the loading spinner animation, not even showing the Zulip logo yet. I would assume that this is because the network hasn't started yet or is being changed and it fails to retry properly. What fixes it, is closing Zulip and starting it again.

![image](https://user-images.githubusercontent.com/1593486/170257108-2d92d735-d8df-41f6-8099-747651620ccf.png)

This is on the AppImage for Linux version 5.9.3. My distro is Fedora 36, though was an issue for 34 and 35 as well from what I remember (I updated recently).

**Comment by vrozkovec** [comment]
Same behavior for me. Reload nor Hard reload fixes the issue. Need to close and open the app. Using latest 5.9.3 version installed via APT on Linux Mint 20.3

**Comment by kdator** [comment]
Same behaviour on Ubuntu 22.04. If you try to run the application without a physical internet connection via Ethernet/Wi-Fi, then Zulip hangs indefinitely on loading. Restarting the operating system helps to solve the problem.

**Comment by flaviozluca** [comment]
Friends,

Happens to me quite a bit in win 11, I startup the day and it's spinning, I have quit, open it back. Can't it have a delay on startup or keep trying a bit longer?

Thanks.

**Comment by andersk** [comment]
Zulip Desktop 5.9.5 fixes a bug where the app would freeze in this case. It should now display the network error page and otherwise continue working normally.

**Comment by Darkthewolf** [comment]
Hi,

Same problem, win 10, Zulip Desktop 5.9.5 -- forever loading. Reboot, reinstall -- had no effect.

![изображение](https://user-images.githubusercontent.com/35077269/217446469-966d63cf-3245-458b-ae4d-58ece8ae14c2.png)

**Comment by mateuszmandera** [comment]
@Darkthewolf Is the app's UI working? You seem to have one of the menus open, so that might be working fine?

**Comment by Darkthewolf** [comment]
> @Darkthewolf Is the app's UI working? You seem to have one of the menus open, so that might be working fine?
The app's UI is working, but menu items do nothing and i can't, for example, go to the settings and change organization. It happens after I changed host address in server's settings.py (was added custom port). But on other PC, where desktop app was never installed before -- i installed the app and it work well.

**Comment by mateuszmandera** [comment]
> But on other PC, where desktop app was never installed before -- i installed the app and it work well.

Does it work well, just with other servers, or is it also working fine with this server that broke your app on another device? It seems quite strange if there was a difference like that between devices. Are you able to connect to the server from the browser?
