### ISSUE TITLE
"View message source" does nothing

### ISSUE THREAD

**Issue by lukors** [zulip/zulip-desktop#1242]
**Describe the bug**

Pressing the three dot menu and then "view message source" on a message does nothing.

**To Reproduce**

1. Press the three dot menu on a message
2. Press "view message source"

**Expected behavior**

It should show the message's source.

**Screenshots**

[Kazam_screencast_00001.webm](https://user-images.githubusercontent.com/1719884/195800954-78fd11ab-a556-4bf6-bf73-2531379a4064.webm)

**Desktop (please complete the following information):**

- Operating System:
Pop!_OS 22.04 LTS
- Zulip Desktop Version:
5.9.3

**Comment by timabbott** [comment]
Thanks for the report. This is likely a duplicate of https://github.com/zulip/zulip/issues/23864 -- it's the exact same API request that fetches the data for these two features, so we just need to figure out what it's failing in one place.
