### ISSUE TITLE
Malformed links crash the client

### ISSUE THREAD

**Issue by tmichela** [zulip/zulip-desktop#1247]
**Describe the bug**

Having a malformed hyperlink cause the desktop client to crash.

**To Reproduce**

write a comment with a malformed link and click on it, e.g. `[this is a link](this is not an url)`

**Expected behavior**

no crash

**Desktop (please complete the following information):**

- Operating System: macOS 11.7.1
- Zulip Desktop Version: 5.9.3

**Comment by andersk** [comment]
I believe this has been resolved in Zulip Desktop 5.9.4 by the upgrade to Electron 22.0.0 (#1259) and/or the exception handler added in 94780c44c89e171710684944e0e811c2b6cdc8b0. If you see this crash again after upgrading to 5.9.4, please let us know. Thanks!
