### ISSUE TITLE
can't turn off desktop notifications

### ISSUE THREAD

**Issue by mwarpinski** [zulip/zulip-desktop#1300]
**Describe the bug**

Even with desktop notification turned off, and with Do Not Disturb Enabled, I still get desktop pop-up notifications

**To Reproduce**

Turn off notifications, enable DND.. wait for someone to post a message

**Expected behavior**

nothing

**Desktop (please complete the following information):**

- Operating System:
Ubuntu 22.04
- Zulip Desktop Version:
v5.9.5

**Comment by andersk** [comment]
Closing as duplicate of #1299.
