### ISSUE TITLE
On "About Zulip" dialog there isn't the way to exit

### ISSUE THREAD

**Issue by engineer163** [zulip/zulip-desktop#1309]
**Describe the bug**

When you click on About Zulip, a page with information opens that cannot be closed. It helps to restart the program "Command + Q" or "View - Hard Reload".

**To Reproduce**

Click on "Help - About Zulip"

**Expected behavior**

The window is displayed normally, but there is no way to exit it.

**Screenshots**

<img width="1101" alt="image" src="https://github.com/zulip/zulip-desktop/assets/88875714/b2d6d07e-c129-492b-bb17-d23af50330aa">

**Desktop (please complete the following information):**

- Operating System:
   macOS 12.6.3
- Zulip Desktop Version:
   5.9.4

**Comment by andersk** [comment]
You have disabled the sidebar with **View** → **Toggle Sidebar**; it will be more obvious how you can switch back to your organization if you turn it back on. But you can switch back from the **Window** menu either way.

**Comment by engineer163** [comment]
Thanks!
