### ISSUE TITLE
Zulip client refusing to connect to newly installed server with --self-signed-cert

### ISSUE THREAD

**Issue by naim5am** [zulip/zulip-desktop#1312]
Thanks for the aweseome work. Any help appreaciated. 

Error: https://domain.home does not appear to be a valid Zulip server

I followed the standard installation procedure on a Raspberry Pi4 running a fresh Raspbian 64bit Debain 11  bullseye. 
installed with:

`./zulip-server-*/scripts/setup/install --self-signed-cert --email=email@disroot.org --hostname=domain.home` 

After successfully installing Zulip, I used the browser to visit the single-use linkand register my new Zulip installation. I got a **Warning: Potential Security Risk Ahead** which I skipped by pressing **Advanced> Accept the risk and continue**. I can't do the same on any of the zulip clients

**some troubleshooting**
**DIG**
```
dig  domain.home

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> domain.home
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37386
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;domain.home.			IN	A

;; ANSWER SECTION:
domain.home.		0	IN	A	192.168.18.37

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Jun 05 11:38:05 EEST 2023
;; MSG SIZE  rcvd: 59
```
**CURL**
```
curl -Ssl -v https://domain.home
*   Trying 192.168.18.37:443...
* Connected to domain.home (192.168.18.37) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /home/buzzworker/anaconda3/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Desktop**

- Client Operating System: Pop!_OS 22.04 LTS, kernel 6.2.6-76060206-generic x86_64
- Zulip Desktop Version: 5.10.0
I tried to do the same on the mobile client but couldn't figure out how to add a new server.

**Comment by andersk** [comment]
See https://zulip.com/help/custom-certificates.

**Comment by naim5am** [comment]
Thanks. Wouldn't it help to put a link to that in the **--self-signed-cert** section of the installer options documentation? It says --self-signed-cert is not for production use, but I expect to find the documentation needed to test Zulip.
