### ISSUE TITLE
Desktop Notifications are not working anymore

### ISSUE THREAD

**Issue by tonynajjar** [zulip/zulip-desktop#1317]
Zulip desktop version: 5.10.0

Suddenly my desktop notifications stopped working. Pressing the `Test desktop notification` and Play button does nothing
![image](https://github.com/zulip/zulip-desktop/assets/14879660/000a714a-2bf7-49cc-ab27-0a86664b1e66)

Weirdly enough, it still works from the browser. I'm not sure how I can give you more information, are there any logs I can send to you? Thanks for the guidance

**Comment by tonynajjar** [comment]
This should be useful to you:

![image](https://github.com/zulip/zulip-desktop/assets/14879660/17480ee7-62b0-4741-a4f3-86c4cbe40441)

**Comment by achton** [comment]
I have the same issue on Linux with the desktop app. We are using Zulip Cloud.

**Comment by achton** [comment]
@tonynajjar Did you learn anything new since creating this issue? Have you tried downgrading?

I've tried reinstalling 5.10 without any change 🐼

**Comment by tonynajjar** [comment]
Sadly not, still the same. Weirdly enough no one else in my company seems to be having the issue. My ugly workaround is to have the web version always open in parallel to get the notifications 🙃

**Comment by achton** [comment]
Yeah, whatever works, right? :) 

Did you by any chance upgrade to Ubuntu 23.04 recently? That's the only thing I can think of - I think this issue started more or less around that time for me.

**Comment by tonynajjar** [comment]
Nope, still on Ubuntu 22.04.3

**Comment by andersk** [comment]
Have you accidentally enabled the [Do Not Disturb](https://zulip.com/help/do-not-disturb) feature of the desktop app? If you want notifications, make sure you’ve turned that off.

**Comment by tonynajjar** [comment]
> Have you accidentally enabled the [Do Not Disturb](https://zulip.com/help/do-not-disturb) feature of the desktop app? If you want notifications, make sure you’ve turned that off.

Well, that's officially the stupidest I felt in 2023. That was the issue indeed, thanks a lot for your comment.

On the other hand, it would be great if it would be clearer to the user that Do Not Disturb is on when testing desktop notification with the button in Settings > Notifications:

![image](https://github.com/zulip/zulip-desktop/assets/14879660/00e4df69-d04a-420e-a110-304f2ed96b3c)

I'll be happy to open another feature request if you agree with the idea
