### ISSUE TITLE
provide the `zulip.desktop` which is required by package maintainer of linux distribution

### ISSUE THREAD

**Issue by hervyqa** [zulip/zulip-desktop#1321]
**Problem Description**

I didn't find `zulip.desktop` if build from the source code for linux or linux release ([tar.xz](https://github.com/zulip/zulip-desktop/releases/download/v5.10.0/Zulip-5.10.0-x64.tar.xz)). even though `zulip.desktop` is important for zulip to appear in the launcher menu. but i found it in appimage.

**Proposed Solution**

there is no `zulip.desktop` for linux applications (i meant build from source code for linux. no snap, flatpak or appimage) to appear on launcher menu, so it is necessary to create `.desktop` manual for linux distribution package maintainer. like [archlinux](https://aur.archlinux.org/cgit/aur.git/tree/zulip-desktop.desktop?h=zulip-desktop), [voidlinux](https://github.com/void-linux/void-packages/pull/45242/files#diff-1eede1a0fbf7b72074d40f3621625eaf4991c3736898a2e68e491626da5b4b49) and others. the solution is to create a `zulip.desktop` like this from [package.json](https://github.com/zulip/zulip-desktop/blob/7fba8cfae92d9a8d570cb97bf802117f58d80a27/package.json#L73C10-L73C10):

```
[Desktop Entry]
Name=Zulip
Exec=zulip
Terminal=false
Type=Application
Icon=zulip
StartupWMClass=Zulip
Comment=Zulip Desktop Client for Linux
Categories=Chat;GNOME;GTK;Network;InstantMessaging;
```

usually it will be put in a directory `/usr/share/applications/`.

**Describe alternatives you've considered**

I don't understand electron yet, but we can see from the `wire-desktop` source code that generates `.desktop` automatically.
https://github.com/wireapp/wire-desktop/blob/dev/bin/build-tools/build-linux-desktop-file.ts

**Additional context**

**Comment by andersk** [comment]
The `zulip.desktop` file is generated by [`LinuxTargetHelper#writeDesktopEntry`](https://github.com/electron-userland/electron-builder/blob/v24.6.4/packages/app-builder-lib/src/targets/LinuxTargetHelper.ts#L93) in app-builder-lib, part of electron-builder. It’s only generated for the deb, RPM, Flatpak, and Snap targets. For example, `Zulip-5.10.2-amd64.deb` includes it at `/usr/share/applications/zulip.desktop`.

```desktop
[Desktop Entry]
Name=Zulip
Exec=/opt/Zulip/zulip %U
Terminal=false
Type=Application
Icon=zulip
StartupWMClass=Zulip
Comment=Zulip Desktop Client for Linux
Categories=Chat;GNOME;GTK;Network;InstantMessaging;
```

If you’re packaging Zulip for another format, it’s up to you to create your own `zulip.desktop` file (or extract it from one of the electron-builder outputs).
