### ISSUE TITLE
Search doesn't include keywords from links

### ISSUE THREAD

**Issue by divaltor** [zulip/zulip-desktop#1329]
**Problem Description**

When you try to search some link from stream you probably just remember some keyword like `https://github.com/<user>/<project_name>` and you wanna find a message by searching for `<project_name>` from that link, but Zulip totally ignores any links

**Proposed Solution**

Zulip search inside links as well, not just messages

**Describe alternatives you've considered**

Slack works as expected

**Comment by andersk** [comment]
This issue is in the server, see

- https://github.com/zulip/zulip/issues/9165
- https://github.com/zulip/zulip/issues/19362
