### ISSUE TITLE
cannot open sent file in desktop app on osx big sur

### ISSUE THREAD

**Issue by devZer0** [zulip/zulip-desktop#1331]
**Describe the bug**

in zulip 5.10.0 you could download and open a file directly, when it was sent by another user in a pm/dm, but in 5.10.2 it behaves differently. there is no option anymore to open the file from zulip. 

i can save it to downloads, but then need to go to findert to open

**Comment by andersk** [comment]
Thanks for the report. Closing as a duplicate of #1333, which has a clearer diagnosis of the problem.
