### ISSUE TITLE
Download notifications don't show up in latest version

### ISSUE THREAD

**Issue by FeldrinH** [zulip/zulip-desktop#1333]
**Describe the bug**

With Zulip Desktop v5.10.0 when I clicked on a file it would download it and then show a notification that the file had been downloaded. Since updating to v5.10.2 this morning that no longer works. When I click on a file to download it it is shows up in the Downloads folder, but no notifiaction is shown and no other indication is given that the download had started or completed.

**To Reproduce**

Send/find a message with a file and click on the link once to download it. The file will appear in your Donwloads folder but no notification will show up indicating that anything happened.

**Expected behavior**

File downloads should show some indications that they were started/completed, just like they did in v5.10.0.

**Screenshots**

The file download notification that used to appear but no longer does:
![image](https://github.com/zulip/zulip-desktop/assets/5256211/7140ec42-7022-4afd-a3d3-a2f627a0c20a)

**Desktop (please complete the following information):**

- Operating System: Windows 10 (10.0.19045)
- Zulip Desktop Version: 5.10.2 (bug did not exist in 5.10.0)

**Comment by andersk** [comment]
Thanks for the report. I tracked this down to an upstream Electron change that broke the third-party `gatemaker` library, and opened javan/gatemaker#4. I’ll get a fixed release out shortly.
