### ISSUE TITLE
"Finish desktop login" needs to show the URL

### ISSUE THREAD

**Issue by feamsr00** [zulip/zulip-desktop#1353]
**Problem Description**

If the browser fails to load the third party login page, the application\login process is softlocked until the application is restarted.

**Proposed Solution**

Add the URL the application is trying to open to the "Finish desktop login" page.

**Describe alternatives you've considered**

NA

**Additional context**

![image](https://github.com/zulip/zulip-desktop/assets/983484/d0863e8d-75af-4692-a7e5-aff58b6eea72)

**Comment by andersk** [comment]
The app has a back button in the lower-left corner, as well as **History** → **Back** (`Alt`+`←`).
