### ISSUE TITLE
Adding  functionality of finding organization when connecting

### ISSUE THREAD

**Issue by Satvik1769** [zulip/zulip-desktop#1355]
**Problem Description**

It takes some time to find the organization URL and when we get that URL from other sources we can join the organization.

**Proposed Solution**

I wanted to change this by using name of organization instead we can use discord type naming convention, whenever a person write similar name to the organization we can show all the organization  similar to how youtube works. We can map the URL with the name of organization and when user write name it would be mapped and the URL will be sent further. It would be better that we add logo of organizations in the search list to further distinguish them.

**Describe alternatives you've considered**

Another alternative can be just write organization name and from backend it will bring the organization URL. This will benefit user since otherwise user have to try for two URL s moreover it will also confirm that whether organization is present or not.

**Additional context**

![image_2024-01-30_123252688](https://github.com/zulip/zulip-desktop/assets/101499823/05ee5dc5-8624-4f19-abb9-db526cc84e25)
![image](https://github.com/zulip/zulip-desktop/assets/101499823/67d74789-6295-4940-8b7d-832cded41ebd)

**Comment by alya** [comment]
Thanks for the suggestion! Closing this issue, as discussed [here](https://chat.zulip.org/#narrow/stream/16-desktop/topic/finding.20organizations.20to.20join/near/1729217).
