### ISSUE TITLE
Gray screen on Fedora 40 after latest mesa driver update

### ISSUE THREAD

**Issue by Quasar6X** [zulip/zulip-desktop#1375]
**Describe the bug**

Zulip deskop displays a gray background in the main content pane after latest Mesa driver updates on Fedora 40. It would make sense to me that the new driver packages caused this issue, however I've bulk updated a lot of packages (not including Zulip Desktop - it was already on 5.11.0) so it is possible that some other package update caused it. Unfortunately I've lost the terminal output of the update process.

I'd been using the desktop client on Fedora 40 since the release of the distro without any issues up until now.

**To Reproduce**

1. Install latest Fedora 40
2. Update to latest packages
3. Install Zulip Desktop
4. Start Zulip Desktop

**Expected behavior**

Zulip Desktop works.

**Screenshots**

![Screenshot from 2024-07-05 14-24-44](https://github.com/zulip/zulip-desktop/assets/7925250/e7564cfa-20ac-4229-8cc6-fa459b5b5b16)

**Desktop (please complete the following information):**

- Operating System:
Fedora 40 x86_64
- Zulip Desktop Version:
5.11.0

**Additional context**

My current Mesa packages:

```shell
$ rpm -qa | grep "mesa"
mesa-libGLU-9.0.3-4.fc40.x86_64
mesa-filesystem-24.1.2-7.fc40.i686
mesa-filesystem-24.1.2-7.fc40.x86_64
mesa-va-drivers-24.1.2-7.fc40.x86_64
mesa-libglapi-24.1.2-7.fc40.x86_64
mesa-dri-drivers-24.1.2-7.fc40.x86_64
mesa-libgbm-24.1.2-7.fc40.x86_64
mesa-libEGL-24.1.2-7.fc40.x86_64
mesa-libGL-24.1.2-7.fc40.x86_64
mesa-libOSMesa-24.1.2-7.fc40.x86_64
mesa-vulkan-drivers-24.1.2-7.fc40.x86_64
mesa-libxatracker-24.1.2-7.fc40.x86_64
mesa-va-drivers-24.1.2-7.fc40.i686
mesa-libglapi-24.1.2-7.fc40.i686
mesa-dri-drivers-24.1.2-7.fc40.i686
mesa-libgbm-24.1.2-7.fc40.i686
mesa-libEGL-24.1.2-7.fc40.i686
mesa-libGL-24.1.2-7.fc40.i686
mesa-libOSMesa-24.1.2-7.fc40.i686
mesa-vulkan-drivers-24.1.2-7.fc40.i686
```

**Comment by Quasar6X** [comment]
I would like to add that this bug is flaky, sometimes the client works but after going around to different streams it suddenly becomes gray and I have to restart the app multiple times until it starts normally.

**Comment by alya** [comment]
Thanks for the report, @Quasar6X ! I flagged this issue for discussion [in the Zulip development community](https://chat.zulip.org/#narrow/stream/16-desktop/topic/Gray.20screen.20on.20Fedora.2040.20.23D1375/near/1850044).

**Comment by Quasar6X** [comment]
Hey, @alya just wanted to let you know that I've fixed this issue. There was yet another driver update but simply clearing the cache in `$XDG_CONFIG_HOME/Zulip/Cache` and `$XDG_CONFIG_HOME/Zulip/GPUCache` did wonders even before that. I'm closing this issue now, sorry for wasting your time 😅

**Comment by alya** [comment]
No worries, thanks for letting us know!
