### ISSUE TITLE
Mac - red unread message icon / count not appearing on dock, menu bar or Zulip sidebar

### ISSUE THREAD

**Issue by johnathanz** [zulip/zulip-desktop#1376]
**Describe the bug**

I'm on Mac Ventura 13.6.7, running the latest Zulip mac client.

Whenever a new message comes in, I get the notification slide in as a Banner / Alert (top right side).

But there is no unread icon in:
* Zulip Dock icon
* Zulip menu bar icon
* left sidebar icon within Zulip

Zulip notification setting
![2024-07-06 at 15 06 00](https://github.com/zulip/zulip-desktop/assets/1593039/70680cef-2494-4e44-a914-b0758dfb28ca)

MacOSX notification for Zulip
![2024-07-06 at 15 07 20](https://github.com/zulip/zulip-desktop/assets/1593039/784e633e-06d5-4a27-9945-d22c60c0868a)

I was under the impression that the red bubble will appear for dock icon, menu bar icon at least.  What's the expected behaviour?

p.s. btw, the Zulip logo seem to be having some sort of issue in the notification settings. It's fine everywhere else

**To Reproduce**

1. With the Zulip desktop Mac app
2. Go into Personal Settings > Notifications
3. Click the "Send a test notification" button
4. Immediately press `CMD+M` to minimise Zulip

**Expected behavior**

* Notification should come in as an Alert / Banner (depending on Mac OSX Notification setting for Zulip)
* The unread notification should also appear in:
   * Zulip Dock icon
   * Zulip menu bar icon
   * left sidebar icon within Zulip

**Screenshots**

**Desktop (please complete the following information):**

- Operating System:

MacOSX Ventura 13.6.7

- Zulip Desktop Version:
Latest Zulip desktop version (downloaded last week). 

**Additional context**

We're using the cloud hosted version of Zulip

**Comment by johnathanz** [comment]
Apologies. Looks like notification is working for:
* Dock icon
* Sidebar icon within Zulip

`Test notification` never triggered those. But testing with the `Welcome bot` does trigger notifications for ☝️ .

Is the menubar icon meant to show an indication icon, because I have my dock hidden. So expected a red bubble to show against the Zulip menubar icon?
![2024-07-07 at 18 42 21](https://github.com/zulip/zulip-desktop/assets/1593039/d524db10-54e7-4916-854a-eab4004831f0)

**Comment by alya** [comment]
I think that's the same issue as #1279.

**Comment by alya** [comment]
I put up https://github.com/zulip/zulip/pull/30763 to add a note to the documentation, since the lack of an unread count icon with a test notification tripped you up.

**Comment by johnathanz** [comment]
thanks @alya . Recommend we update the documentation to have users "talk to Welcome bot" for notification testing as "Test notification button" only triggers Alerts on the Mac. Unread counters are not updated 😢 .

**Comment by johnathanz** [comment]
🤞 both this issue (Mac desktop) and #1279 (Linux desktop) could be fixed soon!  

I think the tray icon in Windows does work though

**Comment by timabbott** [comment]
Closing since https://github.com/zulip/zulip/pull/30763 fixed the part of this not covered in #1279. Thanks for the report @johnathanz!

**Comment by johnathanz** [comment]
All good @timabbott . Added my +1 to #1279

**Comment by johnathanz** [comment]
On Mac, I could surface the menubar notifications with [Doll](https://github.com/xiaogdgenuine/Doll)

The coloured icon is the one created by Doll, the white one is from the Zulip mac desktop icon
![2024-07-13 at 12 06 31@2x](https://github.com/user-attachments/assets/b201dba9-ab30-41c3-9b0b-64471ab4007c)
