### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly.

### ISSUE THREAD

**Issue by D0liphin** [zulip/zulip-desktop#1389]
**Describe the bug**

When running the Zulip AppImage, I cannot start Zulip.

**To Reproduce**

1. Install the Zulip AppImage on the target arch below
2. Run the following
```
> sudo chmod u+wrx ./Zulip-5.11.1-x86_64.AppImage 
> ./Zulip-5.11.1-x86_64.AppImage 
[67088:0928/120758.497901:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Zulip-aqQ8fJ/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Expected behavior**

Zulip should open

**Screenshots**

NA

**Desktop (please complete the following information):**

- Operating System: Ubuntu 24.04.1 LTS x86_64 (Wayland)
- Zulip Desktop Version: 5.11.1-x86_64

**Additional context**

This issue has previously been seen before [https://github.com/zulip/zulip-desktop/issues/912](https://github.com/zulip/zulip-desktop/issues/912).

This works fine with `--no-sandbox`.

**Comment by andersk** [comment]
This is a different issue that affects all Electron AppImage applications on Ubuntu 24.04; see

- electron/electron#42510

You can try the `sysctl` change described in that thread ([more information](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces)), but my suggestion would be to use one of our other package formats (deb, Snap, or Flatpak).

**Comment by D0liphin** [comment]
Right, will close this then, since it's not relevant.
