### ISSUE TITLE
offline Windows installer

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#148]
Some antivirus software blocks installers that download stuff. That's what we experienced with the web installer. 

Could there also be an offline installer?

Q: Can one just copy the installation folder to other machines and it will still run fine there (bypassing the installer altogether)? Then I would create a 7z executable with the installation directory.

**Comment by akashnimare** [comment]
Please download - 
* https://github.com/zulip/zulip-electron/releases/download/v0.5.10/zulip-0.5.10-x64.nsis.7z (for 32 bit)
* https://github.com/zulip/zulip-electron/releases/download/v0.5.10/zulip-0.5.10-ia32.nsis.7z (for 64 bit)

**Comment by timabbott** [comment]
We need to document this properly before we can really close this issue.

-Tim Abbott (mobile)

**Comment by akashnimare** [comment]
Documented about installers in https://github.com/zulip/zulip-electron/commit/e35661993d58133b0a7bf35df81325cb4e70e12e.
