### ISSUE TITLE
bug in Win 0.5.10: on sys tray quit

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#149]
When I right click the system tray icon and then quit I get this error. Sometimes I have to quit twice before it appears. After that the app is unresponsive and can only be killed with task manager. 

![JavaScript error occurred in the main process](https://cloud.githubusercontent.com/assets/26190934/26217061/6d352562-3c06-11e7-828f-b5b0a52cb60f.png)

and I have the zulip app as 5 processes (plus one I had killed).
![image](https://cloud.githubusercontent.com/assets/26190934/26217083/84586286-3c06-11e7-81db-a13d4ec72129.png)

Matthias Müller: killing the one without parameters (in the screenshot the fifth with the 1) kills all of them. Or I have to kill every single one separately.

killing the one without parameters (in the screenshot the fifth with the `1`) kills all of them. Or I have to kill every single one separately.

**Comment by penCsharpener** [comment]
you have to zoom into the second screenshot - it's very wide

**Comment by Lplenka** [comment]
I couldn't reproduce such error while running the app from our development repository. App worked fine.
Will verify this in the released app.

btw @vbNETonIce  do you always get this error when you quit app from tray? I mean what's the frequency of such errors?

**Comment by penCsharpener** [comment]
I'm not closing the app a lot but when I do it via sys tray every time. 
Setup Win10 1703 (15063 build number)
JavaRE 8.131 32bit if that matters

**Comment by penCsharpener** [comment]
now that we have 50 people using the app this is turning into a real problem because it happens all the time. The longer Zulip app is running the more processes it creates. lots os people don't know how to kill it with task manager and it's also further down in the list which makes it even harder to see. 

If this can be hotfixed I (we) would be much obliged.

**Comment by Lplenka** [comment]
This seems to be a serious issue :sweat:
I believe this issue is also related to upstream. I don't find any fault in code.
Couple of issues there, still under discussion.
[https://github.com/electron/electron/issues/2312](https://github.com/electron/electron/issues/2312)
[https://github.com/electron/electron/issues/4781](https://github.com/electron/electron/issues/4781)
[https://github.com/electron/electron/issues/2209](https://github.com/electron/electron/issues/2209)

@akashnimare @geeeeeeeeek Please have a look.

**Comment by akashnimare** [comment]
@vbNETonIce this is fixed in https://github.com/zulip/zulip-electron/commit/48ff50634484277faeb7f628179a61a444e04f46. Can you check it again?

**Comment by akashnimare** [comment]
Closing until more information is provided.
