### ISSUE TITLE
Cannot connect to server by IP address

### ISSUE THREAD

**Issue by Shayan-To** [zulip/zulip-desktop#150]
I don't have a domain for my server, but I have valid certificates and Chrome connects to it with no problem. At the first run of the app, when I enter the IP address of my server and click "Connect", it says "Not a valid Zulip server". And I checked developer tools, it even does not send a request to the server. I think the error comes from validation of the domain name of the server. And I could connect to chat.zulip.org with no problem.

OS: Windows 10.1703

**Comment by akashnimare** [comment]
@Shayan-To what IP-address you're trying to connect?

**Comment by Lplenka** [comment]
Our app doesn't support IP address for now. You can try domain names only.

**Comment by timabbott** [comment]
We should probably make this possible.

-Tim Abbott (mobile)

**Comment by Lplenka** [comment]
Yes, definitely we will add this feature. A lot of code has been changed after merging PR [#140](https://github.com/zulip/zulip-electron/pull/140). Hence, a few regression issues should be solved before we can safely introduce a new feature.

So, we will work on this, might take a couple of days.

**Comment by akashnimare** [comment]
Partially fixed in - [v1.2.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.2.0-beta), will improve it in later.
