### ISSUE TITLE
Zulip should stay in the system tray on close on Windows 10

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#160]
I got the following report from a user switching from the old desktop app to the new one:

> There is one feature however that no longer works for me : Zulip no longer remains in the system tray on close.  Since I have the habit of closing the window, I’m often forced to restart the app because of this (if I’m lucky enough to realize what I did).

Since this is a regression from the old app that we want to kill, I'm giving this relatively high priority.

**Comment by penCsharpener** [comment]
This would also solve #149 partly

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/48ff50634484277faeb7f628179a61a444e04f46. @vbNETonIce can you cross check it?

**Comment by penCsharpener** [comment]
I tried with the instruction given before (with npm install) etc. but it didn't work. I won't be able to test for the next 10 days unless maybe you ship an installer.

**Comment by akashnimare** [comment]
> I won't be able to test for the next 10 days unless maybe you ship an installer.


@vbNETonIce no problem then. We'll push a new pre-release in a day or two so you could test it :)

**Comment by akashnimare** [comment]
@vbNETonIce here is the latest [installer](https://github.com/zulip/zulip-electron/releases/download/v1.0.0-beta/Zulip-Web-Setup-1.0.0-beta.exe).

**Comment by akashnimare** [comment]
Fixed in [v1.0.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.0.0-beta). Closing, feel free to reopen if still occurs.
