### ISSUE TITLE
links sometimes open within Zulip app, should open in desktop browser

### ISSUE THREAD

**Issue by glyph** [zulip/zulip-desktop#164]
- Operating System:
  ```
  ProductName:	Mac OS X
  ProductVersion:	10.12.5
  BuildVersion:	16F73 
  ```
- App: version 0.5.10
- Just type a link, like https://google.com/, then click on it
- It opens in a window of the Zulip app (which is possibly a [terrifying security problem](https://github.com/electron/electron/blob/master/docs/api/sandbox-option.md)?) rather than in the selected preferred browser application (in my case, Safari).

**Comment by glyph** [comment]
Note: right click, "open link" does the right thing. It's just left-clicking that's behaving this way.

**Comment by timabbott** [comment]
This definitely seems like a priority issue.  Since @akashnimare is travelling, @geeeeeeeeek do you have time to look into this?

**Comment by zhongyi-tong** [comment]
@Tim Will fix today.

**Comment by timabbott** [comment]
Cool.  Probably worth adding a test for this, since it seems like something that's particularly bad to have regress.

**Comment by zhongyi-tong** [comment]
@glyph Cannot reproduce. The `new-window` listener has properly dealt with this scenario. External links will be open in browser.  Any others have the same problem?

![c](https://cloud.githubusercontent.com/assets/7262715/26680261/4e3e65b4-470b-11e7-9065-a90e7f87dc74.gif)

**Comment by timabbott** [comment]
Is it possible the bug is in our last release (0.5.10) but fixed since then?

**Comment by zhongyi-tong** [comment]
I don't think so. That part of code in `main.js` has not been changed since
it was there. Can anybody else reproduce this bug?

**Comment by akashnimare** [comment]
I can't reproduce this error on v0.5.10.

**Comment by glyph** [comment]
It's very consistent for me. Are there any diagnostics I could perform?

**Comment by zhongyi-tong** [comment]
@glyph Could you please leave a link where you downloaded the app? The release page?

**Comment by akashnimare** [comment]
Have you downloaded the app from release page i.e. [v0.5.10](https://github.com/zulip/zulip-electron/releases/tag/v0.5.10)?
> It's very consistent for me. Are there any diagnostics I could perform?

@glyph can you please remove the cached files and try again -

> `rm -rf /Users/yourusername/Library/Application Support/zulip`
> `rm -rf /Users/yourusername/Library/Application Support/electron`

**Comment by zhongyi-tong** [comment]
@glyph @akashnimare Still cannot reproduce. I tried with a clean install (downloaded from the release page) on macOS 10.12.5. At least we know it's not related to the app version and os version.

Could you please be more specific about where you get the app?

**Comment by zhongyi-tong** [comment]
Or, to solve the issue, could you please try downloading the app from the release page and re-install it?

**Comment by glyph** [comment]
Sitting back down at my work machine this morning, the issue has disappeared.  I can't seem to reproduce it with any sequence or combination of links I was using before.  Not sure if I updated or what, but apparently the issue is gone :).  If I can find some more specific behavior which provokes this I will reopen.

**Comment by zhongyi-tong** [comment]
Thanks @glyph. Feel free to reopen the issue if you have a clear steps-to-reproduce! 😃

**Comment by glyph** [comment]
Unfortunately I do not have clear steps to reproduce, but this started happening again.  Nothing I could see in the developer tools.  View -> Reload did not fix the problem, but quitting and re-launching the app did.  Checking the about box I can confirm this is version 0.5.10.

Are there any further diagnostics I can perform the next time this recurs?

**Comment by akashnimare** [comment]
@glyph please download [v1.1.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.1.0-beta).

**Comment by glyph** [comment]
I've now done so.

**Comment by akashnimare** [comment]
Is it still occuring?

**Comment by glyph** [comment]
It takes weeks between occurrences; the app has to get into a state where this is happening, it works correctly when it first starts up.  But for now: no, it has not recurred.

**Comment by akashnimare** [comment]
This is kind of mysterious. Please re-open again in future and try to remember the process which caused the bug.

**Comment by glyph** [comment]
There is no "process". I use the app for a week, sometimes links start opening inside app windows at random.  Once they do nothing fixes it but an app restart.  Nothing in the DOM inspector shows me clearly what's going on with the links; I need some guidance as to what to look for.

**Comment by timabbott** [comment]
@akashnimare is there an logging we could add to make investigating this easier?

**Comment by zhongyi-tong** [comment]
@timabbott I don't think so. We can design a logging system for actions like opening a tab, navigating to a new url, etc. But I'm not sure how much it will help with our debugging.

**Comment by timabbott** [comment]
If the example URL weren't google.com, I could imagine our work on #204 fixing this.  But given that it is, I don't understand how this issue is possible from reading the code.

**Comment by akashnimare** [comment]
https://github.com/zulip/zulip-electron/commit/9e4e5e9bfd355c4612e1e24b5b7d39555941d770 should fix this issue.

**Comment by glyph** [comment]
Let me know when there's a new build to test, and I'll be happy to report if it happens again.

**Comment by akashnimare** [comment]
@glyph Here - [v1.3.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.3.0-beta). Re-open if it happens again.

**Comment by glyph** [comment]
Thanks! I haven't seen it in a while as it is, but I'll definitely keep an eye out.
