### ISSUE TITLE
intermediate certs aren't supported.

### ISSUE THREAD

**Issue by theundefined** [zulip/zulip-desktop#17]
I have server which have cert class1 from startssl. It works fine, browser works, server send own certificate and intermediate certificate.

But - zulip-desktop on linux doesn't work with it.
It works when fine when i use --allow-insecure, or when i add intermediate cert for ca-certificates (https://www.startssl.com/certs/sub.class1.server.ca.crt do /etc/ssl/certs, and update-ca-cert to make links.

Without that - it only show blank white page with information that:
11:07:54 Debug: Error: "The issuer certificate of a locally looked up certificate could not be found" "The issuer certificate of a locally looked up certificate could not be found" QSslCertificate( "3" , "06:70:ff:72:ff:ae:ff" , "1calalaMfXldsfsdf3L/idsff==" , "StartCom Ltd." , "" , QMap((1, "mydomain.org")(1, "mydomain.org")) , QDateTime("czw. paź 15 08:25:10 2015") , QDateTime("sob. paź 15 01:40:46 2016") )
11:07:54 Debug: Error: "The root CA certificate is not trusted for this purpose" "The root CA certificate is not trusted for this purpose" QSslCertificate( "3" , "06:70:59:ff:ff:ae:ff" , "sfdsafdaswsfdsdfaslasdfsasdfas/sdfsa==" , "StartCom Ltd." , "" , QMap((1, "mydomain.org")(1, "mydomain.org")) , QDateTime("czw. paź 15 08:25:10 2015") , QDateTime("sob. paź 15 01:40:46 2016") ) 
11:07:54 Debug: Error: "No certificates could be verified" "No certificates could be verified" QSslCertificate( "3" , "06:ff:ff:ff:ff:ff:d2" , "1cMsdfasdfasfsdfIsadfsaqsdfas/isdfas==" , "StartCom Ltd." , "" , QMap((1, "mydomain.org")(1, "mydomain.org")) , QDateTime("czw. paź 15 08:25:10 2015") , QDateTime("sob. paź 15 01:40:46 2016") )

I've checked that peerverifydep is 0 - so intermediate certs should be supported.
Does anybody have idea what's wrong?

**Comment by lfaraone** [comment]
Please verify your server is correctly sending the intermediate certificate. 

Zulip.com uses an intermediate certificate ("DigiCert SHA2 High Assurance Server CA"), and the client is able to verify the chain correctly.

**Comment by theundefined** [comment]
sorry, my fault. intermediate certifivate was invalid. now - works fine :-)

**Comment by timabbott** [comment]
I'm thinking we may want to add an easy way to test on the server side for whether a proper set of intermediate certs is setup so that folks catch this issue while configuring their server...

**Comment by timabbott** [comment]
I'll open a ticket for that
