### ISSUE TITLE
"Use Beta App"

### ISSUE THREAD

**Issue by SimplyAhmazing** [zulip/zulip-desktop#173]
There should be a drop down menu allowing a user to use the Electron app in a beta mode. This will allow us to release beta versions of the app to a fraction of the user base (those with beta app mode enabled) in order to have them act as a test population for app changes and updates. Partial rollout is the most ideal way to test new features and changes.

**Comment by akashnimare** [comment]
@SimplyAhmazing electron-builder has added the exact feature we were talking about :) 

![image](https://user-images.githubusercontent.com/2263909/29094944-d859dcc0-7cac-11e7-8455-0843dc44fc87.png)

**Comment by akashnimare** [comment]
Added in [v1.3.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.3.0-beta).
