### ISSUE TITLE
unread status-menu indicator is not updated

### ISSUE THREAD

**Issue by keturn** [zulip/zulip-desktop#177]
On OS X, the unread indicator in the menu bar is often incorrect.

Screenshot, where I believe I have no unread messages in non-muted channels, but the indicator says 9:

![zulip-electron-unread-counter](https://user-images.githubusercontent.com/83819/27149740-75448452-50f9-11e7-92a2-54932a7d3fde.png)

The indicator also does not update when I click **Home** to view all messages and scroll to the bottom, etc.

This was a regression we noticed sometime around the time of PyCon. One of our team says that commit f9f21cd626779be9d1d364d1739cd7da0e71a13ea works better.

**Comment by zhongyi-tong** [comment]
@zulipbot claim

**Comment by akashnimare** [comment]
Tray icon show's the sum of unread messages presents across all the teams.

![screen shot 2017-06-15 at 2 16 30 pm](https://user-images.githubusercontent.com/2263909/27221480-5c02b1b8-52a6-11e7-812d-773f66961d7d.png)

@geeeeeeeeek this is fixed in #168, right?

**Comment by zhongyi-tong** [comment]
@akashnimare I think so.

**Comment by akashnimare** [comment]
@keturn can you reproduce this on latest master?

**Comment by akashnimare** [comment]
This issue has been fixed. Please reopen if this issue still occurs.
