### ISSUE TITLE
"Can't connect with the client" errors are confusing when cause is invalid cert chain

### ISSUE THREAD

**Issue by WPTechnician** [zulip/zulip-desktop#178]
I am running Windows 10 Professional as a client.  When I run the client I am getting the message, "Not a valid Zulip server".  I can log in to Zulip through a browser without issue.  The SSL cert is not self-signed.  I am not sure where to go from here.

Thanks! 

---
Please include: 
- `Operating System`
- `Clear steps to reproduce the issue`
- `Relevant error messages and/or screenshots`

**Comment by WPTechnician** [comment]
It was a bad cert chain.  Thanks!

**Comment by timabbott** [comment]
@akashnimare could we provide a better error message for invalid cert chains that helps the sysadmin debug?

**Comment by akashnimare** [comment]
@timabbott did you mean the message in error dialog?

<img src="https://cloud.githubusercontent.com/assets/13533873/25277023/9dd64266-26ba-11e7-9939-b8f5853495cb.png"/>

**Comment by timabbott** [comment]
Well it sounds like @WPTechnician got a different error than that.  @WPTechnician can you post a screenshot of what you saw?

**Comment by WPTechnician** [comment]
It simply said that the entered URL wasn't a valid Zulip server, no other error. The root cause was that my intermediate cert in my bundle was the wrong one. The actual error after tracing was:

Verify return code: 21 (unable to verify the first certificate)



On Jun 16, 2017 3:35 PM, Tim Abbott <notifications@github.com> wrote:

Well it sounds like @WPTechnician<https://github.com/wptechnician> got a different error than that. @WPTechnician<https://github.com/wptechnician> can you post a screenshot of what you saw?

**Comment by akashnimare** [comment]
More detailed message has been added in master.
