### ISSUE TITLE
server icon path error [Windows]

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#181]
On Windows system, the default server icon is not showing up due to the [path error](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/domain-util.js#L9).

![image](https://user-images.githubusercontent.com/2263909/27306852-ec665870-5564-11e7-8dfd-c4c88a22400b.png)

**Comment by zhongyi-tong** [comment]
@akashnimare Could you take a look at this? I don't have a Windows machine...

**Comment by akashnimare** [comment]
Tried everything, no luck yet. Windows 😿 .

**Comment by akashnimare** [comment]
@geeeeeeeeek the URL in background-image does not work as expected on windows. 

``` javascript
const defaultIconUrl = __dirname + '../../../img/icon.png';

<div class="server-tab" style="background-image: url('${this.props.icon}');"></div>
```


It appends the path of the directory from which it running to the path of server icon which results in the path error. For an example, the end bg-image URL would look like this -

```
file:///C:/Users/akash/dev/zulip-electron/app/renderer/C:/Users/akash/AppData/Roaming/Zulip/server-icons/917.png

```



To fix this, I have implemented the same styling with img tag in [windows-path-issue](https://github.com/zulip/zulip-electron/tree/windows-path-issue). Let me know if it looks good.


<img src="https://user-images.githubusercontent.com/2263909/28753267-99a8d27e-754f-11e7-9a32-2be633731731.png" width="200"/> <img src="https://user-images.githubusercontent.com/2263909/28753268-a8f0b846-754f-11e7-8bd3-3ffb44b7629f.png" width="200"/> 


![image](https://user-images.githubusercontent.com/2263909/28753255-7b4c1908-754f-11e7-9feb-9df4a1f07e06.png)

<img src="https://user-images.githubusercontent.com/2263909/28754273-e3f098b6-755f-11e7-8dc1-ac89696b9afc.png" width="150"/> <img src="https://user-images.githubusercontent.com/2263909/28754260-bf5f2e5e-755f-11e7-94c7-2fafcca3bcd4.png" width="150"/>

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/d8c08c1c5bea67fcdde334143f13452a474e4bd2.
