### ISSUE TITLE
Can't turn off notification sound on osx

### ISSUE THREAD

**Issue by ehues** [zulip/zulip-desktop#186]
I can't turn off notification sounds for stream messages. I have audible notifications disabled In my user settings and on the stream settings, but I still get an audio alert when the OSX notification bubble appears. 

User settings:
![screen shot 2017-06-21 at 1 31 21 pm](https://user-images.githubusercontent.com/4691994/27397964-25a13624-5686-11e7-954a-73c5281d4895.png)

Stream settings
![screen shot 2017-06-21 at 1 33 39 pm](https://user-images.githubusercontent.com/4691994/27398144-d359dc8a-5686-11e7-80f9-193b238df154.png)

Operating System: OSX 10.11.6 (15G1421) (El Capitan)
Version: 1.0.0-beta

**Comment by akashnimare** [comment]
@ehues possible workaround is to turn off the sound from notification center until we fix this -

![image](https://user-images.githubusercontent.com/2263909/27499880-72c62e38-5883-11e7-97be-ce9bc4e6da65.png)

**Comment by ehues** [comment]
Thanks for the workaround.

**Comment by akashnimare** [comment]
@timabbott On disabling audible notifications the **silent parameter** should be `true`, right?

![screen shot 2017-07-01 at 12 37 27 pm](https://user-images.githubusercontent.com/2263909/27759977-6563f338-5e5a-11e7-9a5c-e6eb0ce1774f.png)

**Comment by akashnimare** [comment]
Ohh wait, here is the original logs - 

![image](https://user-images.githubusercontent.com/2263909/27796892-3ab08298-6029-11e7-85f5-6667c45aeaaa.png)

There is no silent parameter, we need to send it (via webapp) so that electron can inhirit the sound settings as well.

**Comment by akashnimare** [comment]
Added setting for controlling sound for new notification.

![image](https://user-images.githubusercontent.com/2263909/27927636-0ff76d04-62aa-11e7-94a3-b620c8c0d83b.png)

**Comment by akashnimare** [comment]
@timabbott Is it possible to send the `silent` parameter as well while sending a [new notification](https://github.com/zulip/zulip/blob/9461f490c83c35eecbea6a165bcf9effa85d9703/static/js/notifications.js#L33) through web app?

**Comment by timabbott** [comment]
@akashnimare can you explain the question a bit more?

**Comment by akashnimare** [comment]
Fixed in [v1.2.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.2.0-beta).
