### ISSUE TITLE
Unable to Minimize to System Tray

### ISSUE THREAD

**Issue by versipellis** [zulip/zulip-desktop#187]
Win 7 Enterprise. There doesn't seem to be an option to minimize to system tray, even with the system tray icon enabled. X'ing out of it closes the app entirely, which is quite different from my expectations coming from Discord and Slack.

**Comment by akashnimare** [comment]
@versipellis What version of zulip you're using? This issue has been fixed in [v1.0.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.0.0-beta).

**Comment by versipellis** [comment]
Ah, my apologies!

**Comment by akashnimare** [comment]
No worries :)
