### ISSUE TITLE
close settings bug

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#188]
A user reported this - 

If you close the settings tab while on a different tab, any tab that isn't the first zulip server, then you get a split view of the first zulip server and the tab that you were on.

![close_settings_bug](https://user-images.githubusercontent.com/2263909/27501178-55c1597e-5889-11e7-8e01-bc3d76b4edfd.gif)

**Comment by zhongyi-tong** [comment]
It happens on my machine.. I will send a fix soon.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/cda8aa3b09ce15da60e1bde176eba641363fdefd.
