### ISSUE TITLE
Please document command line switches for the desktop app somewhere?

### ISSUE THREAD

**Issue by wolfen351** [zulip/zulip-desktop#19]
Well the title says it all really.. Please document command line switches for the desktop app somewhere?

I *think* these switches exist:

* --site https://www.sitename.com     - this opens the client app using the site specified
* --debug                                           - This outputs debug info (unconfirmed)
* --allow-insecure                              - May allow bad certs to be ignored (self signed) (unconfimed)??

**Comment by timabbott** [comment]
Probably the right solution here is to add a `--help` option that documents these.

**Comment by oemergenc** [comment]
Hey, i am still having trouble in getting the --allow-insecure switch to work. Can anyone post the complete command line switch used on windows to start the application with this flag enabled? I was not able to get any of those switches to be enabled after startup. Usually, i am using a bat file for tasks like this. However, nothing seems to work.

i tried the following command:
<code>
start "" "C:\Program Files (x86)\Zulip\zulip.exe" --allow-insecure
"C:\Program Files (x86)\Zulip\zulip.exe" --allow-insecure
</code>
When using the debug switch, shouldn't be there more verbose messages on the command line. This command does not print any message, only start zulip with blank screen
<code>
start "" "C:\Program Files (x86)\Zulip\zulip.exe" --debug
</code>
I am using the latest available binaray from here: 

https://zulip.com/dist/apps/win/

Thanks for any advice

**Comment by lfranchi** [comment]
@STRML feel free to open a PR with that commit! Once you sign the CLA i'll happily merge :)

**Comment by STRML** [comment]
Whoops, didn't realize I opened it on my own repo - will move it.
