### ISSUE TITLE
Add a configuration option for connecting through an HTTP proxy

### ISSUE THREAD

**Issue by shane-kearns** [zulip/zulip-desktop#198]
Some users want to connect from a machine in one network to a zulip server on another network where direct connections are not possible and all traffic must go via an HTTP proxy.
e.g. client on a corporate network, server on the public internet.

Transparent / intercepting proxies require no configuration on the client, but lots of organizations still use traditional HTTP proxies. The CONNECT method allows establishing a TCP tunnel for HTTPS connections.

Electron appears to support this via the [Session.setProxy](https://electron.atom.io/docs/api/session/#sessetproxyconfig-callback) API.

The best behaviour from a user's POV is to fetch proxy settings from the operating system.
* On Windows, this will be somewhere in the registry (configurable through control panel / internet explorer; or may be pushed centrally for enterprise versions)

The second best option is a configuration option in the app's settings.
This will be equivalent to configuring Firefox, and the app won't work "out of the box" but the configuration option will be easy to find by looking in the settings.

The "minimum viable product" would be a command line switch or environment variable; which makes connection possible for expert users.

The electron API offers both `pacScript` and `proxyRules`.
A PAC (proxy auto configuration) script is a javascript document usually provided as a URL; it tells the browser on a per-URL basis which proxy to use (or 'DIRECT' for none).
The PAC script is the most likely configuration in a corporate environment
`proxyRules` gives the same capabilities as a table.
Most browsers have a single proxy server, and a list of exceptions when using static configuration.

For testing, 'squid' is a relatively easy to configure HTTP proxy available on many Linux distros.

**Comment by akashnimare** [comment]
@shane-kearns thanks for the detailed info. I'll look into it.

**Comment by zhongyi-tong** [comment]
Done in #278.
