### ISSUE TITLE
enhancement: ability to view /stats, /integrations, /about pages in the app

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#203]
would be nice to have those links below show up directly in the app but then we also need a working 'go back' to home button

https://chat.zulip.org/stats
/integrations
/about
pages in the app

**Comment by timabbott** [comment]
@vbNETonIce can you explain why you would prefer these to be in the app (and are the reasons the same for each)?  For several of these pages, we want them to be visible to Google (and thus there's benefit in them not being part of the app).  We could move some (e.g. /stats) into a modal like the settings UI, but it would offer a bit less space on the screen for the actual content.

**Comment by timabbott** [comment]
Oh, I see this is a desktop app issue.  I can see why you'd want it to not open a browser window when those are clicked; is that the motivation?

**Comment by penCsharpener** [comment]
yes, I mean the desktop app. It doesn't quite make sense since it's Zulip server related and the users would probably expect it to appear right in front of them rather than in an entirely different application (ie. browser).

**Comment by akashnimare** [comment]
@vbNETonIce If you click on `/integrations` it will get open in the app itself, not in the browser and you could always go back using `CommandOrCtrl+[`.

**Comment by penCsharpener** [comment]
cool, I tried and it worked. So if /stats will open in a popup soon, we can close this issue already...

**Comment by akashnimare** [comment]
To open it in the app, `/stats` should be hyperlinked somewhere in the webapp just like `/integrations`.

**Comment by timabbott** [comment]
Yeah, I think we can close this issue.  The plan for #204 should address this as well.
