### ISSUE TITLE
improvement: let users choose into which path they install the app

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#205]
This is about the installer. 

Currently the app installs automatically into `%programfiles%`. This folder requires elevated rights. Maybe the user or admin prefers a folder without elevated right to perform script-based updates. 

Can this be added to the installer or at least a radio button option to install it either there or into `%appdata%\Zulip`?

**Comment by akashnimare** [comment]
@vbNETonIce Fixed. Now user will be able to decide where to install the app.

![install](https://user-images.githubusercontent.com/2263909/28194552-9c319674-6862-11e7-9708-9ea97f7d33f2.PNG)
