### ISSUE TITLE
Home view suddenly marks all as read

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-desktop#209]
I'm on Linux with the 1.2.0 beta, which I just installed a few minutes ago.

I'm not sure exactly what just happened, but here's my best reconstruction:
* I opened the app for the first time. At that time I had maybe a few dozen unread messages, having just sat down after an hour afk.
* I narrowed to the `#electron` stream for discussion, and read and sent a bunch of messages there, navigating between various topic narrows and the stream narrow. I think I also went briefly back to home at some point.
* The discussion in `#electron` was done for a bit, and I hit `Esc` to go back to home.
* The app showed the home view, in a version that looked plausible but I didn't get a good view of it -- because after maybe 200-600ms it suddenly flashed or jerked around, and all the unread indicators faded away and the unread counts (except of muted streams) disappeared.

Yikes! Fortunately it's not many messages and I can pretty easily catch up by hand without the aid of any unread markers.

**Comment by timabbott** [comment]
Sounds like a scroll being triggered by the app that's buggy.  I'm not sure why the app would be doing scroll actions at all, but seems worth looking through the desktop codebase for any scrolling code that could cause this.  I haven't heard reports of something similar in the Zulip webapp, so it seems likely this is a desktop-specific issue.

**Comment by gnprice** [comment]
Hmm, that reminds me -- @jhurwitz [mentioned recently](​
https://chat.zulip.org/#narrow/stream/frontend/subject/pointer.20bug/near/246965)
a bug that brought the pointer to the present for him. That one involved
the web, and possibly mobile but probably not because the mobile app
crashed promptly on startup.

Does that qualify as something similar? I think we haven't otherwise had
reports of scrolling to the end in a while.

**Comment by gnprice** [comment]
@jhurwitz ^ (sorry, should have learned by now that GitHub's handling of email reply comments is too buggy to attempt anything more than the plainest of text)

**Comment by zhongyi-tong** [comment]
I don't think there is code to do scrolling in the desktop app. The behavior should be exactly the same as in browser. i.e. as you scroll down the messages, the unread count will decrease; but the app itself will not trigger a scroll.

**Comment by akashnimare** [comment]
@gnprice let us know if you could reproduce this again.

**Comment by timabbott** [comment]
We have a related bug we're investigating in the webapp; we should probably resolve that and then check back in on this one, if it's the case that the app itself literally never scrolls.

**Comment by akashnimare** [comment]
@timabbott is this fixed in webapp? If yes, then we can close this.

**Comment by timabbott** [comment]
It isn't, but there is a bug in the webapp that's probably this, so maybe it makes sense to just track it there.

**Comment by gnprice** [comment]
For clarity of cross-reference: I believe this is zulip/zulip#4720 .
