### ISSUE TITLE
selected server highlighting, remove ^ and replace with low contrast Ctrl

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#210]
* current look is very Slack-like
* select server highlighted with a change in background colour
* remove ^ and replace with `Ctrl +` because few know that `^` stands for
@timabbott suggest something with a background change

here an attempt to capture that thought
![image](https://user-images.githubusercontent.com/26190934/28140880-8019ae62-675a-11e7-85c1-10a416a7d14f.png)

**Comment by penCsharpener** [comment]
oops, pressed enter to early
hotkey should not be white but lower contrast colour to stand out less

**Comment by timabbott** [comment]
The more important argument for changing the white bar to a colored region style is that several users didn't realize that the white bar marked the server that's currently open.

One detail we need to think about is whether the hotkey label should be inside the selected color region.

As a sidenote, we probably should show the name of the organization in hover text if you mouse over it.

**Comment by zhongyi-tong** [comment]
Make sense. @vbNETonIce  I will pick a darker color.

@timabbott What do you mean by `selected color region`? I don't quite understand.

**Comment by timabbott** [comment]
Sorry, that was kinda unclear.  "selected color region" was meant to to reference, in @vbNETonIce's second screenshot, the region around the icon for the currently active server (which I referred to as "selected") with a different color.  

Thinking about this a bit more, I think it'd probably look ugly to have that the color not be symmetric about the icon, and @vbNETonIce's mockup looks fine, so I think we could try running with that layout (probably worth playing with the colors as @geeeeeeeeek suggests).

**Comment by zhongyi-tong** [comment]
![image](https://user-images.githubusercontent.com/7262715/28279406-011d4abc-6ae6-11e7-8200-0d7ae5303ee1.png)

What do you think? @timabbott 

I'm still tuning the colors, but do you like the idea?

**Comment by timabbott** [comment]
I think the idea works.  Though maybe the "option-1" is too bright in the highlighted choice?

@gnprice what are your thoughts?

**Comment by penCsharpener** [comment]
1) does the Google `G` have transparency (ie. `.png` Icon)? 
2) The `^` has been replaced with the Mac command icon. Will it say `Strg` on Windows?

_Sent from my HUAWEI PRA-LX1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by timabbott** [comment]
@vbNETonIce re: 2:  it'll show the appropriate key for that platform; which I think is `Ctrl`.

**Comment by zhongyi-tong** [comment]
@timabbott I changed `#cee2db` to `#afd2c6`, a little bit darker. I think it won't stand out as much as it did.

@vbNETonIce It's a png but it's not transparent. 

![image](https://user-images.githubusercontent.com/7262715/28296390-99b1e566-6b2d-11e7-9bdd-d44a85b3c31c.png)

**Comment by gnprice** [comment]
That screenshot looks good! I think I would understand that the highlight means that's the currently-selected item.

Showing the "Command-key" glyph on macOS makes sense. Is that style with "⌘ 1", with a space between the "command" glyph and the number, the style you'd find in e.g. a keyboard-shortcut label in a menu? It'd be good to match that style, I think.

On Linux, what I see in for example the Chrome menu is "Ctrl+T", "Ctrl+N", etc., with no spaces; so we should match that style with "Ctrl+1", etc. I think the same is true on Windows, but it'd be good for someone with Windows handy to check.

**Comment by zhongyi-tong** [comment]
Yep. It looked wired if the string is too long. Now that the style has been
updated, I will change it to Ctrl+1. 😀
Greg Price <notifications@github.com>于2017年7月18日 周二上午10:17写道：

**Comment by zhongyi-tong** [comment]
The `Ctrl + 1` shortcut text has been updated.

By the way, @akashnimare came with a silghtly different style, which looks like below:
![image](https://user-images.githubusercontent.com/7262715/28376618-300d34dc-6c70-11e7-919d-8f53b175a323.png)

Which one do you prefer?

**Comment by timabbott** [comment]
I think I prefer the new style.

**Comment by brockwhittaker** [comment]
I think this would look better if the edges of the selected icon didn't extend out to the edge of the sidebar but rather had a margin of ~5px, and had a slightly rounded border.

**Comment by zhongyi-tong** [comment]
@timabbott @brockwhittaker @akashnimare @gnprice It has been implemented in #219. Feel free to try it out!

![image](https://user-images.githubusercontent.com/7262715/28428953-a66d3a66-6d40-11e7-8da0-e9309ead2a62.png)

![image](https://user-images.githubusercontent.com/7262715/28428959-ab655d00-6d40-11e7-9e3d-c230ae84f5c7.png)

**Comment by brockwhittaker** [comment]
I definitely think it would look clearer if the :active color didn't extend out to the edges.

**Comment by timabbott** [comment]
Thanks for doing this @geeeeeeeeek.

Brock's suggestion seems like an alternative worth prototyping to see how it looks :)

**Comment by akashnimare** [comment]
Hmm, that will look like this -

![image](https://user-images.githubusercontent.com/2263909/28460847-8d3c275e-6e31-11e7-806b-344da02a892d.png)

![image](https://user-images.githubusercontent.com/2263909/28460868-abd59998-6e31-11e7-9e5c-aeb7b8b9dae2.png)

this looks better :)

**Comment by zhongyi-tong** [comment]
Thanks @akashnimare. Vote time :)

**Comment by akashnimare** [comment]
https://github.com/zulip/zulip-electron/issues/210#issuecomment-316972620 does not look good when it's not active. How about this -

![image](https://user-images.githubusercontent.com/2263909/28461370-f89b3b78-6e33-11e7-8c8f-81d6581a6775.png)

![image](https://user-images.githubusercontent.com/2263909/28461386-07a56d00-6e34-11e7-8fa5-001730e4e7d8.png)

**Comment by penCsharpener** [comment]
I think I like it more without the round edges and margins. With the current design you are more vulnerable to shape clashes. With the Zulip server icon it might work but the other one which is square it clashes. There are more changes in colour overall making it more busy than necessary. 
Also the selector is only different in brightness. But there is basically a selector around every icon which is not at all obvious.

**Comment by timabbott** [comment]
Yeah I think it looks better without the rounded corners and margins.

**Comment by akashnimare** [comment]
Added in https://github.com/zulip/zulip-electron/commit/697948c9d899e2d66739f59f6d9e89914235af4b. Thanks everyone for your suggestions 😄
