### ISSUE TITLE
"Mandatory" URL and server name fields not enforced

### ISSUE THREAD

**Issue by jrowan** [zulip/zulip-desktop#211]
(Version 1.2.0-beta on Windows 10)

Other than the certificate warning, Zulip isn't trying to stop me (e.g. with a "Error: please enter a valid URL" message) when I try to create a server without a URL (or a server name).

Steps to reproduce:
1. Go to the servers page on settings and click "add a new server"
2. Do not fill in any of the fields, just hit "Save"
3. When the following warning shows up
![image](https://user-images.githubusercontent.com/5571464/28141988-fad4c3ae-672c-11e7-86e1-30d194d1af6a.png)
click  "OK."
4. Note that another server has been added, and click on the icon for the newly-created server (I get the following):
![image](https://user-images.githubusercontent.com/5571464/28142045-3364d2f4-672d-11e7-84d5-88e1566339e7.png)

**Comment by timabbott** [comment]
From a flow perspective, we should actually just ask the user for a server URL, and fetch the other fields from that server.

**Comment by akashnimare** [comment]
@jrowan thanks for the bug report. That validation failed due to https://github.com/zulip/zulip-electron/commit/3f93a3346f6d02d3c41fe6af0d56fabb8c940328. Fixed in https://github.com/zulip/zulip-electron/commit/5a2975ca4d40ca6418cbefb0b6fe7eb15cb5e03f.
