### ISSUE TITLE
Forced focus regain on reconnecting to the server

### ISSUE THREAD

**Issue by aero31aero** [zulip/zulip-desktop#212]
When the user disconnects from the internet and reconnects, the app regains focus, even causing a workspace switch. I believe the reconnection to the server triggers this.

OS: Elementary OS 0.4 (Ubuntu 16.04)
Steps to reproduce: Focus another window. Disable networking. Enable networking. Wait.
Expected incorrect behavior: Zulip Desktop app automatically regains focus.
Expected behavior: Nothing/desktop notification saying "Reconnected to server".

**Comment by aero31aero** [comment]
![issue demonstration](https://user-images.githubusercontent.com/8033238/28143749-e1fd17ca-6784-11e7-843f-510828918a7a.gif)

**Comment by zhongyi-tong** [comment]
Yep, because the app reloads itself when reconnection. I will see if we can do it in the background.

**Comment by akashnimare** [comment]
@geeeeeeeeek  I don't think that it's possible to reload the app in the background. If the window is not focused/minimized we could just send a new notification (Instead of reloading).

**Comment by timabbott** [comment]
We don't need to reload the app, just the window?  Browsers seem perfectly able to do this in the background, so it seems like it should be possible to do it in Electron (though perhaps not easy)

**Comment by zhongyi-tong** [comment]
@timabbott @akashnimare @aero31aero With a new implementation, the reload will now be silent and seamless, and will no longer regain focus.
