### ISSUE TITLE
On activating Window 2 click needed to write into compose box [Linux/Windows]

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#216]
when the Zulip desktop app is inactive and I click into the compose box with the mouse then it only activates the Windows. I have to click a second time to get the cursor into the compose box and start typing. 

```quote
Tim Abbott: Hmm, this sounds like a window focusing issue with the multi-organization support...
```

**Comment by shane-kearns** [comment]
This also occurs on ubuntu14.04 linux with the 1.2.0-beta

**Comment by akashnimare** [comment]
Does it also happen with trackpad/touchpad click? Can you guys paste a gif/video here. I can't reproduce this on Ubuntu 16.04.

**Comment by akashnimare** [comment]
Okay, I can reproduce this on Windows.

**Comment by akashnimare** [comment]
So removing the [focus event]( https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L68 ) fixes this problem. @geeeeeeeeek does it break anything? I think we're not handling the focus event properly i.e [here](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/components/webview.js#L98).

**Comment by akashnimare** [comment]
@geeeeeeeeek ping.

**Comment by akashnimare** [comment]
It's a known issue, see -
https://github.com/electron/electron/issues/1773
https://github.com/electron/electron/issues/5900

**Comment by zhongyi-tong** [comment]
@akashnimare yeah, I found the issue. It's Windows specific. But actually, the webview is focused when the app regains focus. I'm finding out how to fix it.

**Comment by zhongyi-tong** [comment]
With an explicit focus on webview, it works well on macOS and Linux but not on Windows. Removing the explicit focus fixes the issue on Windows but breaks on macOS...

**Comment by timabbott** [comment]
I guess we can have a conditional by platform?

**Comment by akashnimare** [comment]
Yeah, that would work. I have tested following solution which works well on all platforms -
```` javascript
focus: process.platform !== 'win32' ? 'focus' : '',
````

**Comment by akashnimare** [comment]
Possible workaround for this issue is to switch to app using `Alt+Tab` so that you don't have to click twice on input.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/20feb9bd388d946ce4e6f9478c762ad32de3e27a.
