### ISSUE TITLE
Error while running dev

### ISSUE THREAD

**Issue by fragm3** [zulip/zulip-desktop#217]
Operating system: Unix

When I run _**npm run dev**_, the following error comes:

<img width="1128" alt="screen shot 2017-07-17 at 12 38 23 pm" src="https://user-images.githubusercontent.com/18073126/28258141-3f44ba44-6aed-11e7-9c41-7e8ef2c71f1a.png">

**Comment by timabbott** [comment]
That `EADDRINUSE` error suggests the problem might be you have some stale processes running?

**Comment by fragm3** [comment]
Yup, thanks its working now.

**Comment by timabbott** [comment]
OK.  We could probably catch EADDRINUSE errors and give a nice error message explaining what's going on and that you probably need to kill an existing copy.  Thoughts?

**Comment by fragm3** [comment]
That would be great! I actually installed a fresh setup, don't have that error anymore.

**Comment by zhongyi-tong** [comment]
@timabbott @akashnimare I suggest we should close this issue. The behavior is inherited from electron and nodejs and there is nothing we can do about it. It's not feasible to catch the error by `process.on('uncaughtException')` in `main.js` because electron terminates before running that script.

**Comment by timabbott** [comment]
Cool, thanks for investigating @geeeeeeeeek!  @fragm3 if you're interested in helping further here, you could add a troubleshooting guide to our docs that mentions this.

**Comment by akashnimare** [comment]
Solution for this problem -
* First get the process ID (PID) of the process running on that port (say 30080):
```sh
lsof -i tcp:30080
```
This will return something like:
```sh
COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node     5738   You   11u  IPv6 0xac745b2749fd2be3      0t0  TCP *:ddi-tcp-1 (LISTEN)
```
* Kill the PID using - 
```sh
kill -9 5738
```
