### ISSUE TITLE
default installation path

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#220]
before the #205 Zulip installed itself into `C:\Program Files\Zulip` but now it's `C:\Program Files (x86)\Zulip` 
can that be changed back please as most current users have it on the one location already and this will only lead to Zulip being installed twice. 

on Win10 you have to install one from the new settings menu (apps and programs) and the other from the old control panel > programs and features. It's a bit messy.

**Comment by penCsharpener** [comment]
I meant to say that although the user can now change to path to whatever they wish most people stick with the default.

**Comment by penCsharpener** [comment]
found a workaround for this
the app installer does add an entry in the registry here: 
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\18ddfc16-e384-5f72-a0ed-ffefbe17581a`
![REG_SZ](https://user-images.githubusercontent.com/26190934/28459466-dec111a8-6e0d-11e7-9737-9882114df5ed.png)

With a group policy I updated this key to the path above and that's the path the app will now use to install by default. I'm basically pretending that it's already installed there. 

Of short or long the old %programfiles(x86)% folder will disappear anyway. It's just a matter of time and therefore not the best default.

**Comment by akashnimare** [comment]
I was playing around with the installation path. This is what I have observed on Windows 8, 64-bit machine -
* The default installation path for v1.3.0-beta is `C:\Program Files\` not `C:\Program Files\x86`.
* If you choose a different installation directory, for an example - `C:\Program Files (x86)\` and have already installed the older version in `C:\Program Files\`, then it will be automatically deleted i.e. `C:\Program Files\Zulip` .
* In any case, you won't have two copies of the app at the same time.

**Comment by penCsharpener** [comment]
hm, I had a few PCs now where Zulip 1.2.0 wasn't registered. At least it seemed like it in Settings > apps on Windows10. It turned out that those PCs had two versions installed. An older one and 1.2.0
I had to uninstall both of them first and then the (x86) was back again. 
But you are right; when I say I had to uninstall both it did uninstall both but one entry remained in Control Panel > Programs and features.

**Comment by akashnimare** [comment]
I'll check this behavior on Win10 also.

**Comment by akashnimare** [comment]
@vbNETonIce should we close this issue?

**Comment by penCsharpener** [comment]
yes, go for it.
