### ISSUE TITLE
Hide/Toggle left sidebar

### ISSUE THREAD

**Issue by catxeger** [zulip/zulip-desktop#222]
(recreated in the correct project, per:  https://github.com/zulip/zulip/issues/5821)

Adding the left-side configuration bar results in the electron 1.2.0 client being exceedingly wide -- and the width can't be adjusted without hiding the user list.

Is it possible to make the width of the user list adjustable (streams also would be nice!), so it's possible to reduce the overall width of the client?

Somewhat related, it would also be a plus to be able to move or hide the left-side configuration bar -- it's very distracting, particularly when you've only got one server configured, and while it's nice to be able to configure the three options, it's confusing to have two (different) configuration sets.

**Comment by timabbott** [comment]
I think probably the thing we should do here in the electron app is make it possible to hide the organization switcher sidebar when you only have one organization.

**Comment by akashnimare** [comment]
> make it possible to hide the organization switcher sidebar when you only have one organization.

I'm positive on this.

**Comment by zhongyi-tong** [comment]
Ok Will do. Maybe a floating collapse button will be a good idea.
Akash Nimare <notifications@github.com>于2017年7月19日 周三上午1:33写道：
