### ISSUE TITLE
OSX and Windows pre built installers

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [zulip/zulip-desktop#24]
Hi Everyone,

Can someone share their build of the osx and windows client? I'm currently using the deb package from the PPA Tim provided, which is great for Linux. Maybe we can share the os x and windows builds to make things a little easier?

**Comment by lfranchi** [comment]
@phillip-white-sociomantic What are you looking for exactly? Are the packages on https://zulip.org/clients.html not what you want?

**Comment by phillip-white-sociomantic** [comment]
@lfranchi Thanks for the download links. This is v0.51 the ones i was looking for. I am running v1.3.7 of Zulip, and the apps page gives me a download link of https://zulip.com/dist/apps/sso/mac/Zulip-latest.dmg, which is only v0.4. The same for the windows version, i get a link https://zulip.com/dist/apps/sso/win/zulip-latest.exe, which is v0.4.4.

I think we need to update the apps page on the server to reference the link you gave me.

**Comment by lfranchi** [comment]
Ah, i believe you are hitting https://github.com/zulip/zulip/pull/261 which has recently been merged but I don't think is in 1.3.7. Closing this, thanks!
