### ISSUE TITLE
Settings gear icon in left sidebar appears when you enter the settings page.

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#243]
On Linux, I encountered this issue, where the gear ended up being added like a server near the top:

![image](https://user-images.githubusercontent.com/2746074/28846401-21f3ae58-76c0-11e7-9008-2a684a1c8ad3.png)

Reproducer:
* Click on the settings gear.  It should highlight the icon at the bottom, not add a duplicate that's highlighted.

**Comment by timabbott** [comment]
I also managed to get this emoji via the "About" item in the taskbar menu.

![image](https://user-images.githubusercontent.com/2746074/28846751-743a5bb6-76c1-11e7-9b96-1a69eb5a766e.png)

**Comment by timabbott** [comment]
I guess for "About", I think moving it to be a tab under "Settings" would be a good solution for making it more discoverable (and having it not need a left-sidebar switcher menu item).

**Comment by zhongyi-tong** [comment]
1. The gear in your screenshot is a tab for the corresponding webview. And the gear at the bottom is an action button to open settings. There are three types of functional tabs that will show on the sidebar: Settings, About and Network Diagnose. I think it's okay to keep it for simplicity. If removed, users might be confused how to close a Settings or a Network Diagnose.
![image](https://user-images.githubusercontent.com/7262715/28855853-10ef39a2-7705-11e7-84d6-329b966e7dd7.png)

2. It's a good idea to move About as a section of Settings. We can await the design suggestions in #244 and move it there.

**Comment by timabbott** [comment]
Hmm, interesting.  I feel like the current UI does feel a bit weird, but given that context, I'm less sure what the right answer is.

**Comment by zhongyi-tong** [comment]
For reference, Slack uses a pop up modal for these pages instead of a tab.
![1](https://user-images.githubusercontent.com/7262715/28856774-7a3c6a38-770a-11e7-838f-70140d663d5e.gif)

**Comment by timabbott** [comment]
Is Slack's popup modal a new window, or a modal within the window?  I think if it's a modal within the window, that'd be a good approach for the "add server" UI in the Zulip app, and maybe also for settings in general.  

For network errors, I think that actually belongs in the window for a given Zulip server, not in the overall error position.  Because you might be able to reach one server but not others if e.g. one of the servers is on a corporate VPN.

**Comment by zhongyi-tong** [comment]
Slack's popup is a modal within the window.

I think it's a good idea to implement settings in an app-wise modal, instead of tab-wise (to distinguish from its own settings from Zulip web). It's doable but needs some big changes in the code.

**Comment by timabbott** [comment]
Yeah, probably not something for this release :)

**Comment by abhigyank** [comment]
This has been fixed in #422.
