### ISSUE TITLE
Do another pass of revising the "About" page for the desktop app.

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#244]
Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/2746074/28846600-e81af384-76c0-11e7-9c24-95c7ef1076f7.png)

@rishig @brockwhittaker we should talk about what should go on this page and make a design.  I think probably 3 segments make sense:
* About Zulip -- probably just a link to zulipchat.com and/or zulipchat.com/about
* About the app -- probably just a nice paragraph explaining this app is open source software under the Apache 2 license, with a GitHub link
* How to get help and report bugs.  Which may belong on another more visible element.

I think going for clean and mostly linking to other resources is a good way to keep effort low.

**Comment by akashnimare** [comment]
@rishig can you please give me the content so that I can just copy paste there 😄

**Comment by rishig** [comment]
What do other apps do here? It's possible About pages have fallen out of favor; I can't find spotify's in their desktop app, and chrome's is buried two layers deep and just looks like
![image](https://user-images.githubusercontent.com/890911/33002059-9fc6a22a-cd66-11e7-8705-c94a97c680d4.png)

**Comment by timabbott** [comment]
I would consider looking at apps that are more similar in purpose like Nylas or Slack.

**Comment by priyank-p** [comment]
@zulipbot claim.

**Comment by akashnimare** [comment]
Added in #346.
