### ISSUE TITLE
No easy way to select a server after hidding the sidebar

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#245]
If you hide the server switch sidebar, on the settings page, there's no obvious way to get back to seeing your single Zulip server's UI.  It turns out you can do it with `ctrl-1`, but that's really not obvious.

Some ideas for fixing:
* The "Servers" section of the settings page should let you jump to that server, maybe be clicking on the icon or something.
* We should list the servers you have setup, with hotkeys in a "servers" menu next to the file menu?
* We could list the servers in the taskbar menu.

Doing something here is a priority, since this is basically the first  thing that anyone is going to try to do after toggling the setting to hide the sidebar.

**Comment by zhongyi-tong** [comment]
Click server name to show webview. Done in #262.

Will add servers to the view menu in the next step. Like this:
![](https://chat.zulip.org/user_uploads/2/d1/-xxW104p--zkPBiANo7pVgCg/pasted_image.png)

**Comment by akashnimare** [comment]
@geeeeeeeeek in `Window` menu :)

**Comment by zhongyi-tong** [comment]
![image](https://user-images.githubusercontent.com/7262715/29000456-d77bd7e6-7a30-11e7-9119-b220f31cecbf.png)

@akashnimare The sub menu is done. But seems that `window` submenu is only displayed on macOS. Do we need to do the same on Linux and Windows?

**Comment by akashnimare** [comment]
Yeah, we should add the `window` menu on Linux and Windows as well.

**Comment by akashnimare** [comment]
On windows -

![image](https://user-images.githubusercontent.com/2263909/29003260-1368aa18-7ad1-11e7-9e49-eeb05cc58e37.png)

**Comment by zhongyi-tong** [comment]
Looks great!
