### ISSUE TITLE
Make capitalization in menus consistent

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#246]
Capitalization is inconsistent in the File/Edit/etc. menus; we should probably be consistently using the "Keyboard shortcuts" style of capitalization that we use throughout the app.  So e.g. "Hard Reload" should become "Hard reload"

**Comment by zhongyi-tong** [comment]
Since most of the apps (including system apps) use upper-case initial letters on macOS. We should use that style as well. Fixed in #254.

**Comment by kanishk98** [comment]
This'll need to be reopened after the discussion [here](https://chat.zulip.org/#narrow/stream/16-desktop/topic/Zulip.20URL/near/731843).

**Comment by kanishk98** [comment]
@zulipbot claim

**Comment by kanishk98** [comment]
@akashnimare I think we can close this issue now. :)
