### ISSUE TITLE
Some menu items on Linux are weird or don't work

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#247]
Specifically at least these are broken:
* Keyboard shortcuts / ctrl-K (neither hotkey nor menu does anything)
* "Clear cache" does this ugly thing: 

![image](https://user-images.githubusercontent.com/2746074/28846867-e9454d12-76c1-11e7-82b1-dfbb1a634410.png) 
does it so something useful as well or is it just weird?
* "Full screen" has no easy way to get out if you went there by clicking the menu item without noting the hotkey, since the menu gets hidden; do we want to have display a little notice like Chrome does that hitting "F11" will let you exit when you toggle it?

Should we just hide these menu items while they're not fully implemented?

**Comment by timabbott** [comment]
(And then open follow-up issues at lower priority for re-adding these elements?)

**Comment by akashnimare** [comment]
> Keyboard shortcuts / ctrl-K (neither hotkey nor menu does anything)

It does work and opens keyboard shortcuts but it's pretty slow (on Linux). On macOs it's pretty smooth.

> "Clear cache" does this ugly thing.

It clears the session’s HTTP cache and temp files. Not so useful as of now. 

I'm thinking to move it to settings page and add few more options in that function like deleting app's settings/configuration etc.

**Comment by timabbott** [comment]
Oh, I see what's going on.  The hotkey is `Ctrl-k`, not `Ctrl-K` (aka it needs to be lower case), and I was typing `Ctrl-Shift-K`.  I guess that's probably user error, though we could think about spelling it `Ctrl-k`.

Moving "Clear cache" to settings probably makes sense.

**Comment by akashnimare** [comment]
I have added a popup which will highlight the hotkeys on full screen. 
- macOS

![image](https://user-images.githubusercontent.com/2263909/28889522-e36d256a-77e1-11e7-805e-46cab3c2070b.png)

**Comment by akashnimare** [comment]
Electron does not allow setting menu item in lower case. So if we set `CTRL+k`, it will show `CTRL+K`. Btw `Shift` is explicitly mentioned if it's there in shortcut.

**Comment by akashnimare** [comment]
Closing and merging to #192. `Clear cache` will be added in setting page.
