### ISSUE TITLE
Update realm icon and name from server configuration on app startup

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#248]
I just tested changing the icon for an organization and then restarting the desktop app, and it still has the original icon from when I connected.  We should make the app check with the servers on startup (and maybe also every 24hr or something?) for `/server_settings`, and adjust the icon and realm name accordingly.

(We still want the caching that we have to have a good experience when opening the app while offline)

That way, an organization administrator can just change the icon once and all their users will get the new version.

**Comment by zhongyi-tong** [comment]
Working on it.

**Comment by zhongyi-tong** [comment]
Fixed via #273.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/1a31d2e43188b38e449b4fe62fbb9cd0e932ba3c.
