### ISSUE TITLE
ctrl-C on zulip-electron-launcher doesn't close the app on Linux

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#253]
When developing, my debug cycle involves frequently rerunning `zulip-electron-launcher`, using ctrl-C to stop it, and then starting it again.  Right now, on Linux, it doesn't actually stop immediately.

It seems worth making it the case that ctrl-C will kill the app so that restarts aren't annoying.

**Comment by akashnimare** [comment]
@timabbott can you check if https://github.com/zulip/zulip-electron/commit/f5e15e3c850b05a34238cac75c308d89f6c8a9ad fixes this issue?

**Comment by timabbott** [comment]
Confirmed fixed, yay!
