### ISSUE TITLE
Improve "+" button to add a new organization

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#264]
When you click the "+" button to add a new organization, it takes you to the right page in settings, but it should also automatically show the "Add server" input and have the focus be in the text box.

(Similarly, the "Add server" button should also put the focus in the input box after you click it).

Tagging this as a priority since some users who were trying out Zulip today seemed fairly annoyed by it.  I think it's not worth blocking our release on it, but if we find some time, definitely worth fixing, since it should be easy to resolve.

**Comment by akashnimare** [comment]
@timabbott pushed a fix in https://github.com/zulip/zulip-electron/commit/caf454590214741455ac535636d8550b15ad79bd. Anything else we should add/change in this?

**Comment by timabbott** [comment]
This is better, but:
(1) The loading screen animation for opening the settings page is unnecessary and weird.  @geeeeeeeeek is this a regression in your recent work to avoid the partial-page load.
(2) It's weird that we display the "Add server" button option when the dialog to add a server is visible.
(3) It's a little weird that we show a Zulip logo in the icon spot next to the UI for adding a new Zulip server; I feel like that's confusing, in that it makes it look more similar to existing servers than it should.

**Comment by zhongyi-tong** [comment]
Fixed in #270.
