### ISSUE TITLE
Use of ES6 Destructuring in index.js

### ISSUE THREAD

**Issue by anshumanv** [zulip/zulip-desktop#271]
Can we possibly use ES6 (ES2015) destructuring in [index.js](https://github.com/zulip/zulip-electron/blob/master/app/main/index.js) for : 

>const {app} = require('electron');
const ipc = require('electron').ipcMain;

which will prevent requiring electron multiple times as we have already done once at the start, thoughts on this suggestion ?

**Comment by zhongyi-tong** [comment]
Good idea. We should do so.

**Comment by anshumanv** [comment]
Thanks for the feedback, @geeeeeeeeek should i send a PR ?

**Comment by akashnimare** [comment]
@Anshuman-Verma yeah, go ahead!

**Comment by anshumanv** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
Command is `@zulipbot claim`  :)

**Comment by anshumanv** [comment]
Thanks for the guide @synicalsyntax , getting accustomed with zulip community 😄
