### ISSUE TITLE
Add a post install script to add the apt repo in debian installer

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#283]
We need to write a post install script to install the apt repo and the signing keys into user's system when installing the Debian package.
 Example - https://github.com/Microsoft/vscode/blob/bfc4e3d780ddbcf8802d9ddc61e3b440af3cae5b/resources/linux/debian/postinst.template#L20

**Comment by akashnimare** [comment]
@SimplyAhmazing template - https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/templates/linux/after-install.tpl

https://www.electron.build/configuration/deb#DebOptions-afterInstall

https://github.com/electron-userland/electron-builder/issues/2050

**Comment by priyank-p** [comment]
@zulipbot claim.
