### ISSUE TITLE
enhancement: add shortcut to reset app settings

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#286]
The main point of this request is to be able to reset the window state if the app is invisible on a virtual or multi screen setup. 

The shortcut would reset x and y both to 0 and then reset the desktop app. 

On Windows the shortcut could be used when the app is visible in the task bar but not on the screen.

**Comment by akashnimare** [comment]
That make sense.

**Comment by penCsharpener** [comment]
can be a complicated short cut as it's really for emergency. Idea came to me when I see your reset data PR

**Comment by akashnimare** [comment]
@vbNETonIce please cross check it.

**Comment by penCsharpener** [comment]
thanks for adding it so quickly. But there isn't yet a keyboard shortcut to this reset. If you can't see the app window only a keyboard shortcut will help. When clicking the Reset Settings Option though I saw that everything was reloading but the window position stayed the same. What about deleting window-state.json?

**Comment by akashnimare** [comment]
> What about deleting window-state.json?

This does delete the `window-state.json` and reloads the app.

> But there isn't yet a keyboard shortcut to this reset.

What shortcut should we add?

**Comment by penCsharpener** [comment]
> This does delete the window-state.json and reloads the app.

odd, I had the app opened on the very left screen that has -x coordinates... It should have jumped to the centre screen.

> What shortcut should we add?

I don't have a preference here. Can we something complicated because most people won't be needing it. You know best which ones you are using / planning on using. Do something with `Ctrl + Alt` maybe.

**Comment by akashnimare** [comment]
Made some changes. Instead of reloading, it `quit + restart` the app now. It does work on macOs.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/288b1cb3f20fcd433bd3d1f4f689347e13773742. @vbNETonIce thanks for the suggestions  👏
