### ISSUE TITLE
Desktop app tray icon does not show unread msg count anymore

### ISSUE THREAD

**Issue by mryakan** [zulip/zulip-desktop#289]
I was using 0.5 version of the windows desktop app mainly because it showed the unread message count in the taskbar icon. Now it does not show that anymore with the latest version (1.4) which makes the desktop app a bit less useful.
---
Please include: 
- `Operating System`: Windows 7
- `Clear steps to reproduce the issue`: Just install the latest 1.4 version of the app
- `Relevant error messages and/or screenshots`: N/A

**Comment by penCsharpener** [comment]
Hi Mr Yakan, 
using the electron app since 0.5.x days I can say that the current electron app is way better than the old legacy app. Even the taskbar notifications look better now. 
Your problem must be something related to Windows 7. It works very well on Win10.

**Comment by akashnimare** [comment]
@mryakan taskbar icon works great on Windows 8/10. I'll check it on Windows 7 as well.

**Comment by akashnimare** [comment]
@mryakan it works on Windows 7 (64-bit) - 

![taskbar_icon](https://user-images.githubusercontent.com/2263909/30180411-6ba0b6ce-942d-11e7-91ea-ccb2e7eddb3c.PNG)

* Please download - [Zulip-Web-Setup-1.4.0](https://github.com/zulip/zulip-electron/releases/download/v1.4.0/Zulip-Web-Setup-1.4.0.exe)
* Make sure the setting option for badges is enable -

![capture](https://user-images.githubusercontent.com/2263909/30180595-0b0b5f3e-942e-11e7-8a8f-fe11a268d704.PNG)

**Comment by mryakan** [comment]
That works indeed, but not what I reported. I am talking about the taskbar icon below on the right
![image](https://user-images.githubusercontent.com/22402472/30186665-7f005032-93f4-11e7-91c3-f4464c8cdbd8.png)

It used to show the same info, (well maxed out at 99, but still better than nothing).

**Comment by akashnimare** [comment]
Ohh, that is tray icon. We stopped that feature since taskbar icon do the same job (also, it doesn't look nice).

**Comment by mryakan** [comment]
Thanks for the response. It was nice since when you do not have taskbar on auto-hide, you can see if anything is pending even if the app is buried under other windows. Other messaging apps do similar things with the icon changing shape (e.g. addition different color dot if there are unread msgs vs unread mentions). I find that very useful and it would be great if that could be added to the desktop app.

**Comment by akashnimare** [comment]
@mryakan since you find it useful, I have re-added that feature. It'll be pushed in next release.

**Comment by mryakan** [comment]
Thanks, much appreciated. That's pretty agile :-).
