### ISSUE TITLE
Option to minimize to tray

### ISSUE THREAD

**Issue by mryakan** [zulip/zulip-desktop#291]
A useful option that is missing from the windows desktop app is ability to minimize to the tray. This saves precious space in the taskbar and is supported by many messaging apps.

---
Please include: 
- `Operating System`: Windows 7
- `Clear steps to reproduce the issue`: N/A
- `Relevant error messages and/or screenshots`: N/A

**Comment by akashnimare** [comment]
@mryakan you can hide the tray icon using `view >Toggle Tray Icon`-

![image](https://user-images.githubusercontent.com/2263909/30207936-f88efbb4-94ae-11e7-8e8b-0b0f54ce72a7.png)

**Show app icon in system tray**

![image](https://user-images.githubusercontent.com/2263909/30208257-44740168-94b0-11e7-9cfc-6b5b672cb0c0.png)

**Comment by mryakan** [comment]
Never mind, my mistake. I just realized you have to close the app not minimize it to hide it from the taskbar.
Thank you.
