### ISSUE TITLE
Emoji picker not showing correctly

### ISSUE THREAD

**Issue by YJDave** [zulip/zulip-desktop#303]
I am using linux mint and when the screen of zulip desktop application is half of desktop and we select emoji picker, it's not showing correctly. 
![emojierror](https://user-images.githubusercontent.com/25907420/30786218-418ac21a-a190-11e7-9b4d-7930768ccc62.gif)

**Comment by HarshitOnGitHub** [comment]
Thanks for the bug report @YJDave but this is something not related to electron-app. There is already an open issue about this in [zulip/zulip](https://github.com/zulip/zulip) repository: https://github.com/zulip/zulip/issues/6291
So you can safely close this. :)

**Comment by YJDave** [comment]
@HarshitOnGitHub Just so you know, This is demo of zulip desktop client application (not mobile application). So if it's included in #6291 then, let me know, I will close it. :)

**Comment by HarshitOnGitHub** [comment]
@YJDave Yeah this is covered in [zulip/zulip #6291](https://github.com/zulip/zulip/issues/6291). [zulip/zulip #6291](https://github.com/zulip/zulip/issues/6291) is concerned with the webapp which is what used by our electron-app as well. "mobile screen" in [zulip/zulip #6291](https://github.com/zulip/zulip/issues/6291) actually refers to small screens not mobile-apps which are native applications.
