### ISSUE TITLE
Adding a new organization does not properly use the organization's icon

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#308]
I just tested this in `master`, and found 2 bugs with the "new organization" flow:
* When adding a second organization, after you type in the URL and hit enter, we select the first organization, not the new organization, which is pretty confusing (since you don't end up seeing the login page).
* We don't seem to fetch save the organization's icon from /server_settings, either right after the server name is entered, or when we reload the app.

We should be fetching the organization icon from /server_settings.

@akashnimare I recommend using the zulip.sagemath.org and chat.fhir.org public servers (which both have organization icons) for testing this with more than 1 organization.

**Comment by akashnimare** [comment]
> When adding a second organization, after you type in the URL and hit enter, we select the first organization, not the new organization, which is pretty confusing (since you don't end up seeing the login page).

It's an old issue, https://github.com/zulip/zulip-electron/pull/238#issuecomment-319778181. We need to handle this event properly.

> We don't seem to fetch save the organization's icon from /server_settings, either right after the server name is entered, or when we reload the app.

This is how the current model work - 
* When user enters a Zulip server, we fetch server details (server name, icon etc) from the `server_settings` API (if supported), see [this](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/domain-util.js#L162). 
* When user first start the app/reloads etc, we again check for the server_icon and if it's being changed then we replace the old icon from the new fetched icon. (Implemented [here](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/main.js#L77) and [here](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/domain-util.js#L206)) 
* In case if user is on Zulip < 1.6 or something fails we use the default Zulip icon.

**Comment by timabbott** [comment]
> In case if user is on Zulip < 1.6 or something fails we use the default Zulip icon.

How are we doing this check?  I've tested with some servers running master that have logos set, and it seems to use the default Zulip icon with some of them.  Sent you the name of a non-public server where I saw this problem.

**Comment by akashnimare** [comment]
> When adding a second organization, after you type in the URL and hit enter, we select the first organization, not the new organization, which is pretty confusing (since you don't end up seeing the login page).

Fixed in master. Please cross check.

**Comment by timabbott** [comment]
Fix confirmed.
