### ISSUE TITLE
Add option to start the app in the background.

### ISSUE THREAD

**Issue by rishig** [zulip/zulip-desktop#314]
This is useful e.g. if you mainly expect to interact with Zulip when you get desktop notifications.

**Comment by akashnimare** [comment]
Yeah, I was planning to add this option.

**Comment by akashnimare** [comment]
Progress is going on in [hidden-on-startup](https://github.com/zulip/zulip-electron/tree/hidden-on-startup) branch.

**Comment by akashnimare** [comment]
@rishig added in master.
