### ISSUE TITLE
"Not a valid Zulip server"

### ISSUE THREAD

**Issue by epaul13** [zulip/zulip-desktop#316]
I get "Not a valid Zulip server" when I try to set my zulip server.

I use https://zulip.intranet.mycompany URL, which of course work in my browser. My server has certificates I've generated with my own CA. I've installed those CA certificate in my OS certificates. Could you give me directions to get more precise logs to try to address this problem ?

    Eric.
					-
					Zulip 1.5.0
					Electron 1.6.14
					linux x64 3.13.0-132-generic

**Comment by epaul13** [comment]
Debugging a bit:

"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"

"Error: unable to get local issuer certificate
at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:603:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)"

If I "patch" the code manually I can start Zulip. Do you know where I can put or configure my ca certs to get Zulip work ? A cleaner message would be nice.

Anyway I'm testing Zulip, it's great !

    Eric.

**Comment by akashnimare** [comment]
> If I "patch" the code manually I can start Zulip?

Hey @epaul13,  what do you mean by this?

**Comment by epaul13** [comment]
@akashnimare :

Well, I used dev tools to edit `app.asar/renderer/js/utils/domain-utils.js`, and bypass the check that fails, ie replace line 123 by `} else if (1 && certsError.indexOf(error.toString()) >= 0) {`. Then, I get the "Do you trust certificate" dialog and zulip work. 

Eric.

**Comment by akashnimare** [comment]
@epaul13 pushed a fix. This should work now.

**Comment by epaul13** [comment]
I downloaded the current git and start the dev version. Now when I set my server, I correctly get the "Do you trust certificate" dialog box. It works, thank you.

By the way do you know how to configure zulip with my CA certificate to avoid this dialog box ? On an intranet it's common to have a certificate signed by own CA. I tried to set the CA certificate in th OS (ubuntu) to no avail.

Anyway, thank you for the patch. 

Eric.

**Comment by timabbott** [comment]
@epaul13 I think probably we should move that to a new issue.  I'd like us to have well-documented instructions for doing that, but it's sorta its own project that will probably separate require work for Mac/Linux/Windows.

**Comment by akashnimare** [comment]
> By the way do you know how to configure zulip with my CA certificate to avoid this dialog box ?

@epaul13 this is #126. Currently, we don't validate custom/own signed certs in desktop app.

**Comment by epaul13** [comment]
Ok. Thanks again.

**Comment by akashnimare** [comment]
This is added in https://github.com/zulip/zulip-electron/commit/0a893c97c720acf76e4247755b4c26f27a1f453e.
