### ISSUE TITLE
dark GUI theme

### ISSUE THREAD

**Issue by Be-ing** [zulip/zulip-desktop#319]
It would be nice if there was an option for a dark GUI so I don't have to stare at so much white light emanating from my screen. @synicalsyntax has made some [hacks using Stylish](https://chat.zulip.org/#narrow/stream/new.20members/subject/dark.20theme.3F/near/299379) in browser, but AFAIK that's not possible in the Electron app.

I don't think a full featured theme system with user defined themes is necessary. To the contrary, that's an unnecessary maintenance burden. I propose following how Signal implements this with just one light and one dark theme shipped with the application.

**Comment by timabbott** [comment]
@Be-ing thanks for the feedback!  I think we should move this issue to the zulip/zulip project, since it makes sense to make them in the webapp code shared with the desktop app, not in the desktop app itself.

**Comment by Be-ing** [comment]
I was unclear about the relationships between the different code repositories, but yeah that makes sense @timabbott. I'm closing this in favor of https://github.com/zulip/zulip/issues/267

**Comment by akashnimare** [comment]
We can easily implement this in electron app.

**Comment by timabbott** [comment]
@akashnimare I'm sure we can, but I'd rather implement it in the webapp, since then it'll be available to users on web as well.

**Comment by dxps** [comment]
Any status about it, please?
I see indeed that website has a dark mode option, and the desktop client has a "Add custom CSS" option, but I couldn't find (at least not yet) any official CSS about it.

Update: I just noticed that enabling the dark mode on the website made also the Zulip Desktop (v4.0.3 at the time of this writing) going dark. Cool enough! 👍
