### ISSUE TITLE
Logo does not show up in the sidebar

### ISSUE THREAD

**Issue by waozixyz** [zulip/zulip-desktop#320]
Operating System: Manjaro

Steps to reproduce:
download the latest appimage, login to an organization with a logo, the sidebar logo does not update and still displays the zulip logo

![screen](https://user-images.githubusercontent.com/31371807/31691843-c2b96f12-b397-11e7-8474-63859435077d.jpg)

**Comment by akashnimare** [comment]
@spaceywolfi can you please tell me what org server you're trying?

**Comment by waozixyz** [comment]
im using https://ascadia.zulipchat.com

**Comment by akashnimare** [comment]
Hmm, I can see your server logo in left sidebar on macOS - 

![image](https://user-images.githubusercontent.com/2263909/31692557-d8a3e634-b3b7-11e7-9b87-7cf03fc321dd.png)

Can you delete and re-add your server and see if it works.

**Comment by timabbott** [comment]
@spaceywolfi what version of the app are you using?  This was broken in v1.4.0 and fixed in v1.5.0, I think.

**Comment by waozixyz** [comment]
@timabbott I think you must be right. I am using Zulip-1.4.0-x86_64.AppImage since that is the latest appimage i was able to download from the [zulipchat.com](https://zulipchat.com/) website

**Comment by timabbott** [comment]
Ahh, that would do it; @akashnimare I think bumping the hardcoded version on zulipchat.com is missing from our "desktop release" checklist.

**Comment by akashnimare** [comment]
I do remember. I'm working on a solution which will automatically fetch the current latest release from GitHub; that way we won't need to update the version manually on` /apps` page every time.
Demo - http://akashnimare.in/electron/

**Comment by akashnimare** [comment]
@spaceywolfi you can download the latest release from GitHub release page - 
https://github.com/zulip/zulip-electron/releases/latest
https://github.com/zulip/zulip-electron/releases/download/v1.5.0/Zulip-1.5.0-x86_64.AppImage

**Comment by timabbott** [comment]
(I updated the link from zulipchat.com)

@akashnimare does the fact he was still on 1.4.0 suggest that auto-update isn't working on Linux?

**Comment by akashnimare** [comment]
As of now, we don't support auto-updates for AppImage.

**Comment by timabbott** [comment]
OK, cool, let's make sure we have an open issue to track that.

**Comment by akashnimare** [comment]
> I do remember. I'm working on a solution which will automatically fetch the current latest release from GitHub; that way we won't need to update the version manually on/apps page every time.
Demo - http://akashnimare.in/electron/

@timabbott I have tried few solutions which basically fetches the latest release of our app from GitHub api but I think that will unnecessarily increase one more http request (which will make /apps page slow) so it's better to update the latest version manually 😅
