### ISSUE TITLE
Switching between servers with window menu and keyboard

### ISSUE THREAD

**Issue by PaulMorris** [zulip/zulip-desktop#329]
I had two zulip servers set up in the app and at first I could switch between them as expected.  Then, after a few days of use, the items in the window menu to switch between them stopped working, and also the ctrl+1 and ctrl+2 keyboard commands.  Switching between them by clicking the icons in the sidebar still worked (although I had the sidebar hidden before I encountered the problem).  Restarting the app did not restore the expected behavior.  I then removed one of the servers, restarted the app, and added the server back in again, and that restored the expected behavior.

Zulip 1.5.0
Electron 1.6.14
linux x64 4.13.0-16-generic (Ubuntu 17.10, with GNOME)

**Comment by akashnimare** [comment]
@PaulMorris I think this is related to #317. We have pushed a fix in new beta release - [1.6.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.6.0-beta). Please update your app (via selecting `Get beta updates` from setting option or download manually through this [link](https://github.com/zulip/zulip-electron/releases/download/v1.6.0-beta/Zulip-Web-Setup-1.6.0-beta.exe)) and see if it fixes this issue.

**Comment by akashnimare** [comment]
@PaulMorris this is fixed. Please upgrade to [1.7.0](https://github.com/zulip/zulip-electron/releases/tag/v1.7.0).

**Comment by PaulMorris** [comment]
Thanks!  I will upgrade.
