### ISSUE TITLE
White Screen after Cert Change

### ISSUE THREAD

**Issue by Fhajad** [zulip/zulip-desktop#33]
I was using a self signed certificate until I got our wildcard certificate ordered. I got it installed and working with the web app, but the desktop all is back to a white screen. It was working fine previously with unsecured mode launched, but now doesn't work in either mode with a trusted cert.

**Comment by Fhajad** [comment]
I also tried uninstalling the Zulip program and re-installed but it still kept the domains somewhere despite deleting the Appdata. Still just a white screen.

I then did a fresh install onto my laptop, also a pure white screen.

**Comment by lfranchi** [comment]
What platform are you on? On mac, you can clear the settings by removing `~/Library/Preferences/*Zulip*`, and on windows it's in the registery under `HKEY_CURRENT_MACHINE\Software\Zulip` i think.

**Comment by Fhajad** [comment]
I'm using Windows, forgot to mention that bit.

Since it also failed on a fresh unit, I doubt that will fix it but I'll try it out when I get to work.

**Comment by grohman2** [comment]
My desktop also has this issue (web version working perfectly). No idea what to do to resolve...

**Comment by Fhajad** [comment]
@grohman2 Is your cert self signed? Currently the desktop app doesn't support self-signed untrusted certs off hand. Issue #6 has more information on that matter. This issue I went from a self-signed to a trusted cert and have a white screen.

**Comment by grohman2** [comment]
@Fhajad Yep, I use self signed cert. Thanks for advice.

**Comment by smewp** [comment]
@Fhajad I had the same issue with white screen using trusted cert, web app was working in Chrome but the desktop apps not working.  

In my case I had misconfigured the SSL by not properly combining the .crt and .ca-bundle into one file and then saving it as /etc/ssl/certs/zulip.combined-chain.crt.  You may want to revisit this to rule it out.

This helped me: https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/789/37/certificate-installation-nginx

**Comment by Fhajad** [comment]
@smewp Yep that was it. Used the proper intermediate cert from Thawte and now good to go! Thank you.
