### ISSUE TITLE
OSX Zulip icon low res

### ISSUE THREAD

**Issue by shidarin** [zulip/zulip-desktop#330]
The zulip icon on OSX laptops with retina (high dpi) screens does not match the system dpi.

<img width="95" alt="screen shot 2017-11-07 at 10 46 27 am" src="https://user-images.githubusercontent.com/5846610/32511548-ee8f64ea-c3a8-11e7-9afc-5b490cbb0114.png">

**Comment by akashnimare** [comment]
Yes, the current icon is of 16x16 px. On retina display it should be 32x32 px.

**Comment by akashnimare** [comment]
@shidarin Added high res tray icons https://github.com/zulip/zulip-electron/commit/9853e9226c0cea78cff96d2cc7751e71b513436a.
