### ISSUE TITLE
Min. Window width dependent on zoom level

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#332]
OS: Windows
Behaviour: the desktop client has a minimum Window width which is 👍 
However I would like it even thinner and that could work if I zoom out Zulip. 
Could the minimum width be reduced if the user zooms out?

PS: I could use Skype almost like a side bar but for Zulip Desktop to work that way it would need to be a little narrower.

**Comment by akashnimare** [comment]
It will make sense to make app thinner if you zoom out. Let me see if it's doable.

**Comment by akashnimare** [comment]
So what I'm planning to do here is that If a user Zooms out then we'll set the `minWidth` to 300 px. @vbNETonIce make sense?

**Comment by akashnimare** [comment]
The other option is to just set the default `minWidth` to 300px.

**Comment by akashnimare** [comment]
Set the `minWidth` to 300px and `minHeight` to 400px.
