### ISSUE TITLE
Zulip desktop on Mac grabs Cmd-R keys 

### ISSUE THREAD

**Issue by twestberg** [zulip/zulip-desktop#339]
On a Macbook Pro running 10.13.1 (17B48), after some time (I don't know when, or why) I noticed that my Cmd-R keys (attempting to reply to email, or refresh a browser window, or jump to a method definition in Sublime Text) are only refreshing the Zulip window, no matter what	window has the focus and menubar. Quitting and restarting Zulip desktop fixed it, at least temporarily. Three other people at my work had the same experience, all blaming their Macs.

(Sorry for not having good reproduction instructions; it took a long time before I even considered restarting Zulip.)
				-
					Zulip 1.5.0
					Electron 1.6.14
					darwin x64 17.2.0

**Comment by timabbott** [comment]
@twestberg try upgrading to the 1.6.0-beta; this should be fixed there.

**Comment by timabbott** [comment]
@akashnimare we may want hurry along releasing 1.6 to production since this bug is pretty annoying -- let's make a plan tomorrow.

**Comment by akashnimare** [comment]
@timabbott yeah, I thought the same. Preparing for the release 🚀

**Comment by akashnimare** [comment]
@twestberg this is fixed. Please upgrade to [1.7.0](https://github.com/zulip/zulip-electron/releases/tag/v1.7.0).
