### ISSUE TITLE
Can't get out of custom emoji image shadowbox

### ISSUE THREAD

**Issue by yesthatguy** [zulip/zulip-desktop#342]
I added a custom emoji and decided I wanted to change the image. I clicked on the image (the bold letters "ev" here):
<img width="1135" alt="screen shot 2017-11-24 at 11 49 27 am" src="https://user-images.githubusercontent.com/10944164/33226236-c0923c94-d14e-11e7-99f8-d949c5cb6b4f.png">

And was presented with the image in a shadowbox:
<img width="1137" alt="screen shot 2017-11-24 at 11 48 39 am" src="https://user-images.githubusercontent.com/10944164/33226239-c6050a80-d14e-11e7-9f2a-c7c62f07fc00.png">

From this shadowbox screen, I can't find any way to get back to my main interface. I tried pressing Escape, Enter, Spacebar, Tab. I tried clicking on the image itself or in the corners of the screen in case there's a hidden close button, and on the server icon in the sidebar. Clicking reload in the sidebar just reloads the same image preview. Clicking Settings in the sidebar lets me view the settings, but when I close them I'm back at the same image preview.

This is with the Mac desktop client, version 1.7.

**Comment by akashnimare** [comment]
You can use `CMD+Left` and `CMD+Right` to go back and forward.

**Comment by timabbott** [comment]
That workaround should work.  @akashnimare I think possibly the bug here is just a webapp issue that we're missing `target=_blank` on the custom emoji links...
