### ISSUE TITLE
The text from the input field disappears if you click in an empty area

### ISSUE THREAD

**Issue by fleytman** [zulip/zulip-desktop#343]
The text from the input field disappears if you click in an empty area.

Steps:

1. Input text on input field
2. Press in an empty area or switch to another channel

**Expected Result:** The text in the input field does **not** disappear. On web version
**Actual result:** Text from the input field **disappears**

The web version works as expected.

![field_bug](https://user-images.githubusercontent.com/1923645/33290620-51e596dc-d3d4-11e7-8d6e-f4e48a1b93fa.gif)

Zulip 1.7.0
Electron 1.6.15
win32 x64 10.0.16299

[field_bug.zip](https://github.com/zulip/zulip-electron/files/1507698/field_bug.zip)

**Comment by timabbott** [comment]
@fleytman thanks for reporting!  I'd be surprised if this were an electron app bug, and not a test procedure difference.

I'd like to make sure you're testing correctly: In Zulip, clicking an area that isn't a link or anything special will close the compose box (and save the content as a draft), while switching narrows should not close the compose box; is that what you're seeing?

**Comment by fleytman** [comment]
@timabbott, 

**Zulip electron windows**
1) I click on empty area and compose box close, and message no in draft
2) I click on empty area and compose box close, and message no in draft

**Zulip firefox (57, 64bit)** 
1)  I click on empty area and compose box no close
2) I click on empty area and compose box no close,
See https://github.com/zulip/zulip-electron/files/1507698/field_bug.zip

**New test**: The behavior of IE and Chrome is similar to an electron

**Comment by fleytman** [comment]
I want save my message if i miss-click

**Comment by timabbott** [comment]
@fleytman have you tried using the `d` hotkey or the "drafts" button at the bottom of the screen?

**Comment by fleytman** [comment]
@timabbott, I did not know about this feature. Thank you very much for your help!

**Comment by fleytman** [comment]
Retest on firefox without extension, is similar to an electron, IE and chrome

**Comment by fleytman** [comment]
But it seems to me that it's a bad idea to nullify the field and not everyone will get into the manual to find out about the feature with drafts.
When I'm writing a long message and I lose it, I'm very angry.

**Comment by timabbott** [comment]
Agreed.  A few thoughts on what we should actually do here:
(1) We should have a little notice that the message was saved as a draft when we save a draft; it'd be a simple code change and make this much more discoverable.
(2) Did you find an issue with clicking links to renarrow closing the compose box?  It shouldn't.

I think both types of issues actually belong on https://github.com/zulip/zulip (this part of the desktop app is just running the code from the webapp).  So maybe we should close this and open a new issue there for at least (1) and maybe also (2)?

**Comment by fleytman** [comment]
>So maybe we should close this and open a new issue

I agree

**Comment by timabbott** [comment]
OK, I'll take care of that.

**Comment by timabbott** [comment]
See https://github.com/zulip/zulip/issues/7539
