### ISSUE TITLE
zoom in/out doesn't work for both Ctr -/+ keys

### ISSUE THREAD

**Issue by YJDave** [zulip/zulip-desktop#344]
Short keys used for zoom in/out are
Linux/Windows - **CTRL+** for zoom in, **CTRL-** for zoom out

zoom in/out should work for both `-`/`+` keys of keyboard(in case keyboard have two keys for `-`/`+`). 
They have different key code as they are different keys(ex. for `-` 109 and 189), so we have to set event for both key codes.

More discussion about this issue [here](https://chat.zulip.org/#narrow/stream/electron/subject/zoom.20in.2Fout).

**Comment by akashnimare** [comment]
Look at the code for zoom functionality - [here](https://github.com/zulip/zulip-electron/blob/master/app/main/menu.js#L65). Electron doesn't support numpad hotkeys -
https://github.com/electron/electron/issues/3332. Ideally, this should be fixed in electron. Can you submit the same issue there?

**Comment by akashnimare** [comment]
To fix this here, we need to listen for `keydown` event in [preload.js](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/preload.js). I have a macOS keyboard so can't work on this.

**Comment by YJDave** [comment]
Submitted as [electron/electron#11310](https://github.com/electron/electron/issues/11310) in electron.

**Comment by abhigyank** [comment]
For Linux, Zoom in works at **Ctrl**+**Shift**+**+**, instead of traditional **Ctrl**+**+**. Is it intentional or a bug?

**Comment by akashnimare** [comment]
@abhigyank good catch. This is an upstream [bug](https://github.com/electron/electron/issues/6731). Pushed a temporary fix in https://github.com/zulip/zulip-electron/commit/1948ba2cc3b052faa51e02a66f9ecb0865371133. So now `Ctrl+` works as expected but it appears as `Ctrl+=` on Linux/Windows.

**Comment by architadesai** [comment]
So now the shortcuts in Linux/Windows are:
**Ctrl** + **+**/**=**  for **zoom in** 
**Ctrl** + **-**/**_** is for **zoom out** and 
**Ctrl** + **)**/**0** is for **zoom reset**
