### ISSUE TITLE
Unable to add valid Zulip server to desktop client.

### ISSUE THREAD

**Issue by satbalus** [zulip/zulip-desktop#354]
1.  Servers
2. Type https://internalserver name and add 
Actual result: shows error as invalid server even though same url works in browser.
					-
					Zulip 1.7.0
					Electron 1.6.15
					win32 x64 10.0.16299

**Comment by akashnimare** [comment]
@satbalus hey, thanks for reporting this. I'll be needing your help in debugging this. Can you do the following things-
* try to add your internalserver
* Go to `Menu > View > Toggle Devtools for Zulip App` and there you will see a `console` tab; paste the content of that tab here  

![image](https://user-images.githubusercontent.com/2263909/34203811-660d0a5c-e5a2-11e7-9082-2b0436ed2fe6.png)

* Do the same with `Menu > View > Toggle Devtools for Active tab` 
* What do you see when you enter this in browser `https://yourinternalserver/static/audio//zulip.ogg` ?

**Comment by akashnimare** [comment]
@satbalus ^^.

**Comment by timabbott** [comment]
Closing due to no reply from reporter in a month.

@satbalus if you get a chance to provide more information, we'd appreciate it.
