### ISSUE TITLE
Change default org icon

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#359]
I think rather than setting the default icon as Zulip icon, we should set the "initial letter" as the default icon, something like the Slack does -

<img src="https://chat.zulip.org/user_uploads/2/9d/fXiB6z02OaA5n-GKf8luKpCY/pasted_image.png">

This will be applicable to those orgs who don't the `realm_icon`. We can get the "initial letter" from `realm_name` ex. [here](https://zulip.sagemath.org/api/v1/server_settings).

**Comment by abhigyank** [comment]
@cPhost  is this issue closed? or WIP?

**Comment by priyank-p** [comment]
WIP Almost done.

**Comment by timabbott** [comment]
This seems like something we should do on the backend, since the org icons are also used on e.g. mobile.

**Comment by priyank-p** [comment]
If we could assign avatars on the backend by default for realms that did not upload an image that would be great (I thought we already do this don't we) -- but this is also when a request for fetching realm icon fails so this also needs to be implemented in electron side of code.

**Comment by abhigyank** [comment]
@akashnimare This is implemented in Priyank's commit and can be closed.
