### ISSUE TITLE
RPMs to Fedora 23 and Rawhide

### ISSUE THREAD

**Issue by unrealps** [zulip/zulip-desktop#36]
Hi,
   I made a rpm to install the application Zulip Desktop in Fedora 23 and Rawhide. Instructions to use my repository are in https://copr.fedoraproject.org/coprs/unrealps/zulip-desktop/, if someone is interested.

**Comment by excieve** [comment]
Hi @unrealps. Just FYI: I've created a COPR repo too some time ago:
https://groups.google.com/d/topic/zulip-devel/DcIvITJF3co/discussion

I couldn't package Qt4 build though, PR #23 should help with this once merged.

**Comment by unrealps** [comment]
Thank @excieve for the warning. Since you are already working on a rpm for Fedora I will remove my.
