### ISSUE TITLE
Improve gule-dev script

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#368]
Currently, it does not do much. Few things we should add in this -
* Watch for all the JS/CSS/HTML changes in main and renderer process and then auto-reload app on changes
* Watch for linter also, this could be done using [nodemon](https://github.com/remy/nodemon)

**Comment by priyank-p** [comment]
We have task for reloading renderer process but it does not work for me can somebody else confirm?

I can see the popup running `reload:renderer` but no actual reloading.

**Comment by abhigyank** [comment]
Is there any linter currently being used?

Also, I think we can use nodemon for both the features.

**Comment by priyank-p** [comment]
Yep, we currently have xo.
