### ISSUE TITLE
App Crash: Restarted server without restarting the app.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/zulip-desktop#371]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
---
The app slowed down and crashed on me when I was running a dev instance (no local changes). When I restarted the server (without closing the desktop app), it gave me this message (in the screenshot).
- **Clear steps to reproduce the issue**:
This crash happened to me once when I was just looking for bugs. I haven't experienced it again.
The steps I followed when this happened:
1. Start the dev server.
2. Open the server in the desktop app.
3. Send a very large message (say 10000) lines to make the server crash.
4. Restart the server.
The desktop app would not open the server again even on `hard-reload`.
- **Relevant error messages and/or screenshots**:
![d](https://user-images.githubusercontent.com/16427330/34517586-cb6483ea-f0a5-11e7-8767-135b328a39af.png)

**Comment by priyank-p** [comment]
That's the zulip server crashing..., This is zulip issue so you should open issue in zulip/zulip.
Are you using local devlopment server?

**Comment by ViRu-ThE-ViRuS** [comment]
The server did not crash. I just restarted it. The application froze and gave me this error. I could open the server in the brower when this happened. Yes I am using a local dev server.

**Comment by priyank-p** [comment]
@ViRu-ThE-ViRuS hat what zulip does it displays the errors of zulip in a model like this, what we call `blueslip` to fix you probably updated a js file or something. If not update to latest master `git pull upstream master --rebase`. I think if you click the `x` button it should fix it nonetheless.

**Comment by priyank-p** [comment]
And if you can repro this again we need to open an issue on zulip, because you just found a bug 👍

**Comment by ViRu-ThE-ViRuS** [comment]
Thanks for your response. Will open if I can reproduce it. Closing for now. :-).
 Tho I must say that it was updated to latest master and not modified by me.
