### ISSUE TITLE
Add support for 32-bit debian installer

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#379]
Currently, we only support 64-bit deb installer. This could be easily done using electron-builder's `arch` option.

**Comment by priyank-p** [comment]
Yep, we need to do this asap @zulipbot claim.

**Comment by akashnimare** [comment]
I have tried to build 32-bit deb from 64-bit machine using -
`"dist": "electron-builder --ia32 --x64"` but the build failed due to keyboard-layout dependency. Since this requires rebuilding native modules we need to install few Linux packages to build it from 64 machine.

**Comment by akashnimare** [comment]
I don't think we can build the 32-bit installer from a 64-bit machine :/ 
Anyways I have built the 32 bit Debian and AppImage installer using a 32-bit machine and published the same.
