### ISSUE TITLE
Video Chat Button Missing

### ISSUE THREAD

**Issue by stevenfoong** [zulip/zulip-desktop#384]
According to the web site screenshot, there supposed to be a video chat button under the chat box. But my fresh installation, cant find the video chat button.
Not much article in the document mention about this video chat.
Can you help ?
---

- **Operating System**:
  - [x] Windows
  - [x] Linux/Ubutnu
  - [x] macOS
- **Clear steps to reproduce the issue**:
Click on a contact, under the chat box , the video button is missing.
- **Relevant error messages and/or screenshots**:

**Comment by akashnimare** [comment]
@foongws can you attach a screenshot of the chat box here? I can see the video chat button - 

![image](https://user-images.githubusercontent.com/2263909/34984233-4086b438-fad6-11e7-82a2-418bc8249744.png)

**Comment by timabbott** [comment]
The video chat option is relatively new and might not be in the release @foongws is using.

**Comment by stevenfoong** [comment]
![screen shot 2018-01-18 at 4 56 25 pm](https://user-images.githubusercontent.com/16485977/35089035-a953b7d6-fc70-11e7-98e6-703d933e033a.png)

mine look like this

**Comment by stevenfoong** [comment]
@timabbott i am using zulip 1.7.1 on ubuntu

**Comment by akashnimare** [comment]
@foongws do you know which version of Zulip are you using? As Tim said this feature is pushed recently and might not available in your Zulip version. To know the Zulip version you're using - 
https://your-zulip-server/api/v1/server_settings
https://chat.zulip.org/api/v1/server_settings

**Comment by stevenfoong** [comment]
@akashnimare this is the result:

{"zulip_version":"1.7.1","authentication_methods":{"google":false,"dev":false,"password":true,"email":false,"ldap":true,"github":false},"require_email_format_usernames":false,"result":"success","realm_description":"<p>The coolest place in the universe.<\/p>","msg":"","realm_uri":"https:\/\/www.sige.la","realm_name":"Hello Everyone!","realm_icon":"\/user_avatars\/2\/realm\/icon.png?version=2","email_auth_enabled":false}

**Comment by timabbott** [comment]
Looking at http://zulip.readthedocs.io/en/latest/overview/changelog.html, the video chat button hasn't been released yet.  It's available on zulipchat.com, and will be available in the next release (1.8) when that comes out.  @foongws if you'd like, you can upgrade to a version from Git to get it on your server before 1.8 is released.
