### ISSUE TITLE
appId is not defined when app is packaged

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#386]
Looks like there are some path issues when importing the appId from `package.json`. Following helper function fails on packaging - 
```
const {
  build: { appId }
 } = require('../../../../package');
```

**Comment by priyank-p** [comment]
Ah, that because the app.asar is only for `app` directory and `package.json` is not included.

**Comment by akashnimare** [comment]
Yeah, pushing the old way 😄
