### ISSUE TITLE
German Translation for Topic is misspelled

### ISSUE THREAD

**Issue by xAzzzu** [zulip/zulip-desktop#389]
The Button "New Topic" is labeled "Neues Them" in german it should be "Neues Thema".
![new_topic](https://user-images.githubusercontent.com/20838039/35109468-bf05d144-fc76-11e7-8826-788e1c43b3dc.PNG)

**Comment by timabbott** [comment]
@roberthoenig can you take care of fixing this?  It's not exactly a bug in the electron app, but we should probably just fix it regardless.

**Comment by roberthoenig** [comment]
Done. @xAzzzu thanks for reporting this!

**Comment by akashnimare** [comment]
Should be fixed via https://github.com/zulip/zulip/pull/8105.
