### ISSUE TITLE
desktop fail on osx 10.11.1

### ISSUE THREAD

**Issue by lethe3000** [zulip/zulip-desktop#39]
When launched desktop from https://zulip.com/dist/apps/mac/Zulip-latest.dmg 
only blank window appears.
I use Zulip --debug get logs as below:
```
2016-01-06 15:35:37.207 Zulip[31849:7641571] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
```
Here is the blank window
![image](https://cloud.githubusercontent.com/assets/776658/12137463/cb39f6e6-b48b-11e5-9ff5-dffd8489b87b.png)

**Comment by lfranchi** [comment]
Hmm everything looks fine with the app shell launching, but it's not loading the page.

Do you have  a self-hosted Zulip instance? Are you using self-signed SSL certs?

**Comment by lethe3000** [comment]
Yes I'm using self-hosted zulip with self-signed SSL certs, and I've tried to remove caches under ~/Library/Caches/com.zulip.Zulip
But it still shows blank, and No login prompt window shows.

**Comment by lfranchi** [comment]
I think this is issue #6 then. Closing as a duplicate -- check out the long conversation there!
