### ISSUE TITLE
isDev returns true in npm start

### ISSUE THREAD

**Issue by abhigyank** [zulip/zulip-desktop#414]
- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Start the app using `npm start`. All checks for `isDev` returns `true`. 
- **Relevant error messages and/or screenshots**:
`isDev` check, used for checking whether app is running in Development environment, returns `true` even when starting the app through `npm start`. It should return true only in `npm start dev`.

**Comment by akashnimare** [comment]
Whatever script you run, if it's in development mode, `isDev` will return true. Give it a read - https://github.com/sindresorhus/electron-is-dev

**Comment by abhigyank** [comment]
How are we determining if it's in development mode? Shouldn't for `npm start`  `isDev` return 'false'?

**Comment by priyank-p** [comment]
I think you misunderstand what it means when you are running app in development vs production/packaged app.

* The app is not considered development only when its packaged and you open a app.
* Starting manually is considered as development (so anything you do start and app that is not packaged is considered under development.)

**Comment by akashnimare** [comment]
In electron, this is how we decide whether the app is running in dev or prod -
* Development = If app is runnig from a target directory = `electron .` = `npm start`
* Production = if app is running from a packaged state
More details - https://github.com/electron/electron/issues/7714
