### ISSUE TITLE
control-b boldfaces text rather than moves the cursor on macOS

### ISSUE THREAD

**Issue by glyph** [zulip/zulip-desktop#419]
---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubutnu
  - [x] macOS
- **Clear steps to reproduce the issue**:

Type <kbd>Ctrl</kbd><kbd>B</kbd> in the text field.

Expected behavior:

- The cursor moves left one characer.

Actual behavior:

- The cursor is surrounded by `**` characters on either side.

When you hit this key combination on a mac, the correct native text-widget behavior is to move backward one character.  Control-key sequences on a mac have Emacs-like behavior by default in all apps.

The human-interface-guidelines-correct keyboard shortcut which should be captured to bold-face some text is <kbd>⌘</kbd><kbd>B</kbd>, not <kbd>Ctrl</kbd><kbd>B</kbd>.  Cross-platform widgets often consider Ctrl and Cmd to be equivalent, and map them both on macOS, so this might be a default behavior that you need to disable.

If this is intentional behavior, then I would suggest the other keyboard shortcuts (<kbd>Ctrl</kbd><kbd>F</kbd>, <kbd>Ctrl</kbd><kbd>K</kbd>, <kbd>Ctrl</kbd><kbd>Y</kbd>, <kbd>Ctrl</kbd><kbd>A</kbd>, <kbd>Ctrl</kbd><kbd>E</kbd>, et cetera) should also be disabled.  It's better to have an intentionally alien text entry area that is consistent on different platforms than one that violates *some*, but not all, of the native platform's expectations.

**Comment by akashnimare** [comment]
This is the issue with web app, should be fixed there. @glyph opened as https://github.com/zulip/zulip/issues/8430

**Comment by akashnimare** [comment]
@glyph this is fixed in https://github.com/zulip/zulip/commit/9dba134c7af3500731cc9013c1a1cf38c19e8788.
