### ISSUE TITLE
Only show the back button if it needed

### ISSUE THREAD

**Issue by priyank-p** [zulip/zulip-desktop#421]
Right now clicking on the go-back button sometimes does nothing so we can hide the button when not in need you can check of you can go back on an active webview by `webview.canGoBack()`.

This is a followup of #413, @abhigyank can you do this?

**Comment by cPhost** [comment]
@zulipbot label "Priority: Medium", "Type: Enhancement"

**Comment by abhigyank** [comment]
Sure, I can take this up. 
I think showing and hiding the back button, would not look good from design perspective. Rather I feel, we can change the shade of color of the back button to suggest inactiveness. Like how it is handled in browsers like chrome. What do you think?

**Comment by priyank-p** [comment]
@abhigyank i do prefer hiding the button than disabling it since the icon is too big so its not working i rather not have it in my way as a user but feel free to get other opinion on it.

**Comment by abhigyank** [comment]
I get your view. Maybe  open a thread on this in design stream?

**Comment by akashnimare** [comment]
I don' think we need to hide the button, just disabaling the cursor and `0.6` opacity will work.

![image](https://user-images.githubusercontent.com/2263909/36382581-746b229a-15af-11e8-85e3-304bb2767871.png)

**Comment by priyank-p** [comment]
Do we need it up though and not be functional, specially with a new button about to be added and this button being completely being useless most of the time it just adds to clutter for no reason.

**Comment by akashnimare** [comment]
I'm 100% sure that this button will be visible most of the time if a user is using the app. We are planning to add a `hide/show` kind of button to deal with the clutter thing. Something like - 

<img src="https://d2ffutrenqvap3.cloudfront.net/items/281S2Q381l123N3S0w0e/Screen%20Recording%202018-02-13%20at%2002.39%20AM.gif?v=bca79b43" />

But let's try the first approach i.e. show it only if `webview.canGoBack()` and see how it looks.
