### ISSUE TITLE
Add an option to add custom css 

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#432]
We should add an option to let the user choose the custom CSS file from their system and then inject it into the app. This option would be useful for users who don't like the certain design and want to override the default styling.

**Comment by timabbott** [comment]
@akashnimare are there examples of features like this in other electron apps?  I think issues like improving the design of the add_realm page is a lot more important than this.  But if it's easy to do following the design of existing tools, it could be OK to add.

**Comment by akashnimare** [comment]
Yeah, I have seen this feature in a couple of the electron apps, it's an easy feature to implement.

**Comment by akashnimare** [comment]
Added in https://github.com/zulip/zulip-electron/commit/a90dc0c82fed7fb7a10fb54fadaa3aa91e2f8bbb.
