### ISSUE TITLE
Reinstall script does not work in windows

### ISSUE THREAD

**Issue by abhigyank** [zulip/zulip-desktop#440]
---

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
`reinstall` script in `package.json` is `./tools/reinstall-node-modules` and running npm reinstall does not work and throws an error `'.' is not recognized as an internal or external command,
operable program or batch file.` . This is suited for Linux/Mac not for Windows.

**Comment by akashnimare** [comment]
Yeah, this was expected.

**Comment by priyank-p** [comment]
@abhigyan I need more info here:

What were you using (cmd prompt / powershell)?
Window Version?

(Try removing `.` in the `package.json` if this still does not work try adding `.cmd` at the end.)

**Comment by abhigyank** [comment]
Powershell is Major 5, Minor 1, Build 14393.
Windows 10.
Adding `.cmd` made it work though.

**Comment by robgev** [comment]
@zulipbot claim --force

**Comment by robgev** [comment]
@abhigyank @cPhost should I add a node script? Is it a normal solution?
