### ISSUE TITLE
App settings are not working correctly 

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#448]
This is the regression in the master, not sure when this was introduced. 

The settings (Desktop notifications, silent etc) are changing automatically if you change it and then switch back to a server. 

![dnd](https://user-images.githubusercontent.com/2263909/37529660-b316396e-295d-11e8-9874-f16c15d704d5.gif)

Repro steps -
* Go to setting page set `Show desktop Notification` to `ON`
* Switch to added server
* Switch back to the setting page 
* At this time the setting should be `ON` instead it's `OFF`

**Comment by abhigyank** [comment]
[This](https://github.com/zulip/zulip-electron/commit/f409bb0449a9fdbba81e418a256d0a1da14f5cd4) commit intoduced this bug. It worked as expected before this commit.

**Comment by akashnimare** [comment]
Yeah, I have also narrowed down to that commit only, it used to work as expected before this.
