### ISSUE TITLE
Login Screen: Pressing buttons while Zulip tries to connect will fire the events after the loading is finished.

### ISSUE THREAD

**Issue by robgev** [zulip/zulip-desktop#450]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:

On the first step, specify the company name and while the first button says "Connecting" press the "Create Organization" button.

**Comment by abhigyank** [comment]
I am unable to reproduce the issue. "Create a new organisation" button on the add organisation page fires up the link in the browser even while the app is "Connecting" to a new server. 
![](https://user-images.githubusercontent.com/20434085/37621773-fbd0c50e-2be5-11e8-805f-c03c328d4fee.gif)
Can you post a gif reproducing the issue?

**Comment by robgev** [comment]
Yes exactly, but isn't it a bug? Shouldn't the buttons be just disabled when you are trying to connect?

**Comment by akashnimare** [comment]
I don't think anyone would try to click on "Create a new.." button after submitting the server URL 😸  but if you think this could be improved feel free to send a PR which basically disables the click event while the app validates the server.

**Comment by abhigyank** [comment]
I agree with Akash. However I feel "Create a new" should work even while connecting as both are independent events.

**Comment by akashnimare** [comment]
> However I feel "Create a new" should work even while connecting as both are independent events.

Correct.
