### ISSUE TITLE
Tweaks to the "Organizations" settings page

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#456]
* ~~We should have a link to "Add organization", in case users don't see the `+` icon; probably at the bottom is fine.~~ (Decided not to do this)
* ~~It's not great that the hover CSS moves the row (e.g. the "Disconnect" button jumps)~~
* ~~I think we want the "Disconnect" button to be at the far right, so that longer organization URLs don't mess up the table~~:

![image](https://user-images.githubusercontent.com/2746074/37788133-dd1750b8-2dbd-11e8-9d43-e20b9ec21626.png)

Update - I think we could still make that page responsive. 

![image](https://user-images.githubusercontent.com/2263909/37801565-171923ba-2e4d-11e8-8267-09ec92c04e53.png)

**Comment by abhigyank** [comment]
@zulipbot claim

**Comment by abhigyank** [comment]
@timabbott  The hover CSS moving the row has been long there, however I couldn't replicate the button jumping part, the entire row slides to the right. If you want I can remove the transition of the row altogether.
Can you mention the url for which you tried? It will help me in testing the fix.

**Comment by timabbott** [comment]
I tried zuliporg.zulipchat.com, but I think anything long will do it, so you can probably make that state with the inspector.

Yeah, I know the entire row slides to the right; I just think it's a poor interface for a thing with buttons you might be trying to click inside the widget -- even if you're unlikely to miss because the motion is small compared to the button size, users generally have a bad reaction to a button moving when you're trying to interact with it.

**Comment by akashnimare** [comment]
> It's not great that the hover CSS moves the row (e.g. the "Disconnect" button jumps)

I think we should just remove the hover effect for now and probably think for a better animation since it moves the whole row.

**Comment by akashnimare** [comment]
> We should have a link to "Add organization", in case users don't see the + icon; probably at the bottom is fine.

@timabbott I hide that link intentionally since I think the `+` button is pretty visible/big and obvious.
The link is there in the left nav items I just used `display:none` to hide it-

![image](https://user-images.githubusercontent.com/2263909/37796917-6d206afc-2e3e-11e8-9c7c-73e5a80c5a60.png)

IMO we might not need this button but if you want it then we could either add it in the nav item or in the bottom of connected org page.

**Comment by timabbott** [comment]
I guess I was thinking about the new-user situation, but I guess that one doesn't really exist, since presumably we start folks up with the splash screen to add an organization anyway.  So I agree with you; we can ignore that one until we get feedback from a user that they were confused.

**Comment by akashnimare** [comment]
@abhigyank can you remove that 😅

**Comment by abhigyank** [comment]
Done!
