### ISSUE TITLE
Shortcuts menu should also advertise Zulip webapp's built-in hotkeys

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#459]
I think we could just handle this by having a tip-section at the top or bottom of the in-app shortcuts page linking to:

https://zulipchat.com/help/keyboard-shortcuts

And by "tip" I mean something styled nicely lik https://zulipchat.com/help/view-the-markdown-source-of-a-message

**Comment by abhigyank** [comment]
What should be the message in the tooltip?
I was thinking "You can view the webapp built-in hotkeys [here](https://zulipchat.com/help/keyboard-shortcuts)".

**Comment by timabbott** [comment]
Maybe something more like "These hotkeys are in addition to <a>Zulip's web keyboard shortcuts</a>"?

We may want to do a bit of editing after seeing what it looks like implemented, so post a screenshot on the PR.
