### ISSUE TITLE
Enhancement: File Upload Progress Indicator

### ISSUE THREAD

**Issue by stone212** [zulip/zulip-desktop#465]
---
  
On Linux/Ubutnu Electron Client, file upload does not show a progress indicator.

- **Clear steps to reproduce the issue**:

Within a stream, upload a file using the paper clip icon.  You will see a blue bar with blue text "Uploading..." but it gives no progress.

(also you cannot send messages while you are waiting)

**Comment by akashnimare** [comment]
This should go in the webapp. @stone212 can you re-open this issue [here](github.com/zulip/zulip)?

**Comment by stone212** [comment]
@akashnimare  I could but I am not using the webapp.  I am using the electron desktop client and that is where I have this issue.  Also can you re-send the link?  It didn't come through.  Was it the zulip/zulip stream you want the issue posted in?

**Comment by abhigyank** [comment]
@stone212 The desktop app only renders the webapp in the webview and it is actually the webapp that you are indirectly using.
The link would be https://github.com/zulip/zulip/issues
