### ISSUE TITLE
The Desktop App keeps crashing by showing 502 Bad Gateway from nginx

### ISSUE THREAD

**Issue by rvencu** [zulip/zulip-desktop#466]
I am keeping the app open at all times. Usually every morning I find it displaying Cannot connect to the server, Try now... and when trying to connect 502 Bad Gateway is returned.
As the app is basically a web client I went to the server and done tons of restarts until I noticed the desktop app is, somehow, the culprit. That happened when the desktop app was crashed and nothing worked (not reload, not hard reload) and I discovered the main Chrome browser is displaying the same Zulip server interface just fine.
It is enough to close the desktop app and reopen it to fix the issue. But it is also boring to take the entire team every day through it. My people are not computer savvy...

					Zulip 1.9.0
					Electron 1.8.4
					win32 x64 10.0.16299

**Comment by akashnimare** [comment]
> It is enough to close the desktop app and reopen it to fix the issue. But it is also boring to take the entire team every day through it. My people are not computer savvy...

Ahh, that's bad. Would be great if you can provide following info -
* If your server is public can you provide me with the server URL?
* Do you experience the same issue on chrome?
* Can you paste a screenshot of the error (or the app) when that error occurs?

Currently, we don't handle the 502 gateway error which we need to take care of. @timabbott could this error be caused due to bad server configuration or something?

**Comment by rvencu** [comment]
https://chat.dentfix.ro
Yes, at first it happened on Chrome as well. But then I upgraded the RabbitMQ to a recent version and on Chrome it became stable. My Chrome is version 68, I saw the desktop app is built over version 59.
My installation is on Ubuntu Server 16.04 LTS, I heard LTS has some old version of software on repository. If you need I can provide SSH access to the server. I will upload screenshots ASAP the app will appear to crash again.

**Comment by rvencu** [comment]
BTW, I enabled root SSH access so it will be easy to work on the server but I will need a SSH public key to grant access with certificates.

**Comment by akashnimare** [comment]
Thanks, that's helpful. I see the server certificate is properly signed and it's highly unlike that the app is causing the issue. If this error happens again can you reproduce the same in the chrome also (at the same time) so that we can make sure that it's only happening in the app and not in the web app. I don't think I'll need the SSH access but I'll let you know.

**Comment by timabbott** [comment]
It sounds like the original 502 was caused by the server being actually down; the problem here was that somehow the desktop app didn't recover once the server was fixed.

**Comment by rvencu** [comment]
Well, I fixed the server like a week ago. In the meanwhile I even upgraded the desktop app to the most recent version. I can try an uninstall then fresh install of the desktop app. Let me first capture the event on video, then I will try that.

**Comment by rvencu** [comment]
OK, tinkering with developer tools on the app itself I found a lot of 502 messages. I am uploading screenshots here. First is from the App that was online for several hours already (and accumulated 90 of those 502 errors)
![image](https://user-images.githubusercontent.com/287411/38099671-e754ece0-3383-11e8-8c11-189768f29354.png)
The second one if from main Chrome browser that I just opened and kept open for several minutes.
![image](https://user-images.githubusercontent.com/287411/38099917-85c1425c-3384-11e8-8330-496f3d6724d5.png)

What I can see is that there is no difference between browsers, just that the app stays open for long time while the browser is logging in occasionally. I think the main browser will suffer the same issue if left unattended for many hours.

The thing is as soon as it enters that state there is no recovery except closing and opening a new instance of it. I do not understand why.

**Comment by rvencu** [comment]
From that screenshot I can see sometimes the failed requests are retried and they succeed
![image](https://user-images.githubusercontent.com/287411/38100262-95ee9a98-3385-11e8-93cd-3b6c9c907f9c.png)

**Comment by rvencu** [comment]
I had the patience to read all failed url and they end in event_id=n. Thing is every third event number generated 502 error. Like clockwork. If something bigger happens it might jump then after things calm down every third event fails with 502, for hours and hours.

**Comment by timabbott** [comment]
I've never seen anything like this before, but the issue is very likely a networking configuration problem (e.g. a buggy `nginx` or load-balancer configuration that is basically load-balancing between 3 hostnames, only 2 of which actually work).

**Comment by rvencu** [comment]
My setup is nothing special. Just one server for everything, I followed the setup documentation to the letter.
I can find the errors in nginx error log as well
`2018/03/29 20:19:52 [error] 1461#1461: *2702 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522220881%3A9&last_event_id=358 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522220881%3A9&last_event_id=358", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/29 20:20:07 [error] 1460#1460: *2835 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522220881%3A11&last_event_id=92 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522220881%3A11&last_event_id=92", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/29 20:21:52 [error] 1461#1461: *2702 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522220881%3A9&last_event_id=361 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522220881%3A9&last_event_id=361", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/29 20:22:46 [error] 1460#1460: *2835 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522220881%3A11&last_event_id=95 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522220881%3A11&last_event_id=95", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/29 20:24:24 [error] 1461#1461: *2702 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522220881%3A9&last_event_id=364 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522220881%3A9&last_event_id=364", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/29 20:25:16 [error] 1460#1460: *2835 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522220881%3A11&last_event_id=98 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522220881%3A11&last_event_id=98", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"`
Therefore the service on port 9993 has some issues.

**Comment by rvencu** [comment]
I cannot find any special error in server logs related to the moment when the app/browser does become unresponsive. I will try more perhaps in the morning when I will find the app crashed. I will also leave the main browser on as a test.

**Comment by timabbott** [comment]
Weird.  Can you do a `pstree -ap zulip` and post the output?

**Comment by rvencu** [comment]
I searched many logs under zulip folder. None has another clue. I could only find the pika.adapters.blocking_connection errors that led me to upgrade to latest RabbitMQ. The tornado.log shows only status 200 events.
Here is the output of the pstree command:
`nginx,1458                           

nginx,1459                           

nginx,1460                           

nginx,1461                           

python3,1794 /home/zulip/deployments/current/manage.py runtornado 127.0.0.1:9993

python3,1797 /home/zulip/deployments/current/manage.py process_queue --queue_name=feedback_messages

python3,1798 /home/zulip/deployments/current/manage.py deliver_email

python3,1799 /home/zulip/deployments/current/manage.py process_queue --queue_name=user_presence

python3,1800 /home/zulip/deployments/current/manage.py process_queue --queue_name=invites

python3,1801 /home/zulip/deployments/current/manage.py process_queue --queue_name=outgoing_webhooks

python3,1802 /home/zulip/deployments/current/manage.py process_queue --queue_name=signups

python3,1803 /home/zulip/deployments/current/manage.py process_queue --queue_name=embedded_bots

python3,1804 /home/zulip/deployments/current/manage.py process_queue --queue_name=email_mirror

python3,1805 /home/zulip/deployments/current/manage.py process_queue --queue_name=user_activity_interval

python3,1806 /home/zulip/deployments/current/manage.py process_queue --queue_name=missedmessage_emails

python3,1807 /home/zulip/deployments/current/manage.py process_queue --queue_name=missedmessage_email_senders

python3,1808 /home/zulip/deployments/current/manage.py process_queue --queue_name=slow_queries

python3,1809 /home/zulip/deployments/current/manage.py process_queue --queue_name=embed_links

python3,1810 /home/zulip/deployments/current/manage.py process_queue --queue_name=missedmessage_mobile_notifications

python3,1811 /home/zulip/deployments/current/manage.py process_queue --queue_name=digest_emails

python3,1812 /home/zulip/deployments/current/manage.py process_queue --queue_name=user_activity

python3,1813 /home/zulip/deployments/current/manage.py process_queue --queue_name=error_reports

python3,1814 /home/zulip/deployments/current/manage.py process_queue --queue_name=message_sender --worker_num=0

python3,1815 /home/zulip/deployments/current/manage.py process_queue --queue_name=message_sender --worker_num=1

python3,1816 /home/zulip/deployments/current/manage.py process_queue --queue_name=message_sender --worker_num=2

python3,1817 /home/zulip/deployments/current/manage.py process_queue --queue_name=message_sender --worker_num=3

python3,2431 /usr/local/bin/process_fts_updates

uwsgi,1793 --ini /etc/zulip/uwsgi.ini
  |-uwsgi,2474 --ini /etc/zulip/uwsgi.ini
  |-uwsgi,2475 --ini /etc/zulip/uwsgi.ini
  |-uwsgi,2476 --ini /etc/zulip/uwsgi.ini
  |-uwsgi,2477 --ini /etc/zulip/uwsgi.ini
  |-uwsgi,2478 --ini /etc/zulip/uwsgi.ini
  `-uwsgi,2479 --ini /etc/zulip/uwsgi.ini
`

**Comment by timabbott** [comment]
OK, so there's only one Tornado process.  This is quite mysterious.  Are you sure you haven't modified the nginx configuration, put Zulip behind a proxy, or anything like that?

**Comment by rvencu** [comment]
Sure thing no, I only upgraded RabbitMQ. The main browser hit the fan and entered 502 state. I am attaching a short movie about it below
https://screenpresso.com/=DoGWb

**Comment by rvencu** [comment]
These are new lines in  nginx error log
`2018/03/29 22:36:53 [error] 1459#1459: *3433 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /sockjs/info?cb=ju85ie5og3 HTTP/1.1", upstream: "http://[::1]:9993/sockjs/info?cb=ju85ie5og3", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/29 22:36:54 [error] 1461#1461: *3443 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /sockjs/631/61_im6jf/websocket HTTP/1.1", upstream: "http://[::1]:9993/sockjs/631/61_im6jf/websocket", host: "chat.dentfix.ro"`

**Comment by rvencu** [comment]
tornado.log says this around the above error logged time:
`2018-03-29 19:36:45.006 INFO [zr] 82.76.235.114   GET     200   5ms (lp: 51.0s) /json/events [1522220881:9/1/heartbeat] (richard.vencu@dentfix.ro via ZulipElectron)
2018-03-29 19:36:49.584 INFO [] Tornado   0.3% busy over the past 59.6 seconds
2018-03-29 19:36:52.821 INFO [zr] 127.0.0.1       GET     200   3ms /api/v1/events [1522220881:12/0] (richard.vencu@dentfix.ro via internal)
2018-03-29 19:36:52.949 INFO [zr] 127.0.0.1       GET     200   2ms /api/v1/events [1522220881:12/0] (richard.vencu@dentfix.ro via internal)
2018-03-29 19:36:53.672 INFO [zr] 82.76.235.114   GET     200   5ms (lp: 7.7s) /json/events [1522220881:9/1/presence] (richard.vencu@dentfix.ro via ZulipElectron)
2018-03-29 19:36:53.673 INFO [zr] 82.76.235.114   GET     200   5ms (lp: 87ms) /json/events [1522220881:12/1/presence] (richard.vencu@dentfix.ro via website)
2018-03-29 19:36:54.452 INFO [zr] 82.76.235.114   SOCKET  200   0ms /socket/open [transport=xhr_streaming] (unknown via ?)
2018-03-29 19:36:54.511 INFO [] Client disconnected for queue 1522220881:12 (richard.vencu@dentfix.ro via website)
2018-03-29 19:36:54.530 INFO [zr] 82.76.235.114   SOCKET  200   9ms (db: 2ms/1q) /socket/auth [transport=xhr_streaming] (richard.vencu@dentfix.ro via ?)
2018-03-29 19:36:55.584 INFO [] Tornado   0.3% busy over the past 60.0 seconds`

**Comment by rvencu** [comment]
Guess tornado.log takes UTC  time while nginx takes local time (UTC+3). 
The desktop app is still running well, with 182 502 errors in console now.

**Comment by rvencu** [comment]
Is there a way to dump the database and try a fresh setup on a clean system then restore it? If so what is the best Ubuntu OS to start with? We can continue debugging though if you like so...

**Comment by timabbott** [comment]
The other thing to check is what you have in `/etc/hosts`; I could imagine this being caused by weird configuration there.  But I don't have any other ideas for what would cause this weird behavior; it seems surely something weird about your server configuration, but I can't tell what.

For your last question, check out our backups documentation on ReadTheDocs -- that explains how to do what you're asking.  And I'd install on Ubuntu 16.04 -- we're likely desupporting 14.04 in the future.

**Comment by rvencu** [comment]
127.0.0.1	localhost
91.194.31.43	chat.dentfix.ro	chat

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

Thanks for directions

**Comment by rvencu** [comment]
I just noticed another thing, the calls to events?... that succeed with status 200 are taking some 52 seconds to do so. Maybe the ones that fail only fail because they cross the 60 seconds barrier?
Edit: it is not that. I put a timer and count only 19 seconds for a failure to appear...

**Comment by rvencu** [comment]
I installed a fresh server 16.04 LTS, did an apt-get upgrade then installes zulip server and moved the database and secrets over the new server. The move apparently succeded because I could login automatically with zulip-electron client after first server start. Everything was replicated, SSL certificate, hostname and network settings. In less than one hour the client crashed again

Nginx error log shows similar issues that repeats a lot after the moment the client crashed :
`2018/03/30 21:03:01 [error] 26907#26907: *68 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=false&queue_id=1522430032%3A0&last_event_id=58 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=false&queue_id=1522430032%3A0&last_event_id=58", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"`

Restarting the client I can see the interface properly.

While the client works, in nginx error log I can see this set of errors:
`2018/03/30 20:06:24 [crit] 26907#26907: *1 connect() to unix:/home/zulip/deployments/uwsgi-socket failed (2: No such file or directory) while connecting to upstream, client: 82.76.235.114, server: , request: "POST /json/users/me/presence HTTP/1.1", upstream: "uwsgi://unix:/home/zulip/deployments/uwsgi-socket:", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/30 20:06:31 [error] 26907#26907: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /json/events?dont_block=true&queue_id=1522416307%3A0&last_event_id=180 HTTP/1.1", upstream: "http://[::1]:9993/json/events?dont_block=true&queue_id=1522416307%3A0&last_event_id=180", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"
2018/03/30 20:06:33 [error] 26907#26907: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 82.76.235.114, server: , request: "GET /sockjs/info?cb=k7csgfl7ko HTTP/1.1", upstream: "http://127.0.0.1:9993/sockjs/info?cb=k7csgfl7ko", host: "chat.dentfix.ro", referrer: "https://chat.dentfix.ro/"`

**Comment by rvencu** [comment]
supervisorctl status outputs this (while apparently I can use the client):
`process-fts-updates                                             FATAL     Exited too quickly (process log may have details)
zulip-django                                                    RUNNING   pid 32832, uptime 1:07:58
zulip-senders:zulip_events_message_sender-0                     RUNNING   pid 32841, uptime 1:07:57
zulip-senders:zulip_events_message_sender-1                     RUNNING   pid 32842, uptime 1:07:57
zulip-senders:zulip_events_message_sender-2                     RUNNING   pid 32843, uptime 1:07:57
zulip-senders:zulip_events_message_sender-3                     RUNNING   pid 32844, uptime 1:07:57
zulip-tornado                                                   RUNNING   pid 32830, uptime 1:07:59
zulip-workers:zulip_deliver_enqueued_emails                     RUNNING   pid 32890, uptime 1:07:54
zulip-workers:zulip_events_digest_emails                        RUNNING   pid 32887, uptime 1:07:55
zulip-workers:zulip_events_email_mirror                         RUNNING   pid 32880, uptime 1:07:55
zulip-workers:zulip_events_embed_links                          RUNNING   pid 32885, uptime 1:07:55
zulip-workers:zulip_events_embedded_bots                        RUNNING   pid 32879, uptime 1:07:55
zulip-workers:zulip_events_error_reports                        RUNNING   pid 32889, uptime 1:07:55
zulip-workers:zulip_events_feedback_messages                    RUNNING   pid 32874, uptime 1:07:55
zulip-workers:zulip_events_invites                              RUNNING   pid 32876, uptime 1:07:55
zulip-workers:zulip_events_missedmessage_email_senders          RUNNING   pid 32883, uptime 1:07:55
zulip-workers:zulip_events_missedmessage_emails                 RUNNING   pid 32882, uptime 1:07:55
zulip-workers:zulip_events_missedmessage_mobile_notifications   RUNNING   pid 32886, uptime 1:07:55
zulip-workers:zulip_events_outgoing_webhooks                    RUNNING   pid 32877, uptime 1:07:55
zulip-workers:zulip_events_signups                              RUNNING   pid 32878, uptime 1:07:55
zulip-workers:zulip_events_slow_queries                         RUNNING   pid 32884, uptime 1:07:55
zulip-workers:zulip_events_user_activity                        RUNNING   pid 32888, uptime 1:07:55
zulip-workers:zulip_events_user_activity_interval               RUNNING   pid 32881, uptime 1:07:55
zulip-workers:zulip_events_user_presence                        RUNNING   pid 32875, uptime 1:07:55`

**Comment by rvencu** [comment]
After a reboot fts-updates started and is stable. Before it claimed in error log that zulip role does not exists.

The client reconnected and it behaves exactly like before. This is a clean setup on Ubuntu server 16.04 + zulip server 1.7.1 and I did not touch anything except installing openssh-server so I can access it remotely.
![image](https://user-images.githubusercontent.com/287411/38150991-1875c7e0-346a-11e8-9620-f384b0f46e91.png)

**Comment by timabbott** [comment]
One other possibility I can think of is something wrong with your network.  The `/events` queries are meant to do long-polling (i.e. hold open the request for up to a minute waiting for a response)  If you have a network with an unusual configuration, it could (e.g.) set a very short timeout, like 30s, on the maximum duration of HTTP requests.  That would potentially explain the irregular success of these requests.

**Comment by rvencu** [comment]
I have a way to test that, will do a failover to the replicated VM that is located offsite in a different network, even different ISP.

**Comment by akashnimare** [comment]
@rvencu quick question - you can reproduce this bug in chrome, right?

**Comment by rvencu** [comment]
Yes. Chrome or Zulip-electron is behaving in same way

**Comment by rvencu** [comment]
Test 1 failed. I replicated the VM in my home network. Changed networking settings with intranet IP address, also updated /etc/hosts. The on my computer I edited hosts file to point to the intranet IP address for chat.dentfix.ro

I was able to connect properly. The behaviour is the same. I only have one Cisco switch between my computer and the server and of course the Hyper-V 2016 hypervisor architecture until I reach the VM.

**Comment by rvencu** [comment]
Test 2 failed. I used a remote computer in a third network to connect to the original server visible on internet. Same behaviour, so I ruled out my computer and my computer network.

**Comment by akashnimare** [comment]
@gnprice any idea what's going on here?

**Comment by rvencu** [comment]
If needed I can export the hyper-v VM and send it over for local debugging.

**Comment by akashnimare** [comment]
@rvencu hey, can you please repost your problem [here](https://chat.zulip.org/#narrow/stream/31-production-help) so that you can get it fixed asap?

**Comment by akashnimare** [comment]
Closing as not relevant to the electron app (the main issue is in the server configuration).
