### ISSUE TITLE
Unreadable Newbie Tips

### ISSUE THREAD

**Issue by Valkryst** [zulip/zulip-desktop#467]
Switch to night mode in your browser, then log-in to the dektop app. The desktop app will automatically be in night mode. Next, look at the hints that pop up when you're a new user.

The hints have a white background with light grey text. It's entirely unreadable.

---

Zulip 1.9.0
Electron 1.8.4
linux x64 4.4.0-116-generic

**Comment by akashnimare** [comment]
@Valkryst can you paste a screenshot?

**Comment by Valkryst** [comment]
@akashnimare I can, if there's a way to re-enable the tips. I think I've clicked through them all at this point

**Comment by Valkryst** [comment]
Scratch that. I created a second account, followed the steps again, and reproduced the issue.

Here's a screenshot.
![zulip_062](https://user-images.githubusercontent.com/1524476/38097332-768b318c-334b-11e8-8738-f4dd1a228327.png)

**Comment by timabbott** [comment]
I assume this is actually just a webapp issue, not a desktop app issue.

**Comment by abhigyank** [comment]
@Valkryst Can you create an issue at https://github.com/zulip/zulip/issues ? It is a webapp issue, as the desktop app is a web client.

**Comment by Valkryst** [comment]
@abhigyank Yup, I've created the issue over there.

https://github.com/zulip/zulip/issues/8868

**Comment by akashnimare** [comment]
Fixed in https://github.com/skunkmb/zulip/commit/382f93189f9c54bb1041ebe612eb4f0646911b61.
