### ISSUE TITLE
installer: Update installation image for DMG installer.

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#474]
* Rename `Zulip-desktop` to `Zulip`
* Try new design (maybe add Zulip's logo)
<img src="https://github.com/zulip/zulip-electron/blob/master/build/appdmg.png?raw=true"/>

**Comment by abhigyank** [comment]
![appdmg](https://user-images.githubusercontent.com/20434085/39049158-e9fd90a0-44bd-11e8-8253-17206a8af39c.png)
@akashnimare Looks good for PR?

**Comment by akashnimare** [comment]
The Zulip logo kinda looks odd. Can you reduce the size and paste it here?

**Comment by abhigyank** [comment]
![image](https://user-images.githubusercontent.com/20434085/39050155-f007f2b6-44c1-11e8-977f-ee56ef9541c0.png)

**Comment by akashnimare** [comment]
Updated, this is how it looks now - 

![image](https://user-images.githubusercontent.com/2263909/39725992-3707f68c-526b-11e8-8baa-888969453698.png)
