### ISSUE TITLE
App bright white flashing and flickering while scrolling

### ISSUE THREAD

**Issue by ghost** [zulip/zulip-desktop#477]
---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubutnu
  - [x] macOS Sierra
- **Clear steps to reproduce the issue**: 
While scrolling through messages in a stream topic, there's recurrent bright white flashes in a flickering streak across the screen. This does not happen while using Zulip in a browser.
The app is also using a significant amount of CPU usage while open.
- **Relevant error messages and/or screenshots**:

**Comment by akashnimare** [comment]
@eligang can attach a screenshot/gif here?

**Comment by ghost** [comment]
@akashnimare here you are. thanks
![zulip bug screen record redact](https://user-images.githubusercontent.com/38563626/39133432-29826fe0-46e2-11e8-9bb2-796bfcac9071.gif)

**Comment by warsaw** [comment]
I see exactly the same thing with Zulip 1.9.0 on macOS 10.13.4 (High Sierra).

**Comment by abhigyank** [comment]
@eligang Can you reproduce this flicker in the normal white display(non night mode) too?

**Comment by warsaw** [comment]
@abhigyank It does not seem to happen for me in the normal (non-night mode) display.

**Comment by akashnimare** [comment]
Interesting. Never seen this kind of bug, let me try to reproduce this.

**Comment by akashnimare** [comment]
@eligang, @warsaw I can't reproduce this. 



<img src="https://dzwonsemrish7.cloudfront.net/items/2A0n241b0b2q3J0y3W19/Screen%20Recording%202018-04-24%20at%2002.01%20PM.gif?v=0d44d532"/>


Can you folks reproduce this issue on https://chat.zulip.org/ server?

**Comment by timabbott** [comment]
Howdy @warsaw!  Can you check whether you get the same issue if you do the same scrolling in the Zulip webapp in Chrome?  That'd be helpful for isolating whether it's a webapp or Electron bug.

(Also, are you using the latest 1.9.0 release of the Electron app?  I assume so, since the Python community usage of Zulip is new, but wanted to confirm)

**Comment by warsaw** [comment]
@timabbott Hi!  I cannot reproduce this with the Zulip webapp in Chrome in night mode.  Only the macOS desktop client in night mode AFAICT.

**Comment by timabbott** [comment]
Good to know.  This feels like a browser bug (basically in upstream electron).  @akashnimare I think the next thing to try is to download the version of Chromium that Electron is on and reproduce that there?

**Comment by ghost** [comment]
@timabbott I actually am having some flashy blips in the regular non-night mode of the Zulip Electron app (yes, the 1.9.0 release) on Mac as well, but not nearly as bad or frequently consistent flickering as shown in night mode (although it also might just be less obvious in this scheme). Whether or not it's on the high contrast mode doesn't seem to make a difference either.

**Comment by akashnimare** [comment]
I think this might be a caching issue. Can you folks clear the application data using the following option from setting page - 

![image](https://user-images.githubusercontent.com/2263909/39261474-34c1e54e-48da-11e8-8d57-aed7c3d46f8f.png)

**Comment by timabbott** [comment]
I don't really see a story for how this would be a caching issue.  But I guess it's pretty hard to come up with a good theory for why this is happening that isn't something weird:
* It doesn't reproduce with Chrome for the same users
* It doesn't reproduce for other users with the desktop app.

**Comment by warsaw** [comment]
Resetting the app data does not fix the problem for me, although as I'm watching it now, the flashing is more apparent when scrolling quickly.

**Comment by akashnimare** [comment]
Here is my observation (macOS 10.13.2 High Sierra)
* Works as expected in night mode and normal mode (chat.zulip.org server).
* Same result on python's Zulip server.

@warsaw let me update to macOS 10.13.4 and check if I can reproduce this.

**Comment by akashnimare** [comment]
Updated to macOS 10.13.5 Beta but no luck reproducing the issue.
This might be related - https://bugs.chromium.org/p/chromium/issues/detail?id=470669

**Comment by ghost** [comment]
This does sound like a similar problem, but is it related when using the Zulip desktop app in Mac OS? I don't tend to have this issue while using the web app in Chrome (or Safari), so it seems to be specifically something with the macOS app- and I'm only on 10.12.6 Sierra.

**Comment by shidarin** [comment]
I also have this problem.

https://gfycat.com/charmingpeskychinesecrocodilelizard

OSX 10.12.6
Zulip Desktop App 1.9.0

Not present in the web app.

Occurs on both CZO and our internal Zulip instance (which is on 1.8). I've been having this issue since before the 1.8 upgrade though.

It's very obvious on the dark theme. I've switched to the light theme and *think* I've seen it once or twice. I will attempt to record it.

**Comment by akashnimare** [comment]
Can you folks reproduce this bug in the latest release which is `v2.0.0` ?

**Comment by warsaw** [comment]
The macOS version for download is still 1.9.0 and there doesn't seem to be a menu option to download and install a new version.

**Comment by akashnimare** [comment]
@warsaw the app should auto-update itself in a while. App will show following popup -

![image](https://user-images.githubusercontent.com/2263909/39379412-c3b7074e-4a78-11e8-9e2f-ea328d0750d0.png)

Feel free to comment if it doesn't show this in a while.

**Comment by timabbott** [comment]
@akashnimare maybe worth opening a separate issue for adding a "check for updates" option on the screen showing the version?  I think that would be a good idea for this sort of test-a-new-release situation.

**Comment by akashnimare** [comment]
Yeah, I had thought to do so but somehow missed it. Generally, desktop app adds this option in the file menu item - 

![image](https://user-images.githubusercontent.com/2263909/39380662-f9e43f90-4a7c-11e8-87cd-8e789fa9a277.png)

**Comment by ghost** [comment]
I've updated to the 2.0.0 version and no change- still the bright white flashing. I am also on an internal Zulip server instance at our org. 

I recall this being the case before the 18.0 app version as well, but it either became worse/ more frequent or just more obviously headache-inducing apparent with the night mode setting, which would otherwise be my preferred view. But it also does happen in the regular non-night mode too.

**Comment by shidarin** [comment]
Experienced this issue again today on 2.0 on both CZO and a self hosted instance (both running the 1.8.1-rc) it was on both white and dark themes, but reset itself when I changed apps to start a screen capture. FYI, changing apps does seem to reset it frequently. Hard to capture.

**Comment by akashnimare** [comment]
@shidarin okay, I'll be releasing a new beta release tomorrow which uses the updated chromium version and I'm hoping this error will be sorted after that.

**Comment by timabbott** [comment]
Yeah, this certainly feels like a browser bug.

**Comment by abhigyank** [comment]
A new beta [v2.2.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v2.2.0-beta) has been released, this contains an update to the electron version which uses an updated chromium version, which hopefully should solve  this issue. So please give  this beta a try. To upgrade to this version, you need to check the **Get beta updates** option from app settings. Or manually download from  [here](https://github.com/zulip/zulip-electron/releases/tag/v2.2.0-beta) .

**Comment by warsaw** [comment]
Indeed.  A quick test with 2.2.0-beta appears to have fixed the problem.  I'll keep an eye on it, but so far so good!  Thanks.

**Comment by akashnimare** [comment]
@warsaw awesome. @shidarin, @eligang can you folks also confirm if this works for you?

**Comment by ghost** [comment]
@akashnimare Just updated to the beta version. Yes, this is great- MUCH smoother now when scrolling and the flashing issues seems to be completely resolved (even in night mode)! Thank you :)

**Comment by akashnimare** [comment]
@eligang good to know. Feel free to reopen the issue if you see something like this in future!

**Comment by shidarin** [comment]
I've also updated to the beta and have also not hit this issue yet.
