### ISSUE TITLE
Add an option to check latest release using menu item

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#479]
![image](https://user-images.githubusercontent.com/2263909/39380800-794a1c00-4a7d-11e8-817f-b2f1cb79cc37.png)

On clicking the check for update, app should show a dialog which should contains the latest release version and the one user is currenlty using. We can also put this option in the `About Zulip` page.

**Comment by abhigyank** [comment]
What should be the working if an update is available? 
Or this would just show the latest version and the current version?
