### ISSUE TITLE
Message being composed is lost when website reloads

### ISSUE THREAD

**Issue by lablans** [zulip/zulip-desktop#490]
---

- **Operating System**:
  - [X] Windows
  - [not tested] Linux/Ubuntu
  - [not tested] macOS
- **Clear steps to reproduce the issue**:
  - Write a long message (but don't send it yet)
- **Relevant error messages and/or screenshots**:
  - While you type, the window may be reloaded for some reason.
  - Once the reload is complete, you'll find that the text you entered so far is gone (i.e. message compose box is empty)

**Comment by abhigyank** [comment]
The message should be stored in drafts. You can use shortcut key `d` to access drafts. Clicking on the message / pressing `Enter` would load the message onto the compose box.

**Comment by akashnimare** [comment]
This is the expected behaviour, you can find those messages in the drafts.

**Comment by lablans** [comment]
Thanks for your replies. But do you really think it's user-friendly to have him/her press a button he/she does not even know about? Wouldn't it make more sense to re-open the latest draft automatically?
