### ISSUE TITLE
Add an option to disable the auto-updates

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#491]
This could be useful for users who are not an admin of the machine.

**Comment by gnc-tibo** [comment]
How should the administrator disable automatic updates? Is there a preference domain/key for that (macOS) ?

Thanks!

**Comment by timabbott** [comment]
The `autoUpdate` configuration field; see https://github.com/zulip/zulip-desktop/blob/main/docs/Enterprise.md for how to configure that.

**Comment by gnc-tibo** [comment]
Perfect, thanks Tim !
