### ISSUE TITLE
Linux64 AppImage does not automatically update to v2.0

### ISSUE THREAD

**Issue by stone212** [zulip/zulip-desktop#492]
---

- **Operating System**:
  - [x] Linux/Ubutnu
- **Clear steps to reproduce the issue**:

- Download Zulip-1.9.0-x86_64.AppImage to /opt
- Make executable
- Create symlink to /usr/bin/zulip
- Use successfully.

Then when version 2.0 came out, you will see a popup window asking you if you want to upgrade.  You say yes.  The popup goes away.  Then later on it comes back and asks you the same question.

Manually downloading Zulip-2.0.0-x86_64.AppImage is successful.  So it is not the new binary.  (Also this happened between 1.8.2 and 1.9.0).

IMPORTANT NOTE:

It seems obvious this is because the AppImage is in /opt which is owned by root.  (right?)  So an option to enter root/sudo password when upgrading might solve this.

**Comment by abhigyank** [comment]
A new issue can be created if not working with newer versions as well.
