### ISSUE TITLE
Colors muted in 2.2.0 beta

### ISSUE THREAD

**Issue by shidarin** [zulip/zulip-desktop#497]
MacOS Sierra

I was hitting the white flashing bug when I remembered it was fixed in a beta release. I downloaded the beta, installed it, closed and re-opened Zulip to find all the colors are now very desatured or muted. I re-opened 2.0 and compared them, and found this to be true.

It can be subtle, but everything, even the bg color changes.

![colorcompare](https://user-images.githubusercontent.com/5846610/40397444-a904f8ca-5de7-11e8-9b35-89d4605d963e.png)

I did not notice this when I was using the beta with Windows 7, but it still might be present.

**Comment by akashnimare** [comment]
Yeah, it's a known bug in the electron - https://github.com/electron/electron/issues/10732.

**Comment by akashnimare** [comment]
@shidarin I have pushed a temporary fix for this issue, I'll release the new version today which will have this fix.

**Comment by akashnimare** [comment]
@shidarin new release [v2.3.1](https://github.com/zulip/zulip-electron/releases/tag/v2.3.1) is up. Let me know if this fixes the color issue.

**Comment by shidarin** [comment]
Does indeed seem to be fixed!

**Comment by akashnimare** [comment]
Awesome.
