### ISSUE TITLE
Can't save/open attached documents on Linux and Mac

### ISSUE THREAD

**Issue by ababak** [zulip/zulip-desktop#498]
The only way to open attached .doc or .pdf is to drag the link and drop it to browser (and you have to be logged in there).
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [x] macOS
- **Clear steps to reproduce the issue**:
Send a .pdf or .doc file, try to click or right-click (nothing happens). Windows version shows the contextual menu but not Mac or Linux.
- **Relevant error messages and/or screenshots**:

**Comment by abhigyank** [comment]
@ababak This has been merged in the master through #483 which gives an option to download the attached file on clicking it. It is available in the the v2.2.0-beta release. The stable version with this feature should released this week.

**Comment by ababak** [comment]
Great, thanks.

**Comment by akashnimare** [comment]
@ababak can you check if this works as expected in the latest release [v2.3.1](https://github.com/zulip/zulip-electron/releases/tag/v2.3.1)?

**Comment by ababak** [comment]
@akashnimare Can't see any improvements on Linux. Clicking or right-clicking on .zip and .pdf files are just ignored. No downloads, no context menus.
Even noticed another bug: when clicking on attached picture filename (not the picture itself) I can't go back with Escape and the only way to exit is pressing 'back' button which reloads everything.

**Comment by abhigyank** [comment]
The behavior should be clicking on .pdf type of files it should open up a download dialog box, and clicking on the picture filename should show the same behavior as clicking on the picture itself.
I cannot reproduce the the behaviour mentioned by @ababak on Linux in the v2.1.3.

@ababak can you confirm that you on v2.1.3 by clicking on File -> About Zulip ?

**Comment by ababak** [comment]
Hi @abhigyank,

I was actually on v2, sorry for the confusion. It looks like running the updated version just brought to front the old version that was running in the background.

I can confirm that in v2.1.3 clicking the link opens the download dialog box.

Thank you.

Cheers,
Andriy

**Comment by akashnimare** [comment]
@ababak good to know.
