### ISSUE TITLE
Add server URL configuration variable

### ISSUE THREAD

**Issue by mastodon** [zulip/zulip-desktop#5]
I filled out the initial configuration dialog with a bogus URL under OSX. There appears to be no way of changing said URL later under Preferences.

**Comment by timabbott** [comment]
Yeah that definitely needs to be added to preferences, and should be easy to do.  There are a few workarounds available:

* Run it with e.g. "zulip --site https://zulip.example.com"
* It saves a config file somewhere; I don't have a mac handy so I can't easily check where; @lfranchi can you post that on this thread?

**Comment by bastianh** [comment]
I found 2 preferences files in 
~/Library/Preferences/com.zulip.Zulip.plist
and
~/Library/Preferences/org.zulip.Zulip\ Desktop.plist
but deleting them did not reset the server

**Comment by mastodon** [comment]
I also dug around in the code and I am not certain that the --site option does anything on the Mac desktop.

**Comment by lfranchi** [comment]
OK there were some recently introduced issues that I just pushed a fix for. The state of the world is now:

1. `--site <foo>` overrides all other domain options and will load that Zulip domain (and save it for the future)
2. the `Domain` setting in `org.zulip.Zulip Desktop.plist` is used by default
3. If no `Domain` setting exists AND `InstanceDomains` (a list) exists, use the last InstanceDomain domain url

Additionally, changing the domain is always possible via the tray icon: there's a Domains menu item that lets you switch + add more domains.

**Comment by timabbott** [comment]
@lfranchi have we done a new release with these fixes?

**Comment by lfranchi** [comment]
@timabbott Not yet

**Comment by aedelsten** [comment]
Was the "--site" command line parameter added to the Windows client as it doesn't seem to work on the "zulip-latest.exe" installer from today.

Additionally, where is the server address stored on Windows as I can't see it anywhere.

**Comment by lfranchi** [comment]
@aedelsten the current build doesn't have the above fix.

On windows I need to check, but it's stored in the registry (I think `HKEY_CURRENT_USER\Software\Zulip` or something like that). You can remove all Zulip entries in the registry and open zulip

**Comment by aedelsten** [comment]
@lfranchi thanks for that, I found it here: HKEY_CURRENT_USER\Software\Zulip\Zulip Desktop\InstanceDomains\1

**Comment by nibbler3465** [comment]
@lfranchi i was able to get a custom domain with desktop setting the `Domain` string value in `HKEY_CURRENT_USER\SOFTWARE\Zulip\Zulip Desktop\`. It is worth noting that the domain needed to be specified with protocol (ie 'https://customdomain.com', as opposed to 'customdomain.com')

**Comment by versipellis** [comment]
Does this still work? Both the "--site" command line parameter and the registry key approach don't seem to work anymore.

**Comment by akashnimare** [comment]
@versipellis we are switching to [zulip-electron](https://github.com/zulip/zulip-electron). Please use it; if possible :)

**Comment by versipellis** [comment]
Thanks - I've installed it and it runs fine. Symantec throws a WS.1 warning
because it's an unrecognized file in their system, so I've gone ahead and
helped you guys file a dispute ticket as a user for a false positive on it.

**Comment by versipellis** [comment]
Symantec has approved it and whitelisted the file :)

**Comment by akashnimare** [comment]
@versipellis awesome, thanks 🤝 
Please download the latest release - [v1.0.0-beta](https://github.com/zulip/zulip-electron/releases/tag/v1.0.0-beta)/[Installer](https://github.com/zulip/zulip-electron/releases/download/v1.0.0-beta/Zulip-Web-Setup-1.0.0-beta.exe) which is properly code signed. You may get a warning from Windows Defender. It is displayed based on the reputation of the certificate. That warning will go away once more valid installs occur.
