### ISSUE TITLE
Font rendering on Windows 10

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#500]
A user reported - 
> Hi, the font rendering in the new client is blurry. In 1.9.0. it was sharp and great. Now it is very exhausting to work with it again. I'm using Win10. I already switched to high contrast mode.
I know it is a subjective opinion. I only wanted to mention it, perhaps there are more people on the list. Perhaps you should consider a system font.
Best Regards,
App: Zulip 2.3.2
Electron: 2.0.1 (Node v8.9.3)
Operating System: win32 x64 10.0.16299

**Comment by abhigyank** [comment]
@akashnimare We could close this now (doesn't seem to be an issue in the latest version),
