### ISSUE TITLE
Please add usage of default context menu on MacOS

### ISSUE THREAD

**Issue by ghost** [zulip/zulip-desktop#504]
The desktop app currently only shows a basic context menu if you right-click a word:

![screen shot 2018-06-21 at 14 56 11](https://user-images.githubusercontent.com/2435189/41720434-53357eb8-7563-11e8-9842-4e3be1505687.png)

It would be very helpful if the full MacOS context menu would be supported like in this screenshot:

<img width="212" alt="screen shot 2018-06-21 at 14 58 09" src="https://user-images.githubusercontent.com/2435189/41720512-8e339c2a-7563-11e8-9bea-5b8876c92474.png">

Especially the "Services" section is important as this will allow you to use selections with AppleScript services e.g. for automatically looking up selected numbers in Bugzilla, Jira or other tools of choice.

---
- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubutnu
  - [X] macOS

**Comment by akashnimare** [comment]
@dennissieben there is a `service` menu item also which you can use -

![image](https://user-images.githubusercontent.com/2263909/41762054-13c2ca74-7617-11e8-89fd-ee5d8794a6d4.png)

**Comment by ghost** [comment]
Yes but as the context menu is not properly setup it can't access your currently selection at the moment. Otherwise you would see some services in there instead of "No Services Apply" see below:

![screen shot 2018-06-22 at 10 07 45](https://user-images.githubusercontent.com/2435189/41765407-4461d5a2-7604-11e8-8104-4a0ea46e78e6.png)

**Comment by akashnimare** [comment]
To add this, I think we need to fork [electron-spellcheck](https://github.com/electron-userland/electron-spellchecker) and make changes since this feature is handled by that module.

**Comment by akashnimare** [comment]
@manavmehta let's look into this once we are done with the basic context-menu.

**Comment by manavmehta** [comment]
@akashnimare Sure. I think we can do this using the Menu API itself ([see here](https://www.electronjs.org/docs/api/menu#notes-on-macos-application-menu)) before merging.

**Comment by akashnimare** [comment]
@dennissieben adding this in the next release.
