### ISSUE TITLE
Feature request: macOS Bounce to Alert

### ISSUE THREAD

**Issue by vulkman** [zulip/zulip-desktop#510]
OS: macOS 10.12.6 (16G1408)

Right now Zulip supports integration with Notification Center, which is great, but for users of the fullscreen mode it would be great to also use Bounce to Alert, so you see the icon even when you have another app in fullscreen and are in Do-not-Disturb mode.

**Comment by akashnimare** [comment]
@vulkman do you mean boucing the dock on new notifications?

<img src="https://dzwonsemrish7.cloudfront.net/items/21381y3r0C3917001C1j/Screen%20Recording%202018-07-05%20at%2007.04%20PM.gif"/>

**Comment by vulkman** [comment]
Exactly!
