### ISSUE TITLE
File download not working/no dialog shown

### ISSUE THREAD

**Issue by lukasIO** [zulip/zulip-desktop#523]
referring to https://github.com/zulip/zulip-electron/commit/6787b8d5573b1118851a4bb91e1e32fccb12dd2a

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Zulip hosted on private server. Click on file attachment. nothing happens, just a short sound is played. No notification shown and file is not being downloaded.
- **Relevant error messages and/or screenshots**:

**Comment by abhigyank** [comment]
@lukasIO We are aware that this is breaking for some people. Can you let me know if  you are using proxy?

**Comment by lukasIO** [comment]
If I am using a proxy on my system? No.

**Comment by akashnimare** [comment]
@lukasIO this has been fixed in the new beta release [v2.3.4-beta](https://github.com/zulip/zulip-electron/releases/tag/v2.3.4-beta). You can get it using `App Settings > Get Beta updates`. Let me know if it works.

**Comment by lukasIO** [comment]
Fallback to old version works, but the (much desired) open with default-app option doesn't work :\

**Comment by akashnimare** [comment]
This should work on https://chat.zulip.org. Can you cross check?

**Comment by lukasIO** [comment]
on https://chat.zulip.org the file download works, but no notification is shown, i hear a sound once the file download has completed, but i dont see any visual indication that the download is started/progressing/finished. also file doesn't open automatically after download. just sits in downloads folder...

**Comment by abhigyank** [comment]
@lukasIO  On Windows please ensure that the notifications from apps is on in your Windows settings.
![untitled23](https://user-images.githubusercontent.com/20434085/43147483-c44bad3e-8f80-11e8-9c38-20a67439b0cb.png)

**Comment by lukasIO** [comment]
thanks, indeed it was disabled, but weirdly enough only for zulip.
it would be a lot less confusing to add a download started and progress indication (not via desktop notifications, but rather as a small hint somewhere inside the app) and a "downloaded files" section that gets displayed after clicking a button (preferably over the do not disturb button on the left pane)

**Comment by lukasIO** [comment]
what could be the reason this approach doesnt work on privately hosted zulip instances?

**Comment by akashnimare** [comment]
@lukasIO Just an update on this.  The broken download attachment feature in fixed in the latest release v2.3.5. The app should be able to auto-update itself. 

Please check it and let me know if it works as expected.

**Comment by lukasIO** [comment]
Thanks, seems to work as expected now! The lack of indication that a download has actually started will probably be very confusing for people new to zulip...
