### ISSUE TITLE
Missing "-mac" in Zulip-2.3.3.zip breaks Homebrew install

### ISSUE THREAD

**Issue by l00mi** [zulip/zulip-desktop#524]
Since the 2.3.3 release the name of the mac zip release changed from the format Zulip-2.3.2 **-mac** .zip to Zulip-2.3.3.zip. This breaks the install through homebrew.

---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubutnu
  - [x] macOS
- **Clear steps to reproduce the issue**:
Install with homebrew fails because of changed filename.
- **Relevant error messages and/or screenshots**:
```
Installing zulip cask. It is not currently installed.
==> Satisfying dependencies
==> Downloading https://github.com/zulip/zulip-electron/releases/download/v2.3.3/Zulip-2.3.3-mac.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'zulip' with message: Download failed: https://github.com/zulip/zulip-electron/releases/download/v2.3.3/Zulip-2.3.3-mac.zip
Installing zulip has failed!
```

**Comment by akashnimare** [comment]
@l00mi fixed. Can you try again?

**Comment by l00mi** [comment]
Brew installs again! Thank you.
