### ISSUE TITLE
Alt+Shifts opens upper menu but we use that shortcut to switch languages.

### ISSUE THREAD

**Issue by winmasta** [zulip/zulip-desktop#528]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu - Mint 18.3
  - [ ] macOS
- **Clear steps to reproduce the issue**:
1.Run application
2.Choose any chat or stream by clicking on it
3.Put cursor to message entry window
4.Press Alt+Shift
- **Relevant error messages and/or screenshots**:
![default](https://user-images.githubusercontent.com/29568484/43256643-8e8c6256-90f7-11e8-9ace-590919015d59.png)

Input language switch expected, but File menu opened and there is no ability to continue typing message. It could be very useful to disable Zulip Alt+Shift keyboard shortcut.

**Comment by abhigyank** [comment]
Hi @winmasta I couldn't reproduce this on Ubuntu 16.04. Zulip doesn't specifically use Alt+Shift to open File Menu i.e. this is not a Zulip level shortcut. I'd assume this is something Mint does by itself. I am not sure if we can explicitly stop this.
Maybe you can check the shortcuts in Mint System Preferences - > Keyboard.

**Comment by winmasta** [comment]
I have checked all OS shortcuts and didn't find Alt+Shift, moreover I am using Mint for more than 5 years already and never faced with such problem, moreover it affects only Zulip app.

**Comment by akashnimare** [comment]
@winmasta I can successfully switch the language using the `Alt+Shift` key combination on Ubuntu 16.04. You may find that shortcut in keyboard setting, please [see](https://stackoverflow.com/questions/22384513/how-does-one-add-keyboard-languages-and-switch-between-them-in-linux-mint-16). Also, can you switch language using the same shortcut in other apps?

**Comment by winmasta** [comment]
@akashnimare Yes I can switch the language anywere but Zulip app. Trying to switch language in Zulip app leads to throwing down upper menu of the app.
![default](https://user-images.githubusercontent.com/29568484/43390031-70f72db6-9417-11e8-9221-82002b575c8a.png)

**Comment by akashnimare** [comment]
Okay. This looks like an [upstream](https://github.com/electron/electron) issue and for some reason, it doesn't work in the mint os. I'll file an issue there and will look for the potential solution.

**Comment by winmasta** [comment]
Thanks.

**Comment by baumnkz** [comment]
I'm using Linux Mint 18.3 and Zulib desktop, and I have the same problem.

In other applications have already solved this problem:
https://github.com/RocketChat/Rocket.Chat.Electron/commit/5b684bbd4df4a583ac39a7f96a980da6feeabbe4

https://github.com/ramboxapp/community-edition/pull/432

**Comment by baumnkz** [comment]
I think, you need to add '&' before menu labels

**Comment by akashnimare** [comment]
@baumnkz yeah, let me try the mentioned fix. Are you up for debugging this? I can release a quick beta on Linux.

**Comment by baumnkz** [comment]
@akashnimare yes, I'm ready to debugging

**Comment by akashnimare** [comment]
Okay, thanks. Are you using the `.deb` installer?

**Comment by baumnkz** [comment]
Yes, I am

**Comment by akashnimare** [comment]
@baumnkz I have published a new beta release for Linux - v2.3.8-beta. You need to run the following in order to get it (you might need to uninstall the stable version first) -

https://zulipchat.com/help/desktop-app-install-guide#linux-with-apt-ubuntu-or-debian-8

**Comment by winmasta** [comment]
![default](https://user-images.githubusercontent.com/29568484/45476955-8de7df80-b76a-11e8-96b1-b6e5da5e0757.png)
still problem

**Comment by baumnkz** [comment]
@akashnimare Great! But now one of menu item is hiding - help menu is not visible

When I press Alt+Shift now opened non-labeled menu:
![help-menu](https://user-images.githubusercontent.com/972908/45476953-8c1e1c00-b76a-11e8-8ae4-f7e6401ad363.png)

**Comment by akashnimare** [comment]
@baumnkz just fixed it and pushed a new beta. Can you update and check if it works as expected?

**Comment by baumnkz** [comment]
@akashnimare Great! It works!

**Comment by akashnimare** [comment]
Awesome, thanks for the help ❤️
