### ISSUE TITLE
Idle time based only on application interaction

### ISSUE THREAD

**Issue by ryandbair** [zulip/zulip-desktop#532]
- **Operating System**:
  - [x] Windows
  - [x] Linux/Ubutnu
  - [x] macOS

If a user doesn't interact with the application itself, they are eventually considered idle. The desktop idle time should be used for that instead.

**Comment by akashnimare** [comment]
Oh yes, this feature is in our roadmap. @timabbott this is the same thing we were talking about?

**Comment by timabbott** [comment]
Yes, exactly, setting `activity.new_user_input` (we'll need to do an `electron_bridge` thing for this) based on some system-level information about whether the user is idle.  Not possible on browser, but definitely something we should do on the Electron desktop app.

**Comment by abhigyank** [comment]
There are two levels to this I'd say - 
* If the desktop app is open, then all the servers should be shown online irrespective of that server been opened in last 5 mins (or whatever is the idle time) or not. Currently we don't do this and each server is treated just like a browser tab, and is shown as orange in the rest of the servers if some other server is in focus for more than the idle time.
* If the user is interacting with their desktop , i.e. even if the app is minimized we show them as green in all their servers.

Ideally we should have the second level implemented, but that depends on whether we are able to get that information from electron somehow. However I believe the first level is easily doable with the current level of implementation we have.

**Comment by timabbott** [comment]
Let's start with doing the first -- that will require us to figure out the `electron_bridge` integration to read and set `new_user_input`.  And then we can improve the implementation for the second version once that's working well.

**Comment by abhigyank** [comment]
Since this is solved in https://github.com/zulip/zulip/pull/12003, closing.
