### ISSUE TITLE
Some emoticons not converted to a graphical one

### ISSUE THREAD

**Issue by max-maurice** [zulip/zulip-desktop#536]
---

- **Operating System**:
  - [X] Windows
  - [ ] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
  * Include `;)`, `:D` or `:P` in a message and send it by pressing Enter.
- **Relevant error messages and/or screenshots**:
  * The displayed message shows the emoticons in plain text, instead of being converted to a graphical emoticon.

**Comment by max-maurice** [comment]
Edited the issue, sorry. The problem wasn't emoticons being at the end of a message but that some emoticons wouldn't get converted at all.

**Comment by HarshitOnGitHub** [comment]
@max-maurice Thanks for reporting! This issue actually belongs to [zulip/zulip](https://github.com/zulip/zulip). This is not a bug, we just don't convert these emoticons to emojis right now. We are in process of updating the list of emoticons, so this will get fixed soon. See discussion here:
https://chat.zulip.org/#narrow/stream/3-backend/subject/emoticons/near/623789
For a list of currently supported emoticons please see:
https://chat.zulip.org/help/enable-emoticon-translations

**Comment by max-maurice** [comment]
@HarshitOnGitHub Ok, thank you!
