### ISSUE TITLE
YouTube videos not playing in app

### ISSUE THREAD

**Issue by Yogislav** [zulip/zulip-desktop#537]
Since 2.3.5 update I cannot play youtube videos in zulip. Whenever someone sends something and I click the thumbnail, whole screen turns black (as it usually was) but player is not visible.

---
- **Operating System**:
  - [X] Windows
  - [ ] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
1. Send any YouTube video;
2. Click on thumbnail;
3. Stare at black screen;

**Comment by abhigyank** [comment]
Can reproduce on CZO in Ubuntu. Not reproducible on browser, only on the desktop app.

**Comment by timabbott** [comment]
This seems likely related to the click handler overriding for uploaded files logic.

**Comment by timabbott** [comment]
Look for the code around `is_youtube_video` in `static/js/lightbox.js` in the webapp to see how the youtube player is triggered.

**Comment by akashnimare** [comment]
This used to work until the `v2.3.2`. @abhigyank there is some corner case which we missed.

**Comment by Yogislav** [comment]
I believe it worked even until further version. It's only after 2.3.5 update that it stopped working for me.

**Comment by timabbott** [comment]
@akashnimare how does https://github.com/zulip/zulip-electron/commit/6470f5303ffa58444a4ed30c3f252992012ac2b5 resolve this?

**Comment by abhigyank** [comment]
@timabbott  7299cd5 broke this for some reason (it works for all commits before this one). It was due to the sentry module breaking it somehow. Updating sentry to the latest version seems to fix this.

**Comment by timabbott** [comment]
OK, cool; you should definitely be putting that context in the commit message!
