### ISSUE TITLE
Double click on tray icon doesn't lead to app window restore.

### ISSUE THREAD

**Issue by winmasta** [zulip/zulip-desktop#538]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu Mint 18.3
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Close app window so it folds to tray icon.
Double click on icon and nothing happens.
I can restory window only by clicking on tray icon with right mouse button and then clicking on "Focus" with left mouse button. I believe there should be an ability to restore app window by double clicking on tray icon.

**Comment by abhigyank** [comment]
Hello @winmasta Currently this behavior is limited to windows and not supported in other OS. There is an open PR #529, but we aren't sure if electron actually supports it in all environments of Linux.

**Comment by akashnimare** [comment]
This has been added in https://github.com/zulip/zulip-electron/pull/529.
