### ISSUE TITLE
Make Windows App 'Close-to-Tray'

### ISSUE THREAD

**Issue by Katylar** [zulip/zulip-desktop#550]
Hi!

Right now, the app closes-to-tray which is great. My questions is is there any way to make it 'minimize-to-tray' as well?

Windows 10.

Thanks!

**Comment by akashnimare** [comment]
@Katylar what do you mean by 'minimize-to-tray' here? Can you attach a screenshot of how it would look?

**Comment by akashnimare** [comment]
There is a "Start Minimized" setting if you want to start the app in the minimize state -

![image](https://user-images.githubusercontent.com/2263909/44849851-0c2b8880-ac79-11e8-8b4e-49330ed910a6.png)

**Comment by zingmars** [comment]
I think what he meant was that right now the app will close to tray if you use the close button (the one in the title bar). An alternative to this would be minimising to tray if you press the minimise button, while the exit button would exit the Zulip client completely. As an example, qBittorrent has this - 
![image](https://user-images.githubusercontent.com/917126/45952477-d7101d00-c00f-11e8-8986-1562def6315b.png)

**Comment by akashnimare** [comment]
>  while the exit button would exit the Zulip client completely

This behaviour used to exist in the earlier versions of the desktop app but from the feedback we received over the time, users want to have the app in the notification area on clicking the `X`/close button and this is why we changed the flow. We can revisit this if more people are interested in the behaviour you mentioned.
