### ISSUE TITLE
link to narrow opens in browser, no way to open it in app

### ISSUE THREAD

**Issue by glyph** [zulip/zulip-desktop#556]
---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubutnu
  - [x] macOS
- **Clear steps to reproduce the issue**:

- I click on `https://<mydomain>.zulipchat.com/login/#narrow/stream/<stream-id>-<stream>/subject/<topic>/near/<message-id>`
- It opens in my browser, which is not logged in to Zulip, because I use the app
- There's nowhere for me to paste this link in the app, so I just search for some terms that might be in the message I'm looking for

**Comment by akashnimare** [comment]
@glyph Can you reproduce this on https://chat.zulip.org ?

**Comment by akashnimare** [comment]
BTW, I can't reproduce this on `*.zulipchat.com` server also. Make sure you're on the latest release i.e. [v2.3.6](https://github.com/zulip/zulip-electron/releases/tag/v2.3.6).

**Comment by abhigyank** [comment]
@akashnimare  I think glyph means that if someone sends this link to him, he cannot open this link in the app. He doesn't  mean that clicking this link in app opens the browser.

**Comment by glyph** [comment]
> @akashnimare I think glyph means that if someone sends this link to him, he cannot open this link in the app. He doesn't mean that clicking this link in app opens the browser.

Yep! That is exactly what I meant.

**Comment by glyph** [comment]
FWIW I am on v2.3.7-beta but this has been an issue for as long as I can remember.

**Comment by abhigyank** [comment]
@glyph @akashnimare  I think if we implement #470, that'd directly solve this issue. 
@glyph Till then a possible workaround is - in the app, send this link as a private message to yourself and then click on the link. This will then open the message. :)

**Comment by glyph** [comment]
@abhigyank Thanks, this workaround is really helpful! :)

**Comment by akashnimare** [comment]
The workaround mentioned above is what we have been using so far.

> I click on https://<mydomain>.zulipchat.com/login/#narrow/stream/<stream-id>-<stream>/subject/<topic>/near/<message-id>

@glyph so whenever someone sends you this kinda link you want to open them in the Zulip app, right? Do you know how other apps handle this?

**Comment by glyph** [comment]
> @glyph so whenever someone sends you this kinda link you want to open them in the Zulip app, right? Do you know how other apps handle this?

on macOS,

1. register a custom URL scheme, as specified in #470 
2. add a link to every page on `*.zulipchat.com` that says "open in app"

on iOS,

1. use "universal links" https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

**Comment by akashnimare** [comment]
@glyph thanks for the detailed info. I'm merging this issue in the #470. 

> register a custom URL scheme, as specified in #470

Yeah, for the starting I think we could just register a protocol so that user can open the zulip app using `zulip://open`.

> add a link to every page on *.zulipchat.com that says "open in app"

I think we don't have such links. Can you point me to those?

**Comment by glyph** [comment]
> I think we don't have such links. Can you point me to those?

I just mean the login page that you’d get by visiting a link such as the one in the description needs a zulip:// link on it to make it easy for users to go from browser to app.

**Comment by hraftery** [comment]
> Do you know how other apps handle this?

Trello has a "Paste URL & Go" menu option (together with a corresponding copy current URL and keyboard shortcuts) so you can navigate to a URL that you copy from somewhere. I used it heavily and it was a fine solution for me, but yeah a custom URL scheme is the gold standard.

The [workaround](https://github.com/zulip/zulip-desktop/issues/556#issuecomment-418965336) is effective and only a bit cumbersome. Plus it kinda gives you a list of bookmarks as a side-effect! Great to have it.

But yeah, we pass around Zulip URLs a lot and it's frustrating that you can _get_ them from the app but not _put_ them.

**Comment by pranav-dubey-cl** [comment]
> @glyph @akashnimare I think if we implement #470, that'd directly solve this issue. @glyph Till then a possible workaround is - in the app, send this link as a private message to yourself and then click on the link. This will then open the message. :)

instead of dm'ing (if it feels like spamming and if you are a person like me who used dm's to himself to store interesting articles todo's and bunch of other things.) Just paste in chat box and go to preview, click and voila.

**Comment by nomeata** [comment]
Related: https://github.com/zulip/zulip-desktop/issues/1219
