### ISSUE TITLE
add custom title bar

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#559]
This is a feature request. 

VSCode has released a custom title bar and right-click menus that also fully support it's dark theme. 

This is probably a low priority request but it would look really nice in Zulip-Electron as well, to have a custom title bar that can go dark (together with the night theme of Zulip web app). 

It would also go well with the dark sidebar.

**Comment by akashnimare** [comment]
This is tricky and requires few hacks since electron doesn't provide any api for this. To have the custom titlebar we need to make a frameless window first and then after building the control buttons (close, minimize etc) on our own, we need to handle their events as well.

**Comment by penCsharpener** [comment]
sure, just google this: 
[from stackoverflow](https://stackoverflow.com/questions/35660043/how-to-customize-the-window-title-bar-of-an-electron-app#35664860)

This repo might help: 
https://github.com/connors/photon

**Comment by akashnimare** [comment]
CSS is not hard the part here. Handling the custom titlebar and its events are the most tricky thing. Also, we need a solution which works on all the platform, not just macOS.

**Comment by kanishk98** [comment]
I think this is an interesting idea. I personally like the new title bar on VS Code a lot. 
@akashnimare if you're okay with the idea, I can have a look at how Microsoft did that and try implementing one for Zulip over the next few days.

**Comment by akashnimare** [comment]
@kanishk98 yeah, feel free to work on this (but I would prefer we should first fix the high priority issues)

**Comment by abhigyank** [comment]
@penCsharpener Title bar and right click menus support dark theme now. You may test in the latest beta release.

@akashnimare This can probably be closed.
