### ISSUE TITLE
How to call the network reconnect modal

### ISSUE THREAD

**Issue by pranshuchittora** [zulip/zulip-desktop#579]
---

- **Operating System**:

  - [x] Linux/Ubutnu

- **Clear steps to reproduce the issue**:
When there is no network, this :point_down:  modal pop-up to notify the user.
![screenshot from 2018-10-05 03-02-30](https://user-images.githubusercontent.com/32242596/46504453-9acc9000-c84b-11e8-86e0-5b60bf98099b.png)
I am not able to find the source code of this modal.
Pls help

**Comment by akashnimare** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron, codebase related should be directed to the community i.e. http://chat.zulip.org.
(That modal is coming from the webapp https://github.com/zulip/zulip)
