### ISSUE TITLE
settings: Change get beta update option on updating enable update setting

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#585]
If the `Enable auto updates` option is disabled then we should disable the beta updates option also. 
This case is already handled in the backend so even if the beta option is enabled and the auto-update option is disabled, the auto-updates won't work. We just need to make changes in the frontend.

**Comment by kanishk98** [comment]
@zulipbot claim

**Comment by kanishk98** [comment]
Okay, looks like ZulipBot has run into a problem. 
Regardless, I've looked into the issue, and I think I've solved the problem. Changed the 
`clickHandler()` in `autoUpdateOption()` in `app\renderer\js\pages\preference\general-section.js` to the following block:

```
clickHandler: () => {
	const newValue = !ConfigUtil.getConfigItem('autoUpdate');
	ConfigUtil.setConfigItem('autoUpdate', newValue);
	if (!newValue) {
		ConfigUtil.setConfigItem('betaUpdate', false);
		this.betaUpdateOption();
	}
	this.autoUpdateOption();
```
@akashnimare can you please have a look at this solution and tell me if I'm missing something before I submit a PR?

**Comment by akashnimare** [comment]
GitHub is down right now so the comments are not being shown in the GitHub
(replying through the email). I would suggest playing with the solution locally
and testing if the values are getting updated as expected.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/pull/586.
