### ISSUE TITLE
OSX "Look Up" is misaligned

### ISSUE THREAD

**Issue by strob** [zulip/zulip-desktop#597]
---

- **Operating System**:
  - [x ] macOS
- **Clear steps to reproduce the issue**:

1. "Force Touch" on any word in a chat or right click and select "Look Up"

2. The pop-up displays the correct definition, but the text is weirdly offset and selections get all sorts of out-of-whack

- **Relevant error messages and/or screenshots**:

<img width="441" alt="screen shot 2018-11-19 at 8 59 37 am" src="https://user-images.githubusercontent.com/208551/48722697-7fd69500-ebd9-11e8-9598-35b8dbf92709.png">

<img width="418" alt="screen shot 2018-11-19 at 8 57 16 am" src="https://user-images.githubusercontent.com/208551/48722555-253d3900-ebd9-11e8-8734-a84e12656407.png">

<img width="801" alt="screen shot 2018-11-19 at 8 50 48 am" src="https://user-images.githubusercontent.com/208551/48722518-0e96e200-ebd9-11e8-9c3f-2116f03b7332.png">

**Comment by akashnimare** [comment]
@strob can you reproduce this in chrome or in some other app?

**Comment by strob** [comment]
Chrome and other apps (including other Electron apps) work fine; it seems like there's a [known issue](https://github.com/electron/electron/issues/4772) with Electron, but some Electron projects seem to get it working.

**Comment by akashnimare** [comment]
> but some Electron projects seem to get it working.

@strob can you name a few?

**Comment by strob** [comment]
Well, Slack for instance...

<img width="394" alt="Screen Shot 2019-03-19 at 11 53 04 AM" src="https://user-images.githubusercontent.com/208551/54633565-a7c9ee00-4a3d-11e9-87f3-8bbc4d320798.png">

**Comment by akashnimare** [comment]
This is how it looks on my macOS -
![image](https://user-images.githubusercontent.com/2263909/54634139-8f8eb900-4aa7-11e9-905b-11bee020a2a5.png)

**Comment by strob** [comment]
Looks like it’s working for you!

I can confirm that Zulip 2.3.82 on macOS 10.14.3 still exhibits “Look Up” offset issues for me.

**Comment by akashnimare** [comment]
@strob can you please try to update to the beta version which is v2.5.0-beta and see if this works as expected? Follow the steps -
* Turn on get beta updates option from setting 
* Restart the app
* You'll get an update popup - choose **install later** and restart.
* Check if the problem still exists.

**Comment by strob** [comment]
The issue is addressed for me in v2.5.0-beta!

I will say that upgrading to beta was anything but smooth. It took >5 restarts and >10 dialogs. This was the scariest one I saw:

<img width="423" alt="Screen Shot 2019-03-19 at 12 14 04 PM" src="https://user-images.githubusercontent.com/208551/54635314-16f51180-4a41-11e9-8cd9-5553f703bd00.png">

**Comment by akashnimare** [comment]
Good to know this worked. Yeah, the updater thing broke in last stable release which we fixed in the current beta version :)
