### ISSUE TITLE
Add context menu in left sidebar's server tab

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#599]
We should show the menu options when the user right clicks on the added zulip servers in the left sidebar. We could add multiple items there but for now, adding a `Delete` option which basically removes that org from the app.

**Comment by kanishk98** [comment]
@zulipbot claim

**Comment by kanishk98** [comment]
@akashnimare I picked this up right now, and I was able to get the required context menu. However, when I click on 'Delete', there's no immediately visible action, even though I can confirm that the `removeDomain()` function is getting called. If I kill the app and relaunch it, the organisation is deleted. 

Here's what I'm doing in `app/renderer/js/main.js`:

```
                const $serverImgs = document.querySelectorAll(".server-icons");
		$serverImgs.forEach(($serverImg, index) => {
			$serverImg.addEventListener("contextmenu", e => {
				e.preventDefault();
				const template = [
					{
						label: "Delete organization",
						click: () => {
							DomainUtil.removeDomain(index);
						}
					}
				];
				const contextMenu = Menu.buildFromTemplate(template);
				contextMenu.popup(remote.getCurrentWindow());
			});
			if ($serverImg.src.includes("img/icon.png")) {
				this.displayInitalCharLogo($serverImg);
			}
			$serverImg.addEventListener("error", () => {
				this.displayInitalCharLogo($serverImg);
			});
		});
```

I checked the code used in `server-info-form.js` to delete a domain, and there seems to be some `onChange()` method that's causing the immediate reload we want. 
I'm not sure on how to implement that here, and would love some help.

**Comment by akashnimare** [comment]
This looks good. Maybe reuse the following function -
```js

		this.$deleteServerButton.addEventListener('click', () => {
			dialog.showMessageBox({
				type: 'warning',
				buttons: ['YES', 'NO'],
				defaultId: 0,
				message: 'Are you sure you want to disconnect this organization?'
			}, response => {
				if (response === 0) {
					DomainUtil.removeDomain(this.props.index);
					this.props.onChange(this.props.index);
				}
			});
		});
```
You could also try to reload the app using -
```
click: () => {
		DomainUtil.removeDomain(index);
                ipcRenderer.send('reload-full-app');
	}
```

**Comment by kanishk98** [comment]
@akashnimare works now, thanks. :)
I have another question, though. When the organization is removed and a new one is added, the app does not enter the `forEach` loop referenced in the above comment on first run. I have to restart the app or hit `Ctrl + R` for the loop to work again. 

Is this expected behaviour or should I dig deeper in case this is a bug?

**Comment by akashnimare** [comment]
Yeah, reloading is needed in that case. I'm hoping this will be improved in #496.

**Comment by akashnimare** [comment]
> I have another question, though. When the organization is removed and a new one is added, the app does not enter the forEach loop referenced in the above comment on first run. I have to restart the app or hit Ctrl + R for the loop to work again.
Is this expected behaviour or should I dig deeper in case this is a bug?

Okay, there is fix for this. The code for context menu is in the `initActions()` which only gets executed when you first load the app. So there are couple of options to make it work 

a) Execute `initActions()` on reloading the view 
```

	reloadView() {
		// Save and remember the index of last active tab so that we can use it later
		const lastActiveTab = this.tabs[this.activeTabIndex].props.index;
		ConfigUtil.setConfigItem('lastActiveTab', lastActiveTab);

		// Destroy the current view and re-initiate it
		this.destroyView();
		this.initTabs();
		this.initActions();
	}
```

b) Extract the following code and make a new function + execute it on first loading the app + on reload -
```js


const $serverImgs = document.querySelectorAll('.server-icons');
		$serverImgs.forEach(($serverImg, index) => {
			$serverImg.addEventListener('contextmenu', e => {
				e.preventDefault();
				const template = [
					{
						label: 'Disconnect organization',
						click: () => {
							dialog.showMessageBox({
								type: 'warning',
								buttons: ['YES', 'NO'],
								defaultId: 0,
								message: 'Are you sure you want to disconnect this organization?'
							}, response => {
								if (response === 0) {
									DomainUtil.removeDomain(index);
									ipcRenderer.send('reload-full-app');
								}
							});
						}
					}
				];
				const contextMenu = Menu.buildFromTemplate(template);
				contextMenu.popup({ window: remote.getCurrentWindow() });
			});
			if ($serverImg.src.includes('img/icon.png')) {
				this.displayInitalCharLogo($serverImg);
			}

			$serverImg.addEventListener('error', () => {
				this.displayInitalCharLogo($serverImg);
			});
		});

```
