### ISSUE TITLE
ctrl-S hotkey isn't documented properly

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#606]
Built from master on Linux, I thought the the ctrl+S hotkey wasn't working, but actually you need ctrl+shift+s.  We should update the docs to clarify that (in general, best practice is to indicate capitalization via an explicit shift in hotkey docs, because often similar documentation will unconditionally capitalize key names, similar to how they are displayed on a keyboard)

**Comment by abhigyank** [comment]
Which docs are you referring to? It is ctrl+shift+S on the keyboard's shortcut list inside the desktop app.

**Comment by timabbott** [comment]
Oh, I mean this thing: 
![image](https://user-images.githubusercontent.com/2746074/49476567-3720fd80-f7cf-11e8-9e5c-4fa3c07db7f9.png)
