### ISSUE TITLE
"Organizations" page should probably have a direct link to "add a new organization"

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#607]
It feels weird that the only thing we have at the bottom of this is to upload a custom certificate:

![image](https://user-images.githubusercontent.com/2746074/49476606-5586f900-f7cf-11e8-9bc5-75c11d61b969.png)

**Comment by akashnimare** [comment]
@rishig @timabbott does something like this work

![image](https://user-images.githubusercontent.com/2263909/49506367-e929f980-f8a3-11e8-812d-ae42771048ed.png)

<img src="https://cl.ly/64ec9dbe091b/download/Screen%20Recording%202018-12-05%20at%2003.40%20PM.gif">

**Comment by akashnimare** [comment]
![image](https://user-images.githubusercontent.com/2263909/49506887-45414d80-f8a5-11e8-861d-4c303219dc51.png)

**Comment by timabbott** [comment]
Yeah, that link mechanism is great.  Though I think we should put "Add a new organization" above "Add Custom Certificates", since it's the more common use case?  We might want to change its structure to be a button rather than a link so that it looks nice in that position.  What might look nicest is to style it like a white bar of similar size to the existing connected organizations, with just "Add a new organization" as the text in the middle, but I'm not sure.

**Comment by akashnimare** [comment]
Correct, that would look good.

![image](https://user-images.githubusercontent.com/2263909/49529899-0d55fc80-f8dd-11e8-894e-d7278e01b0a7.png)

**Comment by rishig** [comment]
Let's call this "Add an organization"? The "new" makes it feel like you're going to be creating an organization.

**Comment by timabbott** [comment]
I think "Connect to another organization" would be more consistent with what we call it on the next page.

**Comment by rishig** [comment]
yeah, sounds good

**Comment by akashnimare** [comment]
Cool, pushed the changes.
