### ISSUE TITLE
Set User-Agent when using request

### ISSUE THREAD

**Issue by priyank-p** [zulip/zulip-desktop#611]
Currently whenever we using `request` module to add server it does not set `User-Agent` to the zulip server. We should be setting a proper `User-Agent` when sending a request.

The `User-Agent` should be from [`system-util.js`](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/system-util.js#L51) where there is work done previously to have proper `User-Agent`.

Refs: https://github.com/zulip/zulip/pull/10971

**Comment by abhigyank** [comment]
I think this should be done after implementing #603. Can be done before too, but would be much more simple after #603 is closed.

**Comment by akashnimare** [comment]
Okay, so far @priyank-p and I have tried this but no luck -

```sh
diff --git a/app/renderer/js/utils/domain-util.js b/app/renderer/js/utils/domain-util.js
index 8e0b3f3..742677c 100644
--- a/app/renderer/js/utils/domain-util.js
+++ b/app/renderer/js/utils/domain-util.js
@@ -12,6 +12,8 @@ const Logger = require('./logger-util');
 const CertificateUtil = require(__dirname + '/certificate-util.js');
 const ProxyUtil = require(__dirname + '/proxy-util.js');
 const ConfigUtil = require(__dirname + '/config-util.js');
+const SystemUtil = require(__dirname + '/../utils/system-util.js');
+
 
 const logger = new Logger({
 	file: `domain-util.log`,
@@ -108,6 +110,9 @@ class DomainUtil {
 			return Promise.reject('This server has been added.');
 		}
 
+
+		// console.log(SystemUtil.getUserAgent());
+
 		domain = this.formatUrl(domain);
 
 		const certificate = CertificateUtil.getCertificate(encodeURIComponent(domain));
@@ -130,7 +135,8 @@ class DomainUtil {
 			url: domain + '/static/audio/zulip.ogg',
 			ca: (certificateLocation) ? certificateLocation : '',
 			proxy: proxyEnabled ? ProxyUtil.getProxy(domain) : '',
-			ecdhCurve: 'auto'
+			ecdhCurve: 'auto',
+			headers: { 'User-Agent': SystemUtil.getUserAgent() }
 		};
 
 		const serverConf = {
@@ -221,7 +227,8 @@ class DomainUtil {
 			url: domain + '/api/v1/server_settings',
 			ca: (certificateLocation) ? certificateLocation : '',
 			proxy: proxyEnabled ? ProxyUtil.getProxy(domain) : '',
-			ecdhCurve: 'auto'
+			ecdhCurve: 'auto',
+			headers: { 'User-Agent': SystemUtil.getUserAgent() }
 		};
 		return new Promise((resolve, reject) => {
 			request(serverSettingsOptions, (error, response) => {

```


![image](https://user-images.githubusercontent.com/2263909/50044704-b8b93b00-00ad-11e9-8c09-5caca5a7525b.png)

**Comment by akashnimare** [comment]
This fixes the realm icon issue some users are having but I'm not sure if this fixes https://github.com/zulip/zulip/pull/10971 since it stil says (`unauth via ?`)

**Comment by timabbott** [comment]
@akashnimare just to make sure -- you're running against a latest master Zulip dev server?  Because before roughly #10971, that endpoint always said "unauth via ?"...

**Comment by akashnimare** [comment]
No, I was a bit behind. On master -

![image](https://user-images.githubusercontent.com/2263909/50175712-8f094980-0323-11e9-82d4-b308570f643c.png)

**Comment by timabbott** [comment]
OK, great, sorry I should have mentioned that I added support for that logging as part of working on #10971.

**Comment by akashnimare** [comment]
Thanks, everyone 🚀
