### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gregzil** [zulip/zulip-desktop#622]
I am working on Windows 10 ,and specifically the Zulip Desktop v2.3.82,
By going to "Tools"/ "Toggle DevTools for Zulip App", after a while, a Internal server error appeared.
![zulip error](https://user-images.githubusercontent.com/45594372/50728139-ef72f600-112d-11e9-87a4-9b8d05d70709.jpg)

**Comment by timabbott** [comment]
This is a problem with your server, not with the app.  You should ask the server administrator to look at their error logs to see what's wrong.  (Does this happen consistently when using the developer tools?  It seems possible the timing was just random chance).
