### ISSUE TITLE
Reply from notification is broken

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#624]
![image](https://user-images.githubusercontent.com/2263909/50812343-6a0f6180-1338-11e9-9c52-00dae93a46b6.png)

This is due to the change in the webapp's codebase.

https://chat.zulip.org/#narrow/stream/9-issues/topic/reply.20from.20notification/near/679802

**Comment by priyank-p** [comment]
For the fix, 3e73511, we also want to make sure we maintain backward compatibility.
So we should have added a check like `const narrowToTopic = narrow.by_subject || narrow.by_topic;`

Also I don't think the upstream change is in any stable release yet for webapp so the fix is actually be breaking.
