### ISSUE TITLE
Incorrect Focus after Switching Realms

### ISSUE THREAD

**Issue by punchagan** [zulip/zulip-desktop#634]
Running on the latest master. 
When I switch between Realms, I have to click to change focus to the new realm.  To reproduce, 

- add two (or more) realms to Zulip electron
- open compose box in the first realms
- switch to the second realm using the short cut key (Ctrl + 2)
- try using navigation shortcuts - n, j, k, etc. Notice that things don't work! 
- Click on the "page" to bring it into focus. Try the navigation shortcuts now. 
- switch back to the first realm (Ctrl + 1)
- Notice all the previously tried shortcuts typed out in the compose box.

**Comment by akashnimare** [comment]
@priyank-p is this the same bug we fixed last year?

**Comment by priyank-p** [comment]
I can't remember exactly but I think I fixed the focus related thing two times: (1) handling focus changes from the settings tab (2) handling focus correctly for notification feature.

**Comment by punchagan** [comment]
This issue seems related: https://github.com/electron/electron/issues/15718

**Comment by punchagan** [comment]
> This issue seems related: [electron/electron#15718](https://github.com/electron/electron/issues/15718)

Based on this discussion I found a [work around that I pushed here](https://github.com/punchagan/zulip-electron/commit/ed2046f73dd56eb18fddabdef111c7fee4831d11). Let me know if that looks reasonable to you.  @akashnimare @priyank-p

**Comment by priyank-p** [comment]
I think the work around is fine given that we call focus after we call blur. I would add a comment and link to issue for that link so we can later take care of it when it gets fixed upstream.

**Comment by punchagan** [comment]
Thanks @priyank-p. Opened #639 as a fix.
