### ISSUE TITLE
Can't run Travis checks locally [Windows]

### ISSUE THREAD

**Issue by kanishk98** [zulip/zulip-desktop#636]
Since the `scripts/` folder only contains `.sh` files, Zulip contributors developing on Windows cannot check their commits for Travis errors before pushing. This slows them down and makes work harder for the maintainers too. 

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS

- **Clear steps to reproduce the issue**:
Run `$ npm run travis` from within your Zulip directory on a Windows machine. The machine will try to run a `.sh` file and fail. 

- **Suggested solution**:
Since [Windows is now supported as a build environment](https://docs.travis-ci.com/user/reference/windows/), we can write a `.cmd` or `.bat` file for Windows systems.

**Comment by kanishk98** [comment]
I'd like to work on this issue as well. 
@zulipbot claim

**Comment by priyank-p** [comment]
@kanishk98 for running tests on Windows CI, you should just try to run `npm test` that will run lint and then you can try and see if `npm run test-e2e` work out of the box for windows.

The current `scripts/travis-build-test.sh` just starts the `xvbf` service that allows running electron test (the e2e tests) on CI, Its not even possible to install on windows and possibly there is no need to.

For other stuff that the issue might concern, we already have bash script that are useful ported to work on windows look at `tools/reinstall-node-modules` and others in `tools/` directory.

**Comment by kanishk98** [comment]
@priyank-p thanks a ton for telling me about this. 
I agree that if there's already a facility for testing the app using `npm run test-e2e`, there's no need for setting up another build environment on Travis. 
I do have some questions (and suggestions) relating to Windows compatibility regarding the `npm test` and `npm run test-e2e` commands, but I suppose those can be taken up in the message boards.
