### ISSUE TITLE
Spellcheck randomly breaks, or possibly unknown language change

### ISSUE THREAD

**Issue by amahoneyLIT** [zulip/zulip-desktop#646]
- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
  - Unknown, multiple users in our organization have experienced the issue appear and then resolve itself
- **Relevant error messages and/or screenshots**:
![spellcheck problem](https://user-images.githubusercontent.com/38052592/52451432-d6c27b00-2af3-11e9-801c-fd783b7037ed.png)
![suggested words](https://user-images.githubusercontent.com/38052592/52451770-31a8a200-2af5-11e9-8dad-394548836d1a.png)
---

We are testing zulip in our organization. Two users have reported this problem, with unknown steps to reproduce.

**Comment by timabbott** [comment]
@amahoneyLIT thanks for the report!  If you can figure out a reproducer, that'd be super helpful. 

@akashnimare we should debug this, but it's possible we should also add an option in "spellchecker language" of "None" to disable the feature, so there's a workaround (both for bugs like this, which we should hopefully expunge, but also for any other spellchecker issue)

**Comment by akashnimare** [comment]
We do have the option to disable this feature - 

![image](https://user-images.githubusercontent.com/2263909/52519432-40bc5b00-2c81-11e9-8a58-d205b4dbeab9.png)

Adding an option to choose the spellchecker language is in our roadmap.  

- * Unknown, multiple users in our organization have experienced the issue appear and then resolve itself

Resolve itself thing is weird here since if it's not working then the issue should be persisted.

**Comment by akashnimare** [comment]
@amahoneyLIT can you please tell me which version of the desktop app you folks are using?

**Comment by kanishk98** [comment]
@amahoneyLIT we've released a new version of our [desktop app](https://zulipchat.com/apps). Please install this app and let us know if the spellchecker works in this version.

**Comment by amahoneyLIT** [comment]
@akashnimare  Checking the version of the desktop app I had, it says v2.3.82
@kanishk98 our organization has just stopped using Zulip, so I won't have the opportunity to test this out.

**Comment by akashnimare** [comment]
This should work as expected in v3.0.0. Please reopen if it occurs again.
