### ISSUE TITLE
Not able to install the Zulip Desktop App in Ubuntu 18.04

### ISSUE THREAD

**Issue by irahulcse** [zulip/zulip-desktop#648]
After installing the app from the snap package with code(sudo snap zulip). When I am trying to open the app it is not opening and also I am not able to reinstall the app again. Is there is any way of uninstalling the app completely from the system and then reinstall it from cmd. As it had happened to me previously also when the Zulip app was not able to work properly.
The app is showing in the app tray but it is still not working.
![Not able to open the app](https://user-images.githubusercontent.com/34218254/52388968-e7a0cb80-2ab6-11e9-82da-e7b5b2cb130a.png)

**Comment by abhigyank** [comment]
Snap has an issue in Ubuntu 18.04. See #593, #628
You can use the AppImage version. That should work.

P.S. This is a duplicate issue, we can close.

**Comment by akashnimare** [comment]
@irahulcse the issue has been fixed in the latest beta. Can you install and check if this works for you -
```
sudo snap install zulip --beta

```
