### ISSUE TITLE
the keyboard shortcuts dialog is not shown when outside of a workspace

### ISSUE THREAD

**Issue by matrixise** [zulip/zulip-desktop#651]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Use the last version of the Electron client 2.3.82

For example, you click on the button "Add Organization" and you can't show the dialog with the keyboard shortcuts with Ctrl+Shift+K or via the "File" menu.

**Comment by abhigyank** [comment]
The keyboard shortcuts are only relevant when an organization (workspace) is open and in focus and hence can't be shown in other windows. In fact, the Keyboard Shortcut option in File menu should be grayed out in other windows.

**Comment by matrixise** [comment]
+1

**Comment by abhigyank** [comment]
@akashnimare This can be closed I guess. It's an expected behaviour.
