### ISSUE TITLE
Indicator for "Do Not Disturb"

### ISSUE THREAD

**Issue by matrixise** [zulip/zulip-desktop#660]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
- **Relevant error messages and/or screenshots**:

In the Electron version, we have the option "Toggle Do Not Disturb", but when we click on this menu item, there is no indicator, because I don't know if I am in mode "Do Not Disturb" or not.

**Comment by rhythm-sharma** [comment]
I want to claim

**Comment by akashnimare** [comment]
@matrixise the DND indicator is there in the left sidebar. 

Normal mode -

![image](https://user-images.githubusercontent.com/2263909/53625333-d2880a00-3c28-11e9-9123-514aa716a550.png)

DND mode - 

![image](https://user-images.githubusercontent.com/2263909/53625354-de73cc00-3c28-11e9-805a-254148fa93b3.png)
