### ISSUE TITLE
No Right Click context menu on centos7 linux

### ISSUE THREAD

**Issue by ghost** [zulip/zulip-desktop#662]
Centox 7.4/7.5 Linux v2.3.82

Using the app image, there is no right click context menu, so there's no way to copy a stream/topic URL like #15 added.

This is confirmed working in the OSX app.

**Comment by abhigyank** [comment]
This works for me on Ubuntu 16.04, should could be specific to Centos as well.
@swallitsch  We had one such report recently for Windows, but that was fixed by re-installing the client. Maybe you could try re-installing the client once and see if that works for you.

**Comment by ghost** [comment]
This was reported by multiple users across our org, all using the latest app image.

I just did a fresh install of vanilla Centos7 and Gnome 3 and confirmed that there is no right click context menu using chat.zulip.org.

**Comment by abhigyank** [comment]
@akashnimare Can you figure our why is this being caused? I can't seem to find an issue upstream. Maybe due to electron update?

**Comment by akashnimare** [comment]
@abhigyank might be related to the broken spellcheck module.

**Comment by akashnimare** [comment]
@swallitsch can you reproduce this issue in v2.5.0-beta? Steps -
* Run v2.3.82
* Turn on the beta updates option from setting
* Restart app
* The app should be able to auto-update
* Check if the right click works

**Comment by ghost** [comment]
Upgraded to 2.5.0-beta on centos7. Confirmed running 2.5.0-beta.

Right click is still non-functional.

**Comment by akashnimare** [comment]
@swallitsch okay, does the spellcheck work?

**Comment by ghost** [comment]
Nope- no red underline or anything.

![image](https://user-images.githubusercontent.com/32879218/57029283-1d58da80-6bf6-11e9-976d-faa7ced36efe.png)

vs web app

![image](https://user-images.githubusercontent.com/32879218/57029294-2a75c980-6bf6-11e9-8ad9-ffe4ccfb8219.png)

**Comment by akashnimare** [comment]
Looks like the spellchecker module is broken on centos7. Did it work in previous versions (spellchecker + right click)?

**Comment by ghost** [comment]
Since zulip is an electron app, it was not possible to run in previous versions of centos or rhel.

**Comment by ghost** [comment]
Still occurring in 3.0.0

**Comment by abhigyank** [comment]
We should open an upstream issue in Electron regarding this issue as this is a Centos specific issue and we don't have much to do here to fix this. There seems no existing issue nor can I find any explicit docs for Centos regarding right click context issue.

**Comment by ghost** [comment]
Understood, would it be worth investigating electron apps without this issue? Postman for example still has a right click menu

**Comment by akashnimare** [comment]
Okay, let me install Centos and debug this issue.

**Comment by Avi-D-coder** [comment]
Same issue (no right click or spellcheck) with flatpak on Arch Linux.

**Comment by manavmehta** [comment]
@swallitsch @Avi-D-coder can you test on the latest master?
We jushed pushed some changes which can resolve this. :)

**Comment by Avi-D-coder** [comment]
Unfortunately I can't, since I don't have flatpak build tools set up.

**Comment by ghost** [comment]
Sorry, I'm not setup to build node packages :(

**Comment by akashnimare** [comment]
@swallitsch no issues, we'll soon push a new release.

**Comment by akashnimare** [comment]
@swallitsch @Avi-D-coder can you reproduce this issue on the latest release which is v5.3.0?
Also, check if spellchecker works as expected.

**Comment by ghost** [comment]
Latest release (4.3.0) isn't working for unfortunately:

> SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. Please make sure that /tmp/.mount_Zulip-blah/chrome-sandbox is owned by root and has mode 4755
[1] 65374 trace trap (core dumped) ./Zulip-5.3.0-x86_64.AppImage

Probably due to me still being on Centox 7.4/7.5 Linux v2.3.82

**Comment by abhigyank** [comment]
Could you remove the v2.3.82 and try installing? We have long deprecared v2.3.82, and updates don't roll out to this version anymore. We did fix the SUID sandbox issue on debian in our previos release.

**Comment by ghost** [comment]
Sorry that was a copy paste error- I'm launching Zulip-5.3.0-x86_64.AppImage

**Comment by abhigyank** [comment]
@andersk We did fix this issue, could you look at it?

**Comment by Avi-D-coder** [comment]
The update is not on flathub yet
