### ISSUE TITLE
persistent Page not found (404) error

### ISSUE THREAD

**Issue by jhellerstedt** [zulip/zulip-desktop#665]
I'm running my own server that's been going through some self-induced nginx configuration upheaval; which has since settled down, and zulip is working fine in browser.  However, the (mac) desktop app has a persistent "Page not found (404)" error, even after removing/ re-adding the organisation, and after deleting the app/ re-downloading to install.

I suspect there is some cache'd information somewhere, but can't seem to easily find documentation about how to do a "deep delete" to get the desktop app working again.

**Comment by akashnimare** [comment]
Try using this option from setting options - 
![image](https://user-images.githubusercontent.com/2263909/53476507-8c9c3c00-3a98-11e9-8fa5-061de83152f2.png)

**Comment by jhellerstedt** [comment]
too classic, failed to scroll down far enough, and see that option

I'll just add that I had to also 'Factory Reset' up in Tools, in addition to hitting Reset App Data, but the combination did the trick.

Thanks @akashnimare !

**Comment by akashnimare** [comment]
@jhellerstedt awesome!

**Comment by jhellerstedt** [comment]
I had the same problem again after getting upgrading server to 3.0 (desktop app version 5.3); I did a Factory Reset combined with manually deleting the directory:
/Users/<user>/Library/Application\ Support/Zulip

And then I was successfully able to re-add the organisation.
