### ISSUE TITLE
Error by clicking Tools\Check for Updates

### ISSUE THREAD

**Issue by ftribrunn** [zulip/zulip-desktop#672]
OS Windows

![image](https://user-images.githubusercontent.com/4007655/53717308-0bf28c80-3e58-11e9-890f-0657b7820d0f.png)

![image](https://user-images.githubusercontent.com/4007655/53717099-67704a80-3e57-11e9-961f-139a716f78cf.png)

**Comment by akashnimare** [comment]
@ftribrunn yes, this is expected; we still have not uploaded the files for Windows. This will be done in a day or two.

**Comment by akashnimare** [comment]
This should work now. @ftribrunn please check again.
