### ISSUE TITLE
Add number of mentions to left bar (organizations)

### ISSUE THREAD

**Issue by rvansa** [zulip/zulip-desktop#678]
In addition to total number of unread messages (red ball) in given organization I'd like to see number of mentions. I currently have 5 organizations in Zulip and I want to prioritize handling conversations in which I am mentioned.

Therefore, I propose adding a blue ball below the red one, stating how many times I've been mentioned/number of alert words.

In addition to that, it would be nice to configure whether the desktop notification icon (Z) show show unread messages or only mentions.

**Comment by marco-m** [comment]
@akashnimare for my understanding: is this ticket closed because the feature is present (if yes, any documentation about it?) or some some other reasons? Thanks.

**Comment by akashnimare** [comment]
> In addition to that, it would be nice to configure whether the desktop notification icon (Z) shows unread messages or only mentions.

@marco-m, @rvansa we have added a new setting in the webapp (Settings > Notifications > Unread count summary) by which you can configure whatever you want to include in left sidebar in the desktop app. Current options are -
* All messages
* Private messages + mentions
* None

![image](https://user-images.githubusercontent.com/2263909/64812510-fc998c00-d5bc-11e9-9ae6-9b1d6381efe6.png)

**Comment by marco-m** [comment]
thanks!
