### ISSUE TITLE
Ctrl+1 showing up below zulip icon

### ISSUE THREAD

**Issue by SankalpSh** [zulip/zulip-desktop#683]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
  + After app login
  + Dashboard icon below zulip icon at left showing ```Ctrl+1```
- **Relevant error messages and/or screenshots**:
![Screenshot from 2019-03-14 09-22-12](https://user-images.githubusercontent.com/37926536/54332354-e2014d00-4643-11e9-80a2-d72eec3524b3.png)

**Comment by SankalpSh** [comment]
I was able to remove that using ```Ctrl+Shift+i``` using dev tools.
Please tell me should i change that and make a pull request.

**Comment by abhigyank** [comment]
We want it to be shown. It is not an issue here.

**Comment by SankalpSh** [comment]
@abhigyank So i will close the issue.
