### ISSUE TITLE
Issues with Ctrl+Tab cycling

### ISSUE THREAD

**Issue by abhigyank** [zulip/zulip-desktop#691]
Follow up issues of #663

* While on the first server, Ctrl+Shift+Tab doesn't work. Should go to last active webview.
* Open settings, start cycling using Ctrl+Tab - while on settings webview, the settings icon the sidebar is not highlighted. Settings icon should be highlighted.

**Comment by vsvipul** [comment]
@zulipbot claim

**Comment by abhigyank** [comment]
On another note, I feel that settings is different webview altogether and should be clubbed with the servers cycling. We should probably limit cycling to only between the servers and not move to the settings view. 
@rishig weigh in here?

**Comment by akashnimare** [comment]
> We should probably limit cycling to only between the servers and not move to the settings view.

Yes, we should exclude cycling to settings.
