### ISSUE TITLE
Message not stored in drafts after quitting

### ISSUE THREAD

**Issue by vsvipul** [zulip/zulip-desktop#696]
When we close the app after typing something in the message box, the message is not saved in drafts.

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS

- **Clear steps to reproduce the issue**:
1. Open up zulip desktop and type a message in the message box. 
2. Don't lose focus on the message box and quit the app using Ctrl+Q.
3. The message is not saved in the drafts.

Same steps reproduced in webapp seem to store the message in drafts perfectly.

- **Relevant error messages and/or screenshots**:
![Screenshot from 2019-04-01 14-28-28](https://user-images.githubusercontent.com/21038781/55316526-3bfb7280-548c-11e9-9bd1-26fb67103b82.png)
![Screenshot from 2019-04-01 14-29-05](https://user-images.githubusercontent.com/21038781/55316520-3736be80-548c-11e9-9090-76c1a8ab44ba.png)
"THIS IS A TEST!!!!!!!!" message is not stored in drafts.

**Comment by vsvipul** [comment]
@zulipbot label "Type: Bug"

**Comment by akashnimare** [comment]
I can't reproduce this on my macOS desktop app. I highly doubt the issue has anything to do with the desktop app since I have seen the draft not being saved issue in webapp a couple of time also though can't reproduce this now.

**Comment by vsvipul** [comment]
@akashnimare i have tested it multiple times and i think it is an existent issue on Ubuntu. @abhigyank can you please test and tell if this is the case for you or not ?

**Comment by timabbott** [comment]
The webapp attempts to save the draft content during close using a `beforeunload` event listener.  My guess is that depending how forcibly you quit the app, that code may or may not get to finish running before the app closes, so this autosave method might not be 100% reliable.

**Comment by rhythm-sharma** [comment]
i can reproduce this on Ubuntu

**Comment by akashnimare** [comment]
@timabbott is there anything we could do for this in the web app?

**Comment by timabbott** [comment]
If we can reproduce this, what I'd try is e.g. adding some sort of logging statement statement in that `beforeunload` to see if it's not being called by the browser, or it's being called but failing.  I guess I'm not sure what the right process there is because one is quitting the app.  

I would also definitely read through these Google results to see if any of the suggestions there help; a few seem potentially relevant but it's hard for me to tell without testing https://www.google.com/search?q=electron+quit+app+beforeunload&oq=electron+quit+app+beforeunload

**Comment by akashnimare** [comment]
@vsvipul can you test this against master? I think https://github.com/zulip/zulip-desktop/pull/783 should fix this.

**Comment by vsvipul** [comment]
@akashnimare will test it right now. Didn't get any notification for this message.

**Comment by vsvipul** [comment]
@akashnimare Works fine for me now. This issue can be closed. Great work @priyank-p !!

**Comment by priyank-p** [comment]
Closing since it's definitely same as #767 and is fixed in master.
