### ISSUE TITLE
Cursor does not focus in Settings box after soft reload (Ctrl/Cmd + R)

### ISSUE THREAD

**Issue by kanishk98** [zulip/zulip-desktop#697]
While on Settings > Organizations, if I reload by pressing Cmd/Ctrl + R, then I'm unable to focus my cursor in the input box. 

The problem goes away when I switch apps and come back to Zulip.

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS

- **Clear steps to reproduce the issue**:

Navigate to Settings > Organizations. Ctrl + R. (Reloading by clicking on the button in the sidebar works as expected). Try to click on the organization URL input box. You won't see a cursor and the input box won't focus as usual. 

- **Relevant GIF**:

![no_focus](https://user-images.githubusercontent.com/24617297/55422233-d47f1900-5598-11e9-9498-49d4d09880e5.gif)

**Comment by vsvipul** [comment]
@zulipbot claim

**Comment by akashnimare** [comment]
A similar issue can be seen on the `/login` page as well where the cursor doesn't focus the email field -

![image](https://user-images.githubusercontent.com/2263909/55427816-7278e080-55a5-11e9-960a-a61bd167d5eb.png)
