### ISSUE TITLE
man-in-the-middle attacks

### ISSUE THREAD

**Issue by santherics** [zulip/zulip-desktop#701]
the Zulip desktop app got "intercepted" by a guest wifi landing page.(I see the landing page instead zulip interface in the desktop app)

Does it mean that it is not safe to man-in-the-middle attacks?

**Comment by abhigyank** [comment]
Not at all. Zulip app uses webviews which are like tabs in a web browser. So if you have a wifi that requires you to login you'd be routed to that login page first in a browser before accessing anything else, same could happen in the desktop app (unless you've already logged in a web browser into the wifi).

**Comment by akashnimare** [comment]
This is the expected behavior. You'll get the same network page in the other apps also.
