### ISSUE TITLE
Issue with config files running on Linux

### ISSUE THREAD

**Issue by NickoftheSouth** [zulip/zulip-desktop#719]
---

- **Operating System**:
  - [*] Ubuntu (18.10)

- Somehow my configuration files have become corrupt on my Ubuntu installation of Zulip.
Even if I uninstall and re-install I'm getting the same error message and the App fails to open.
This may be a generic Electron issue, but if anyone has any idea how to clear the cache I'd appreciate it.
- **The error message when trying to run Zulip from commandline looks like this**:

```
~$ zulip
Fontconfig error: Cannot load default config file
Failed to generate minidump.Segmentation fault (core dumped)
```

**Comment by kanishk98** [comment]
Hello Nick! Thanks for letting us know. 
@vsvipul has a Linux system, he should be able to help you out here. 
It'd also help if you could help us understand why this may have happened. #593 details how Zulip segfaults if downloaded from the Ubuntu Software Center, but the error message there is different.

**Comment by vsvipul** [comment]
>   This may be a generic Electron issue, but if anyone has any idea how to clear the cache I'd appreciate it.

You can clear the cache files from ```/home/user/.config/Zulip``` . Although, i don't think this is an error because of config files.

It seems to be a problem with your Fontconfig. 
Please try removing and reinstalling fontconfig and report back if it works or not. You can refer to the problem [here](https://bugs.launchpad.net/ubuntu/+source/fontconfig/+bug/1259510).

**Comment by akashnimare** [comment]
@NickoftheSouth let us know if the solutions provided above works for you.

**Comment by akashnimare** [comment]
Feel free to re-open this if the above solution doesn't work.
