### ISSUE TITLE
Javascrit error in main process

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#737]
A user reported -
> My brother saw this today when he tried to open the Zulip app. This happened every time he tried to switch to the app. When he quit and relaunched it worked ok.

![image](https://user-images.githubusercontent.com/2263909/57477820-26614000-72b7-11e9-868d-e80d3e6e71eb.png)

https://chat.zulip.org/#narrow/stream/9-issues/topic/JavaScript.20error.20in.20the.20main.20process

**Comment by vsvipul** [comment]
@akashnimare might be a problem with electron, similar issue [here](https://github.com/beakerbrowser/beaker/issues/799) .

**Comment by akashnimare** [comment]
> Nah that warning's about having a lot of event emitter handlers set.
This bug is basically something that electron does temperamentally. 

@vsvipul looks like a similar error which is coming from the electron.

**Comment by kanishk98** [comment]
@akashnimare I think this problem was addressed in #761, right? I haven't seen reports of a similar issue since then.

**Comment by akashnimare** [comment]
Yeah, I think we are good here.
