### ISSUE TITLE
Clicking gnome menu bar entry for zulip does not bring app into focus

### ISSUE THREAD

**Issue by ngoldbaum** [zulip/zulip-desktop#740]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:

Click "zulip" in the gnome menu bar entry for the zulip app. I would expect this to bring the zulip window into focus but it does not.

- **Relevant error messages and/or screenshots**:

![Peek 2019-05-16 15-51](https://user-images.githubusercontent.com/3126246/57882834-a9702200-77f2-11e9-9149-83e48140e16b.gif)

**Comment by kanishk98** [comment]
Yeah, I find this annoying too. :)
I'd be happy to take this up. 

@zulipbot claim

**Comment by akashnimare** [comment]
@kanishk98 this does work in Windows and macOS.

**Comment by kanishk98** [comment]
> @kanishk98 this does work in Windows and macOS.

Yeah, I tested it on both Windows and Linux. Linux (Gnome Desktop) didn't work for me either.

**Comment by akashnimare** [comment]
Works on Ubuntu 16.04 as well. The bug maybe related to platform limitations.

**Comment by abhigyank** [comment]
Works for me on Gnome Desktop in Ubuntu 16.04.
Could be OS/Environment/User_Settings specific.

**Comment by ngoldbaum** [comment]
I’m using Ubuntu 18.04

**Comment by akashnimare** [comment]
@ngoldbaum can you test if v4.0.0 works?

**Comment by ngoldbaum** [comment]
Yay it works, thank you so much for fixing this.

**Comment by akashnimare** [comment]
Awesome!
