### ISSUE TITLE
No spellcheck on Centos7 3.0.0

### ISSUE THREAD

**Issue by ghost** [zulip/zulip-desktop#749]
Linux/Centos7 Zulip App 3.0.0

The spellcheck module does not underline words on Centos7. Possibly related to #662 , but I figured I'd open a separate ticket for this issue.

Centos:
![image](https://user-images.githubusercontent.com/32879218/58347041-9e7c4980-7e11-11e9-9e8b-9eaefc958ffb.png)
webapp on centos:
![image](https://user-images.githubusercontent.com/32879218/58347049-a6d48480-7e11-11e9-83de-8f03807ca4ae.png)

**Comment by rhythm-sharma** [comment]
@swallitsch  can you please tell us, what is your Default language(setting->display setting->Default language) it's because the spellchecker language now automatically enable for default language

**Comment by ghost** [comment]
Zulip Preferences: English
Centos 7 language set to English (United States)

Spellchecker is on in the app settings

**Comment by kanishk98** [comment]
@swallitsch thanks for reporting the issue. I'm using Ubuntu, not CentOS, but the spellchecker takes some time to kick in for me as compared to Windows/macOS. Does this issue persist after a while/typing erratically in the text box?

(Sorry if this seems like a silly question, just doing a sanity check)

**Comment by ghost** [comment]
No matter how long I wait, spellchecker never underlines anything. I've left misspelled words up for a few hours before.

If I expand the AppImage, are there a few choice files I can add some logging to to see why spellchecker isn't initializing?

**Comment by akashnimare** [comment]
@swallitsch does the right-click context menus works for you?

![image](https://user-images.githubusercontent.com/2263909/60666069-c684b100-9e83-11e9-82aa-fc8ea03ef767.png)

**Comment by ghost** [comment]
@akashnimare negative, which is why #662 was the first ticket I filed. I opened this up later as we're not getting the red underlines either.

**Comment by akashnimare** [comment]
Merging this into #662 as both are connected.
