### ISSUE TITLE
Help > Help Center does not point to help of on-premise installation

### ISSUE THREAD

**Issue by sebastianelsner** [zulip/zulip-desktop#758]
---

- **Operating System**:
  - [ ] Windows
  - [x ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:

We  have installed Zulip server on premise in a network not connected to internet. 
Going through "Help > Help Center" opens a browser opening the online help. Being offline, the help cannot be displayed. 
Opening the actual help of the servers used would be the solution. This is what is done when run in a browser and you click the Gear icon and choose "Help Center"

**Comment by akashnimare** [comment]
@sebastianelsner this is fixed and will add this in next stable release.

**Comment by sebastianelsner** [comment]
Amazing! Thank you!
