### ISSUE TITLE
Zulip drafts discarded when wifi drops

### ISSUE THREAD

**Issue by itsalexschwartz** [zulip/zulip-desktop#767]
When wifi drops out while working in the OSX Zulip client, a refresh occurs and any WIP drafts are discarded. Video showing the issue here: https://www.dropbox.com/s/2r5xz7x64yytncn/zulip_deletes_drafts.mp4

**Comment by akashnimare** [comment]
@itsalexschwartz can you reproduce this issue while reloading the app using `CMD + R` ?

**Comment by akashnimare** [comment]
Okay, so spent some time on this issue and found out -
* The drafts get saved if I reload/hard-reload/refresh the app.
* If I switch off and on the wifi, the drafts get lost.

To fix this maybe we should send an event to the electron app just before we reload the webview using the electron bridge. The electron does have some issues with `beforeunload` events.

**Comment by akashnimare** [comment]
@itsalexschwartz the issue has been fixed and the fix will be included in the next release. Thanks for reporting this.
