### ISSUE TITLE
[feature request]Change Icon for Desktop app

### ISSUE THREAD

**Issue by Synatics** [zulip/zulip-desktop#790]
Can we get a way to change the icon at the top of the desktop app and the title? It would be nice if our logo could be there instead of "zulip". Attached is a picture of what i mean. Thanks
![60954942-26ee7500-a300-11e9-8c0c-1a505181e3f2](https://user-images.githubusercontent.com/51437569/61035796-1a355400-a3c8-11e9-816e-7a75fff9bb84.png)

**Comment by akashnimare** [comment]
I don't think we could provide this feature. Mainly, because the title and the logo is the identity of the Zulip official desktop app. However, you could put your icon in the https://github.com/zulip/zulip-desktop/tree/master/build directory and build your own version.
