### ISSUE TITLE
macos title bar does not adopt dark theme

### ISSUE THREAD

**Issue by jnnkB** [zulip/zulip-desktop#792]
On mac os the zulip desktop app does not adopt to the dark mode (see screenshot below).

---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS
- **Clear steps to reproduce the issue**:
Enable dark mode of mac os in System Preferences/General:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/29376715/61282629-facd6b00-a7bb-11e9-8403-84628a72f9e1.png">

- **Relevant error messages and/or screenshots**:

<img width="1146" alt="Screenshot 2019-07-16 at 11 19 06" src="https://user-images.githubusercontent.com/29376715/61282445-9f9b7880-a7bb-11e9-8037-8e166ca42eb5.png">

**Comment by akashnimare** [comment]
@jnnkB added in https://github.com/zulip/zulip-desktop/commit/6b1a55c7e4cc89908b9a04910857d49a8c394722 -

![image](https://user-images.githubusercontent.com/2263909/61308963-fe3e1200-a80e-11e9-8537-0dd1d251c1ab.png)
