### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by CodeDoctorDE** [zulip/zulip-desktop#797]
There is no space between the text and the topic name.

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS
- Click on a message in the german translation
- **Relevant error messages and/or screenshots**:
![Bildschirmfoto vom 2019-07-25 18-31-31](https://user-images.githubusercontent.com/20452814/61891676-7fca2a00-af0a-11e9-9f2f-44e4c17ff8de.png)

**Comment by akashnimare** [comment]
@timabbott can you transfer the issue to webapp?

**Comment by CodeDoctorDE** [comment]
yes

**Comment by timabbott** [comment]
I just fixed it in the translation data.
