### ISSUE TITLE
Set User-Agent when making requests to /server_settings

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#817]
Our server logs contain a bunch of entries like this:

`/api/v1/server_settings (unauth via Unspecified)`

("Unspecified" means no `User-Agent` header was set in the HTTP request)

Checking what those clients later requested, it's clear that the cause is ZulipElectron not setting that header.  I assume this bug is still in master, but if not, we should fix it... longer-term, we will likely require setting a `User-Agent` in all API requests.

**Comment by kanishk98** [comment]
> that the cause is ZulipElectron not setting that header.

I had a look, and it seems that we are setting the header, but the value of the `User-Agent` when validating the server (while adding a domain or on app load, to check for updates to the server icon) is `null` and we only set that to a legitimate `User-Agent` in `webview.ts`. 

I think there should be some entries in the server logs with actual user agents too. 

Regardless, I'd like to fix this. @zulipbot claim
