### ISSUE TITLE
Add option for a colorless menu bar icon

### ISSUE THREAD

**Issue by aryyya** [zulip/zulip-desktop#825]
On macOS it is more usual for menu bar icons to not have color.

Could Zulip add an option to display a colorless icon?

---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS
- **Relevant error messages and/or screenshots**:

![Example](https://user-images.githubusercontent.com/29365565/65717726-df51cc80-e056-11e9-9cb7-6364c9bfaf49.png)

**Comment by akashnimare** [comment]
@aryyya is this common for all the mac apps? I have checked most of the apps are colourless.

**Comment by aryyya** [comment]
In my experience the vast majority of macOS apps conform to this convention. Right now Zulip is the only app on my system that has a menu bar icon with color.

**Comment by akashnimare** [comment]
This is how it will look -

![image](https://user-images.githubusercontent.com/2263909/65789176-63e93b80-e17a-11e9-9186-133e2893af06.png)

<img width="1440" alt="Screenshot 2019-09-27 at 10 59 22 PM" src="https://user-images.githubusercontent.com/2263909/65789216-7f544680-e17a-11e9-8055-425cedca22a2.png">

**Comment by aryyya** [comment]
In your screenshot it looks a lot less sharp than the icons beside it, will the final version be higher res?

**Comment by akashnimare** [comment]
Yup, it should be sharper I think but I'm having a bit hard time getting to the high res version.

**Comment by aryyya** [comment]
How can I offer assistance?

**Comment by akashnimare** [comment]
@aryyya would you be able to make the tray image colourless keeping the size same?
https://github.com/zulip/zulip-desktop/blob/master/app/resources/tray/trayosx%404x.png

**Comment by kanishk98** [comment]
@akashnimare I'd love to help out here. Can you tell me how you got that colourless icon in the first place? Maybe I can go from there.

**Comment by vsvipul** [comment]
![trayosx@4xwhite](https://user-images.githubusercontent.com/21038781/72224026-94bf7600-359b-11ea-9f58-dd8d9f5cf1d1.png)
@akashnimare  Can you please check how does this image look in menu bar of mac ??

**Comment by vsvipul** [comment]
![trayosx@4xwhiytetrue](https://user-images.githubusercontent.com/21038781/72224063-1fa07080-359c-11ea-8754-2e9725e9021f.png)
@akashnimare  can you try out this icon on mac and see how it looks?

**Comment by akashnimare** [comment]
Let me check.

**Comment by akashnimare** [comment]
@vsvipul thanks, that looks good. @aryyya this is how it looks in the dark theme -

![image](https://user-images.githubusercontent.com/2263909/72234674-21961e00-35f4-11ea-85e5-3006236f9d83.png)


For the light theme, we need to use the current one only since colourless is not visible there.

**Comment by akashnimare** [comment]
@aryyya we are still using the colour icon for the light theme -

![image](https://user-images.githubusercontent.com/2263909/73435892-85984080-436f-11ea-9ded-c111a4c02d54.png)

For the dark theme -
![image](https://user-images.githubusercontent.com/2263909/73435907-8e891200-436f-11ea-9eff-d4b888a4ba02.png)
