### ISSUE TITLE
Problem with connection to a Zulip server "Not a valid Zulip server"

### ISSUE THREAD

**Issue by NickMos** [zulip/zulip-desktop#832]
---

- **Operating System**:
  - [+] Linux/Ubuntu
- **Clear steps to reproduce the issue**:
We have a Zulip server 2.0.5-0 version. Connection using browser is working fine but adding a new organization to the desktop Zulip client comes with an error that it is not a Zulip server.
Zulip is running in HTTP mode behind the proxy. The proxy makes SSL termination and HTTP to HTTPS redirection (HTTP 301) too. Has valid LetsEncrypt cert.

- **Relevant error messages and/or screenshots**:

**On Linux, Zulip client 4.0.0**:
`https://lets.chat.kkts.com.au does not appear to be a valid Zulip server. Make sure that 					
 (1) you can connect to that URL in a web browser and 
 (2) if you need a proxy to connect to the Internet, that you've configured your proxy in the Network settings 
 (3) its a zulip server 					
 (4) the server has a valid certificate, you can add custom certificates in Settings>Organizations`

Please help with the Linux client version because most of our staff are on Linux OS and can't login into the Zulip server.

**Comment by NickMos** [comment]
Also tested with different versions
3.0.0 - connects
3.1.0 - does not

and got the error from debug menu
"UNABLE_TO_VERIFY_LEAF_SIGNATURE"

**Comment by NickMos** [comment]
My bad. I found the issue. I was using a cert with an incomplete chain. After I put a full chain cert everything is working fine with 4.0.0.

**Comment by NickMos** [comment]
@akashnimare I only could suggest adding somewhere in the documentation about full chain cert. That it must be full chain complete. Because `(4) the server has a valid certificate` could be confused sometime when you see that cert is valid in a browser.

**Comment by timabbott** [comment]
I think the right approach is we should have a link to our general SSL troubleshooting guide, which aims to cover a lot of issues like this:
https://zulip.readthedocs.io/en/stable/production/ssl-certificates.html

@akashnimare what do you think?

**Comment by akashnimare** [comment]
@timabbott just to be clear, we should be adding the following links in the error dialog, right? i.e. somewhere here - 

![image](https://user-images.githubusercontent.com/2263909/67510618-e64e1800-f6b2-11e9-92bd-90272dc1b2a4.png)

**Comment by timabbott** [comment]
Yep, that's correct.

**Comment by akashnimare** [comment]
Done!
