### ISSUE TITLE
Ability to increase notification visibility for recent topics

### ISSUE THREAD

**Issue by stuartwdouglas** [zulip/zulip-desktop#835]
It would be great if there was a way to increase the urgency of notifications for topics I have been recently active in. 

Something like it is treated the same as an @mention if there is activity in a topic that I have posted too in the last 30m. We have a very active zulip instance which means there is a lot of noise, so if I am having a conversation I can't rely on notifications as most of them are in other topics, I need to remember to manually check every few minutes to see if there has been a reply.

**Comment by kanishk98** [comment]
This is a pretty cool suggestion. Thanks @stuartwdouglas!

I'm not sure if this is something that should be implemented entirely in the desktop app, though. If we were to put this in the web app instead and then simply pull the notifications from there as usual, that might be a better solution. 
Would that solve your issue?

**Comment by akashnimare** [comment]
@timabbott I think we should do this in the web-app?

**Comment by stuartwdouglas** [comment]
That makes sense, I was not really sure about the internals, I use the desktop app so I made an assumption that it was the place to file the issue.

**Comment by timabbott** [comment]
Yeah, there's an open webapp issue for this; in any case work on this is certainly planned.  I think https://github.com/zulip/zulip/issues/12309 is the best place to follow.
