### ISSUE TITLE
Showing "real" context menus right-clicking streams/topics/messages

### ISSUE THREAD

**Issue by moeenio** [zulip/zulip-desktop#836]
The right-click context menu on topics, messages, and streams only show Copy/Open. I think it should show the menu you can get clicking the arrow on the stream/message/topic (with a copy option added).

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS
- **Clear steps to reproduce the issue**: Right click any message, stream or topic.
- **Relevant error messages and/or screenshots**: 

Right-click menu :

![Right-click stream menu screenshot](https://user-images.githubusercontent.com/37651007/67551064-47540b00-f708-11e9-928d-36c7928ad658.png)

Arrow menu :

![Arrow stream menu screenshot](https://user-images.githubusercontent.com/37651007/67551191-9c901c80-f708-11e9-9820-5ef0cfdf98f0.png)

**Comment by kanishk98** [comment]
Hmm, I think this is a good idea. We should be able to do this. 
@akashnimare it'll be great if you can let us know what you think - I'd like to make sure we're not disrupting a commonly used interface here.

**Comment by moeenio** [comment]
>I'd like to make sure we're not disrupting a commonly used interface here.

We can keep the arrow button, and have the right-click as an addition

**Comment by vsvipul** [comment]
I think this won't technically me possible inside the webview. How do you plan to make it work @kanishk98  ?

**Comment by moeenio** [comment]
> I think this won't technically me possible inside the webview. How do you plan to make it work @kanishk98 ?

I believe we can use an `contextmenu` event listener to show the current dropdown

**Comment by vsvipul** [comment]
@locness3  Yes, but how do you plan to capture on which element the user has right clicked?

**Comment by moeenio** [comment]
> @locness3 Yes, but how do you plan to capture on which element the user has right clicked?

well, with event.target

**Comment by vsvipul** [comment]
@locness3 Maybe it can work, I am willing to work on this if this is really required and will improve UX. @akashnimare  thoughts?

**Comment by akashnimare** [comment]
We have the same behaviour as the Chrome I think. I really doubt that we need to update our current behaviour. @timabbott should we proceed in this direction? I'm happy with the current implementation which is getting those options when clicked on arrow. And I don't think folks will expect a right-click there.

**Comment by timabbott** [comment]
Yeah, I don't think it makes sense to move away from browser default behavior in this one place.

**Comment by akashnimare** [comment]
Make sense. We can revisit this later once we get more feedback on this.

**Comment by moeenio** [comment]
Well, we could do this on the web version as well
