### ISSUE TITLE
Investigate PWA Support

### ISSUE THREAD

**Issue by ghost** [zulip/zulip-desktop#838]
I see that Zulip Desktop 4.0.0 is still using Electron 3 (it looks like Zulip Desktop support for Electron 5 is coming) and that Chrome now has [Progressive Web Apps](https://developers.google.com/web/progressive-web-apps); would it be possible to support Progressive Web Apps for Zulip Desktop to provide similar system integration but reduce the overhead of using Electron?

**Comment by akashnimare** [comment]
I think PWA and the desktop app are two separate things, right? For PWA, we gotta improve our webapp first. For that, you can report the same here -  
https://github.com/zulip/zulip

**Comment by ghost** [comment]
I created [this issue](https://github.com/zulip/zulip/issues/13337) there to request support from the webapp, thanks!
