### ISSUE TITLE
cannot zoom out in windows app

### ISSUE THREAD

**Issue by nikomatsakis** [zulip/zulip-desktop#839]
I accidentally zoomed in much too far on https://rust-lang.zulipchat.com/, which I am viewing in the Windows App. Unfortunately, pressing `Ctrl+-` doesn't make the make the text size any smaller. Selecting Zoom Out from the menu also has no effect. Selecting "Zoom to actual size" (`Ctrl+0`) also does nothing. Removing the organization and adding it back again also had no effect; the text remained at the larger size. 

Help!

**Comment by timabbott** [comment]
Transferring issue to the desktop repo in case anyone else reproduces this.

**Comment by MasonProtter** [comment]
This happens for me in MacOS on the desktop app. The zoom in menu button does not work, but the zoom out button and the zoom in /out keyboard shortcuts do work. 

I have a screen recording of it happening but Github won't let me upload a video. If you want the video, just suggest a place I can upload it and I'll do so.

**Comment by mtzguido** [comment]
This is happening to me too in Linux on v5.2.0. `Ctrl -` does nothing, `Ctrl +` does zoom in but then I can't go back. `Ctrl 0` and `Ctrl )` which I've seen suggested, or the mouse wheel, also don't do anything.

Please add a way to tweak zoom from the settings, perhaps under display settings, to have a way out.

**Comment by akashnimare** [comment]
@mtzguido please check #911.
