### ISSUE TITLE
manual update required?

### ISSUE THREAD

**Issue by j0hannesr0th** [zulip/zulip-desktop#844]
Everyone in our company has the Windows client with version 2.3.82 installed.
![grafik](https://user-images.githubusercontent.com/36242595/69556535-27349780-0fa5-11ea-9455-16df514cdea6.png)

Today I saw that 4.0.3 is already out but we're stuck on 2.3.82.

Is the updater broken in our version? Should we wait or do a manual upgrade?

---

- **Operating System**:
  - [x] Windows

**Comment by akashnimare** [comment]
@hmr-it-jr hey, I have yet to upload the files for Windows Zulip app v4.0.3. But I think v2.3.82 is too old and you might need to do the manual upgrade here.
https://zulipchat.com/apps
