### ISSUE TITLE
Rendering artifacts on Linux

### ISSUE THREAD

**Issue by becken** [zulip/zulip-desktop#848]
I tested Zulip-4.0.0-x86_64.AppImage on Linux 4.19 with X.Org 1.18.3 for a very short period before noticing severe rendering artifacts on text as well as images.

The application produces effects like in the below screenshot quite frequently. Tested with the chat.zulip.org server.

---
- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Happens through normal usage simply by moving the mouse cursor around.
- **Relevant error messages and/or screenshots**:
![zulip](https://user-images.githubusercontent.com/3751582/70252931-869f5e00-1782-11ea-96bd-31a84dcfaed6.png)

**Comment by akashnimare** [comment]
This is bad. Let me cross-check this on my system.

**Comment by andersk** [comment]
In Zulip Desktop 5.0.0 we’ve updated to a much newer version of Electron and Chromium. Do you still see this issue?

**Comment by becken** [comment]
With the 5.0.0 AppImage, I no longer see any such artifacts. 👍
