### ISSUE TITLE
"GitHub no longer support your web browser" in desktop app

### ISSUE THREAD

**Issue by omry** [zulip/zulip-desktop#849]
It is no longer possible to authenticate with GitHub in the desktop app.
See screenshot.
A solution can be to update the user agent sent to GitHub.

![image](https://user-images.githubusercontent.com/376455/70380685-13b5f480-18f4-11ea-99b9-fde465e8c373.png)

**Comment by timabbott** [comment]
@omry just to confirm, what desktop app version are you using?

@akashnimare we need to prioritize investigating this ASAP -- since I'm not aware of a mechanism that someone would get this without it breaking GitHub social auth for everyone using the desktop app.

**Comment by omry** [comment]
I am using v4.0.0, this seems to be the latest version.

**Comment by akashnimare** [comment]
Will fix the issue by this week.

**Comment by omry** [comment]
Any update?

**Comment by akashnimare** [comment]
@omry we are working on this - https://github.com/zulip/zulip-desktop/pull/854
