### ISSUE TITLE
Show only stream specific users on right panel

### ISSUE THREAD

**Issue by parthi2929** [zulip/zulip-desktop#865]
---

- **Operating System**: 
  - [x ] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
In any stream, you could see all users on right side bar. I would like to see only those that are subscribed to the stream I have opened. I could not find this option anywhere in settings. 
- **Relevant error messages and/or screenshots**:

**Comment by timabbott** [comment]
There's an open effort to add such a setting in the appropriate project: https://github.com/zulip/zulip/pull/12846

**Comment by parthi2929** [comment]
@timabbott the screenshots link asks to register.. could we expect this fix in next release?

**Comment by timabbott** [comment]
It'll be in an upcoming webapp update; we don't have a timeline for it at this time.
