### ISSUE TITLE
Undo not working in compose box on macOS

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-desktop#866]
EDIT: Observed only on macOS so far. Seems not to affect Linux; untested on Windows.

I (on Zulip desktop 4.0.0) and another member of the Recurse Center noticed that undo isn't working in the compose box on macOS, either from the Edit menu or by using command-Z. Immediately after typing some text, if you try to undo, your input doesn't change at all.

I'm not sure if this is a bug, or a feature that hasn't been introduced yet.

**Comment by ngoldbaum** [comment]
seems to work fine on linux

**Comment by ngoldbaum** [comment]
(I'm using 4.0.1 though, maybe you want to update your client?)

**Comment by chrisbobbe** [comment]
Hmm, I'm not sure how you got 4.0.1, as it isn't on the releases list (https://github.com/zulip/zulip-desktop/releases) -- but I just tested on the 4.0.2 pre-release on Mac and undo is still not working. :)

**Comment by akashnimare** [comment]
Just tested this, I can confirm this issue.

**Comment by peterdalydickson** [comment]
I can confirm the issue too, on v4.0.0 of macOS desktop app

**Comment by adityamudgil2505** [comment]
@zulipbot claim

**Comment by adityamudgil2505** [comment]
@akashnimare Undo and Redo have no effect inside <webview> tag after v1.8.8 for macOS. [Read this](https://github.com/electron/electron/issues/15728)
