### ISSUE TITLE
Rendering artifacts in stream setting screen on macOS 10.15 

### ISSUE THREAD

**Issue by XAMPPRocky** [zulip/zulip-desktop#869]
Every time I open the stream settings screen I get the exact same artifacting that makes using that screen completely unusable. I've tried this across restarts of both the app and OS.
 

- **Operating System**:
 macOS (10.15.2 (19C57))
- **Clear steps to reproduce the issue**:
- Click on the stream setting screen.

### Screenshot
<img width="1421" alt="Screenshot 2020-02-14 at 11 22 16" src="https://user-images.githubusercontent.com/4464295/74522860-56133780-4f1c-11ea-95d8-b6fb38b67616.png">

### Screen Recording
I've included a gif since mp4 is not allowed to be included in an issue, however the gif's low framerate makes some of the artifacting hard to see. I've also included a temporary firefox send link to an mp4.

https://send.firefox.com/download/288044de8d2d7cc3/#_OsCf5yvG8_hZ_FMZfQX3Q

![zulip-bug](https://user-images.githubusercontent.com/4464295/74522245-1f88ed00-4f1b-11ea-9e6d-1cf80c6f470e.gif)

**Comment by XAMPPRocky** [comment]
Another one I encountered was when I selected the email address the whole section disappeared.
<img width="1205" alt="Screenshot 2020-02-16 at 10 22 33" src="https://user-images.githubusercontent.com/4464295/74602187-6f47ef80-50a6-11ea-833c-2a09566474a8.png">

**Comment by akashnimare** [comment]
@XAMPPRocky hey, thanks for reporting this. Can you reproduce the same thing in the browser?

**Comment by XAMPPRocky** [comment]
@akashnimare I just tested on Safari, and did not have these issues.

**Comment by akashnimare** [comment]
@XAMPPRocky I can't reproduce this. Can you please tell us the details of your system (RAM etc)?

**Comment by XAMPPRocky** [comment]
I've included as much system information as possible. @akashnimare I joined another zulip org and tested it there, and there is definite difference between a zulip org with few streams (Loads fast and is somewhat noticeable) to one with a lot of streams (Slow, and looks like above).

### About This Mac
<img width="698" alt="Screenshot 2020-02-23 at 10 13 04" src="https://user-images.githubusercontent.com/4464295/75109684-e5f46800-5625-11ea-9236-2e22826c59bd.png">

### System Report on Memory
<img width="863" alt="Screenshot 2020-02-23 at 10 17 54" src="https://user-images.githubusercontent.com/4464295/75109680-e0971d80-5625-11ea-8fd4-cadc45b98b77.png">

## System Report on GPUs
<img width="455" alt="Screenshot 2020-02-23 at 10 17 37" src="https://user-images.githubusercontent.com/4464295/75109682-e55bd180-5625-11ea-806b-a2b634b40ad3.png">
<img width="481" alt="Screenshot 2020-02-23 at 10 17 16" src="https://user-images.githubusercontent.com/4464295/75109683-e55bd180-5625-11ea-9779-69842c30ff3e.png">

**Comment by akashnimare** [comment]
@XAMPPRocky thanks for the detailed info. 

> I joined another zulip org and tested it there, and there is definite difference between a zulip org with few streams (Loads fast and is somewhat noticeable) to one with a lot of streams (Slow, and looks like above)

Would it be possible for you to check the Zulip version in both the orgs? You can see the version at `org_url/api/v1/server_settings`. Example -

https://chat.zulip.org/api/v1/server_settings

**Comment by XAMPPRocky** [comment]
Rust-lang: 2.0.0-4046-g020190241a
Bytecodealliance: 2.0.0-4046-g020190241a

They are both hosted on `zulipchat.com`.

**Comment by akashnimare** [comment]
@timabbott any idea here?

**Comment by timabbott** [comment]
Well, the version display bug for zulipchat.com is something I've fixed for the next production deployment there.  zulipchat.com is all we need to know about server version.

What desktop app version is it?  This sounds like a Chromium bug that will likely only be fixable by upgrading Electron; I'd like to be sure you're on 4.0.x.

**Comment by XAMPPRocky** [comment]
@timabbott My desktop version is `v2.3.82`, and I have auto updates on.

**Comment by XAMPPRocky** [comment]
This is no longer an issue, though the UI does feel sluggish on the `rust-lang` zulip.

**Comment by timabbott** [comment]
Great.  In the last few days we added a big banner notice for folks running 2.3.82; that version has a bug that prevents it from auto-updating, which is likely why were stuck on it.
