### ISSUE TITLE
Remove deprecated request module

### ISSUE THREAD

**Issue by andersk** [zulip/zulip-desktop#886]
The `request` module is [deprecated](https://www.npmjs.com/package/request). Although it is still used by our indirect dependencies, we should replace our direct uses of it.

**Comment by akashnimare** [comment]
Damn, just came to know about this. Will have to explore alternatives now.

**Comment by Bearbobs** [comment]
Moving to something like `axios` or `urlib` can be a good solution

**Comment by akashnimare** [comment]
Yeah, gotta see if those satisfy our requirements (proxy support etc).

**Comment by andersk** [comment]
I do feel compelled to ask: given that Electron is, you know, a web browser…do we actually need a separate third-party library to make web requests? Can we just use [`electron.net`](https://www.electronjs.org/docs/api/net)?

**Comment by Bearbobs** [comment]
`electron.net` is another fork of `request` module, I guess

**Comment by andersk** [comment]
I [don’t see](https://github.com/electron/electron/commits/master/lib/browser/api/net.js) any evidence of that. But that wouldn’t matter; the Electron developers will maintain `electron.net` regardless of what happens to any modules it may or may not be a fork of.

**Comment by timabbott** [comment]
Yeah, it seems like switching to `electron.net` makes a lot of sense.

**Comment by Bearbobs** [comment]
@andersk makes sense, can I please work on migrating `request` to `electron.net`?

**Comment by akashnimare** [comment]
@Bearbobs can you first check if we can use it in the `renderer` process or not?

**Comment by Bearbobs** [comment]
on it, will revert back @akashnimare.
Thanks,

**Comment by Bearbobs** [comment]
@akashnimare yes we can use it for the `renderer` process, it's quite straight forward as the request package

**Comment by Somtozech** [comment]
Anyone working on this already?

**Comment by Bearbobs** [comment]
@Somtozech me

**Comment by Bearbobs** [comment]
@akashnimare @timabbott 
https://chat.zulip.org/#narrow/stream/16-desktop/topic/GSoC-2020/near/833454

**Comment by PawBud** [comment]
Any updates on this @Bearbobs?

**Comment by PawBud** [comment]
Is this issue claimed?
