### ISSUE TITLE
Replace deprecated isDarkMode

### ISSUE THREAD

**Issue by abhigyank** [zulip/zulip-desktop#891]
Since we have moved to electron 8, we need to replace deprecated APIs. One of them is [isDarkMode](https://www.electronjs.org/docs/api/system-preferences#systempreferencesisdarkmode-macos-windows-deprecated), it is to be replaced by `shouldUseDarkColors`. We use it for tray icons.

**Comment by manavmehta** [comment]
@zulipbot claim
