### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by Somtozech** [zulip/zulip-desktop#898]
The package-lock.json conflicts with the lock files for other package managers that is not npm eg Yarn. Removing the package-lock.json from the repo and adding it to .gitignore solves this conflict issue

**Comment by andersk** [comment]
`package-lock.json` is important for reproducibility and should not be ignored. Using `npm` and `yarn` on the same package is generally not supported; we use `npm` for this one.
