### ISSUE TITLE
Open an upstream Electron issue for macOS undo/redo bug

### ISSUE THREAD

**Issue by andersk** [zulip/zulip-desktop#899]
The undo/redo issue #866, worked around by #890, appears to be an upstream Electron issue. @adityamudgil2505 provided a reference to electron/electron#15728, but that was reported against Electron 3 and closed as need-info. Someone who has a Mac and can reproduce this issue in a currently supported Electron version should provide upstream with the needed information and either get that bug reopened or open a new one.

**Comment by Cybernisk** [comment]
I can confirm the issue, on v4.0.3 of macOS v10.11.6 desktop app, cmd+z not working. Should I provide any additional information?

**Comment by andersk** [comment]
@Cybernisk We need to confirm this *in a currently supported Electron version* (so not Zulip Desktop v4.0.3, which uses Electron 3), and ideally produce a minimal test case (so not Zulip Desktop at all, since that isn’t minimal). The goal is to provide an actionable bug report to the Electron developers so they can fix it.

**Comment by akashnimare** [comment]
@adityamudgil2505 are you up for this? I know that you have tested the app against v8 and it still doesn't work and we have to report the same.

**Comment by adityamudgil2505** [comment]
@akashnimare  Yes, this issue still exists in the latest version of electron v8.1.1 on macOS Catalina. I agree with @andersk to report a bug to Electron developers.

**Comment by andersk** [comment]
@adityamudgil2505 Can you go ahead and do that, then? When you’re done, leave a link to the new Electron issue here so the rest of us can follow it. Thanks!

**Comment by adityamudgil2505** [comment]
@andersk Sure, I will create an Issue.

**Comment by adityamudgil2505** [comment]
@andersk Issue Link
Undo/Redo has no effect inside webview  https://github.com/electron/electron/issues/22744

**Comment by akashnimare** [comment]
Looks like they fixed this issue in upstream - https://github.com/electron/electron/pull/22911
