### ISSUE TITLE
Use system default dictionary

### ISSUE THREAD

**Issue by MasonProtter** [zulip/zulip-desktop#900]
- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS

I'm Canadian and default to a Canadian dictionary on my system but in the desktop app, if I write something like 'coloured' it shows up as a typo with no clear way to change the dictionary

![Screen Shot 2020-03-19 at 1 49 42 PM](https://user-images.githubusercontent.com/29157027/77108852-8ef56f00-69e8-11ea-93a9-7530645e5844.png)

This is not the case for me when using Zulip from the browser.

**Comment by abhigyank** [comment]
Hi @MasonProtter , The dictionary that is currently being used is based on the language chosen on by user account for the organization. 
In Zulip (web or browser), please go to Settings -> Display Settings and change "Default Language". I see that Canadian English is not there, but British English is there (which I presume is almost similar, please forgive my ignorance). 
Please try this out and let us know back here if it works (or doesn't).

**Comment by MasonProtter** [comment]
Thank you, this resolves my issue well enough!
