### ISSUE TITLE
“Factory Reset” and “Reset App Data” use two completely separate code paths

### ISSUE THREAD

**Issue by andersk** [zulip/zulip-desktop#903]
The **Tools → Factory Reset** menu option and the **Settings → General → Reset App Data** button use two completely separate code paths that do slightly different things. We should remove one of them or unify the two to use the same code.

**Comment by adityamudgil2505** [comment]
@andersk I think both types of reset is important. For better use of reset, we can migrate the **Factory Reset** in menu option to **Settings → General → Reset App Data**, so users can easily understand which reset option is useful for them.
