### ISSUE TITLE
where's your Hackerone project

### ISSUE THREAD

**Issue by imagemlt** [zulip/zulip-desktop#905]
I'd like to report a security isue, and found that you claimed having a Hackerone bug bounty program, but I can't find anything abount Zulip on hackerone. so How can I report this to you?

**Comment by abhigyank** [comment]
@timabbott Please look into this.

**Comment by timabbott** [comment]
@imagemlt our HackerOne program isn't public yet.  Can you contact security@zulipchat.com?  That's our documented security contact.  Or you can send us your HackerOne username and we can invite you to our program.
