### ISSUE TITLE
Zulip Kerberos Authentification

### ISSUE THREAD

**Issue by Dbone29** [zulip/zulip-desktop#906]
---

- **Operating System**:
  - [x] Windows
  - [x] Linux/Ubuntu
  - [x] macOS
- **Clear steps to reproduce the issue**:
Zulip Server with Apache SSO and Kerberos

We are running a Zulip Server for our university and we have the requirement to use Kerberos/LDAP. Everything works just fine except all desktop clients.
Is it possible to integrate kerberos support into the clients?
Thanks!

**Comment by timabbott** [comment]
@Dbone29 thanks for the report!  I think our planned approach for this is to delegate to the browser; we now do this for Google/GitHub/GitLab authentication (it's a very recent change, requiring pre-release versions of both the desktop app and server).  

You can use pinned browser tabs as a workaround until that's ready.

One thing I don't know off the top of my head is whether things are hooked up properly for this to work; just to confirm, you're using ZulipRemoteUserBackend in `/etc/zulip/settings.py`?  

@mateuszmandera FYI, I'm not sure we've tested that precise configuration with the new desktop auth flow; can you make sure it works?  If so, we can recommend @Dbone29 install master and use the upcoming 5.0.0 desktop app version (should be out in a few days).

**Comment by Dbone29** [comment]
Yes, I'm using the ZulipRemoteUserBackend.

**Comment by mateuszmandera** [comment]
@timabbott https://github.com/zulip/zulip/commit/eea68ce92d6299e30dd94151fd6cea591cbee271 added support for the flow with automated tests, and the desktop app doesn't care about the details of the auth steps that happen in the browser, so I'm pretty sure it'll work fine. I can try to test manually too, once I get my production installation working again.

**Comment by akashnimare** [comment]
@mateuszmandera is this being taken care of?

**Comment by mateuszmandera** [comment]
@akashnimare I tested right now, actually doesn't work, the app isn't opening the browser upon clicking the button like it does for google, github, I don't know why. You can test on https://myrealm1.gentoox.net/accounts/login/ if you'd like to debug. Google and github auth doesn't work there, but if you click their buttons, the app will open the browser. Same would be expected for the SSO button. You can PM me on czo for your credentials for this auth method :slightly_smiling_face:

**Comment by mateuszmandera** [comment]
This no longer works the way it used to since https://github.com/zulip/zulip/commit/40c80029034eea896e18de8add9db51ea7b8aa75

I think a server-side fix will be most appropriate here, I'll try to figure something out.

**Comment by timabbott** [comment]
This was fixed by zulip/zulip#15163.

**Comment by timabbott** [comment]
@Dbone29 I recommend upgrading your server to master to get this fix.
