### ISSUE TITLE
Zulip 4.0.3 desktop client for MacOS is a constantly reloading disaster I cannot use (also the 5.0.0 update)(still happening, help???)

### ISSUE THREAD

**Issue by alice-kaanta** [zulip/zulip-desktop#907]
To replicate: 
1) Read the alarming banner over your Zulip desktop client that announces the old version has security bugs.  
2) Install the newest client (4.0.3) on your MacOS machine, as per standard practices.  
3) Open your Zulip desktop client and start using Zulip as per usual.  
4a) Expected result: Everything works.  
4b) Actual result: Zulip "reloads" every 3-5 seconds, which means I can literally do nothing except read new messages as they come in.  

Update 4/1 13:20 PM: Installed the 5.0.0 update.  Still seeing same behavior.  Will attempt devtools to see what I can find.  (I really hate Heisenbugs.)

Update 4/1 13:27 PM: Opened the devtools view, which closed immediately as the page reloaded.  Will attempt to get a screenshot.  

Update 4/1 13:29: See screenshot below.  I think it thinks I'm repeatedly going offline and online.  
![image](https://user-images.githubusercontent.com/35539502/78167700-dfbf8b80-741c-11ea-9034-2954efc22cff.png)

Update: 4/1 13:39  Restarted my computer, no improvement.  Going back to using the browser version, which is inexpressibly sad as it now becomes one tab amongst a hundred.  New screenshot that I snatched between reloads, with my lightening reflexes: 
<img width="1198" alt="Screen Shot 2020-04-01 at 1 38 30 PM" src="https://user-images.githubusercontent.com/35539502/78168623-41ccc080-741e-11ea-986f-b86ce92c4e7c.png">

Update: 4/3 14:34 Still happening.  Am sad beyond description that I have to use the browser version because I have literally >100 tabs open at any given time and need Zulip to be more findable as a desktop app.

**Comment by timabbott** [comment]
(I should mention you can always use the webapp as a workaround while we figure out what's wrong)

**Comment by abhigyank** [comment]
@manavmehta @akashnimare  Can you replicate this on prod version in your Mac?

**Comment by manavmehta** [comment]
I'm afraid I can't reproduce it. It's working perfectly for me in prod (as well as dev).
Can this be of one some user specific bugs ?
I have a similar (not-every-mac-reproducible bug : https://chat.zulip.org/#narrow/stream/9-issues/topic/zoom.20out.20issue)

**Comment by andersk** [comment]
> I'm afraid so.

Meaning you can reproduce it?

> It's working perfectly for me in prod (as well as dev).

Meaning you cannot reproduce it?

**Comment by manavmehta** [comment]
@andersk sorry, should've been more obvious. I can't reproduce the issue

**Comment by adityamudgil2505** [comment]
I can't reproduce this issue in macOS Catalina (10.15) in Zulip-Desktop Version (4.0.3).

**Comment by akashnimare** [comment]
@alice-kaanta are you able to reproduce this frequently? Also, is your internet connection stable? Let us know if you have special configuration for the internet.

**Comment by timabbott** [comment]
Another question that might shed some light on the problem: @alice-kaanta do you get any error in the web console using Zulip Chrome in that organization?

**Comment by alice-kaanta** [comment]
This is happening every time I open the Zulip desktop application, right up to 2 minutes ago.  My internet is fine (I've got a broadband connection in a Boston suburb and have had no problems with my many, many meetings at home).  The browser version (I use Chrome) is fine (aside from being one tab in a cast of thousands)

**Comment by alice-kaanta** [comment]
I got logged out, and I attempted to log in again (via Google SSO), but am unable to do so because of the constant reloading.  😞

**Comment by alice-kaanta** [comment]
Same as above.

**Comment by alice-kaanta** [comment]
Seems to be fixed in the most recent update, thank you, Zulip team!

**Comment by timabbott** [comment]
Glad to hear it!  I doubt we did anything specific here -- likely a Chromium bug fixed upstream that we happened to get for free when we upgraded that.  We appreciate the follow-up; I hate having weird bugs like this pending.

**Comment by v3ss0n** [comment]
we have the same problem too. Still reloading randomly.

**Comment by timabbott** [comment]
@v3ss0n please open a separate issue, since what you're experiencing is almost certainly an unrelated bug with the same symptom.

**Comment by v3ss0n** [comment]
Thanks a lot @timabbott  
https://github.com/zulip/zulip/issues/19727
