### ISSUE TITLE
More granular zoom options

### ISSUE THREAD

**Issue by MasonProtter** [zulip/zulip-desktop#908]
It'd be good if the desktop app had more granular control over zoom levels. The jump for me on MacOS between the default zoom and the next level is too big a jump. Maybe we need something like a 1.25x zoom level?

**Comment by abhigyank** [comment]
The current zoom is of 0.1 at every level. That is goes 1x -> 1.1x -> 1.2x and so on. 
https://github.com/zulip/zulip-desktop/blob/82a7f97ca6c65eee34cf0062cc116fed9970374a/app/renderer/js/components/webview.ts#L233

**Comment by MasonProtter** [comment]
Ah, yeah fair enough. Maybe incrementing by `.05` then?  I just find this jump a bit too big and want somewhere in-between them (and I've heard similar sentiments from others in our workspace).

**Comment by abhigyank** [comment]
@timabbott Should we do this?

**Comment by manavmehta** [comment]
@abhigyank if we're gonna support this, please do tell me as I am looking into #911  and this can be added

**Comment by timabbott** [comment]
I think it makes sense to emulate the zoom levels available in a normal browser; people are generally pretty happy with that?

**Comment by abhigyank** [comment]
Chrome does 1x-> 1.1x->  1.25x ->1.5x.
Comparatively we are already much more granular.

**Comment by akashnimare** [comment]
> Comparatively we are already much more granular.

Agreed. I think it's already pretty granular, shouldn't go lower than this. We can revisit this if we get more feedback related to the zoom level.
