### ISSUE TITLE
Tray Icon disappears on Screen Lock & Unlock

### ISSUE THREAD

**Issue by punchagan** [zulip/zulip-desktop#910]
- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

I'm on Ubuntu Focal (GNOME Shell 3.36.0). 

When running the desktop app on the latest master, the tray icon seems to disappear when I lock my screen and unlock it. Hard reloading the app seems to restore it. CZO discussion [here](https://chat.zulip.org/#narrow/stream/16-desktop/topic/Tray.20icon).

**Comment by andersk** [comment]
This seems to be an upstream problem that affects all applications, so there probably isn’t anything we can do. See ubuntu/gnome-shell-extension-appindicator#75.

**Comment by fauust** [comment]
Same here, tray icon has just gone

OS: Debian Buster
Window manager: i3wm + polybar

**Comment by fauust** [comment]
Any chance that this could be related to https://github.com/electron/electron/issues/21445?
See also https://github.com/keybase/client/issues/23347.

**Comment by imolein** [comment]
Same here, tray icon is gone since I updated the desktop app to version 5.0.0.

OS: Xubuntu 18.04.3
WM: XFCE

**Comment by dotenorio** [comment]
I solved this with this code:

```js
  if (os.platform() !== 'linux') return

  const monit = exec(`
    dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" |
    while read x; do
      case "$x" in 
        *"boolean true"*) echo SCREEN_LOCKED;;
        *"boolean false"*) echo SCREEN_UNLOCKED;;  
      esac
    done
  `)

  monit.stdout.on('data', (data) => {
    const out = data.toString().trim()
    if (out === 'SCREEN_UNLOCKED') {
      tray.destroy()
      createTray()
    }
  })
```

You can see more about this in my repo https://github.com/dotenorio/clipboard-manager-electron/ on `lib/create_window.js` line `350`

**Comment by imolein** [comment]
As described in comment https://github.com/electron/electron/issues/21445#issuecomment-565061274 I can confirm it is working with `xfce4-statusnotifier-plugin` in Xubuntu 18.04

**Comment by devurandom** [comment]
On KDE Plasma, using the Flatpak, I never see any tray icon at all on these two systems (i.e. not even right after start of the application, which is a problem if `startMinimized=true` in `~/.config/Zulip/config/settings.json`):
```
Operating System: Gentoo Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.1
Kernel Version: 5.5.14
OS Type: 64-bit
```
```
Operating System: Fedora 31
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.67.0
Qt Version: 5.13.2
Kernel Version: 5.5.13-200.fc31.x86_64
OS Type: 64-bit
```

See-Also: https://github.com/flathub/org.zulip.Zulip/issues/18

**Comment by fauust** [comment]
Hi!
Since 5.0.0 was released (19 days ago) the tray icon is completely missing. If my understanding is correct this is not directly related to zulip but to electron https://github.com/electron/electron/issues/21445.

I have tried to revert to 4.0.3 version but this seems to be impossible, I have also looked for beta releases following https://zulipchat.com/help/desktop-app-install-guide#install-a-beta-release.

So my only solution for now is to use the browser version or to live without tray icon and the notification counter...

Does anybody has a workaround to share with me? Building a version from source is an option I could consider of course!

Regards,
Faustin

**Comment by fauust** [comment]
Side note: my issue is not exactly this one (tray icon is totally missing), should I open a new issue?

**Comment by akashnimare** [comment]
@fauust please file a new bug with detailed info (Linux distro, app installer type etc).

**Comment by devurandom** [comment]
> > Side note: my issue is not exactly this one (tray icon is totally missing), should I open a new issue?
>
> @fauust please file a new bug with detailed info (Linux distro, app installer type etc).

@fauust Please link it here afterwards, since I am having the exact same issue.

See-Also: https://github.com/zulip/zulip-desktop/issues/910#issuecomment-609930694
See-Also: https://github.com/flathub/org.zulip.Zulip/issues/18

**Comment by fauust** [comment]
@akashnimare done https://github.com/zulip/zulip-desktop/issues/936

**Comment by abhigyank** [comment]
@punchagan A chromium bug was created for this 
https://bugs.chromium.org/p/chromium/issues/detail?id=1042098 .
There is also a Gnome level issue at https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/220

I guess we have to wait for this to be fixed upstream. Till then one may build out of the hack of #922 if necessary.

**Comment by punchagan** [comment]
> Till then one may build out of the hack of #922 if necessary.

I think it is worth doing the hackish fix.

**Comment by abhigyank** [comment]
Electron is restoring to the original way of implementation for tray icon, so that should fix this issue for us. https://github.com/electron/electron/pull/23674

**Comment by abhigyank** [comment]
@punchagan Can you test on the latest release? Electron has restored to the original way of implementation so this should be fixed in the older release.

**Comment by fauust** [comment]
Latest version working again, see https://github.com/zulip/zulip-desktop/issues/936#issuecomment-649344282

My setup:
- debian 10
- i3wm
- polybar

**Comment by punchagan** [comment]
> @punchagan Can you test on the latest release?

I see the icon now, but I don't see the correct icon. I see ellipsis being shown instead of the Zulip logo. :see_no_evil: 

![image](https://user-images.githubusercontent.com/315678/85813318-80092000-b780-11ea-8078-a28f7e3ca2c8.png)

**Comment by punchagan** [comment]
> I see the icon now, but I don't see the correct icon. I see ellipsis being shown instead of the Zulip logo. see_no_evil

This was when I was running from source. The `snap` shows the icon correctly. Just adding a note for completeness.
