### ISSUE TITLE
Zoom out and Actual Size don't seem to work on some systems

### ISSUE THREAD

**Issue by manavmehta** [zulip/zulip-desktop#911]
**Operating System**: macOS Catalina 10.15.2

 **Clear steps to reproduce the issue**:
Zoom in a few times and then try to zoom out. You **might** not be able to (works well on some systems). 
(Works on some organizations and not on others)

Discussion on CZO : https://chat.zulip.org/#narrow/stream/16-desktop/topic/zoom.20out.20issue

Upstream issue : https://github.com/electron/electron/issues/20667

**Comment by catalin-hritcu** [comment]
I'm having zoom out problems very often with Zulip. Is there any workaround when it stops working?

I'm on Manjaro Linux (xfce).

**Comment by manavmehta** [comment]
@catalin-hritcu We will be looking into this shortly. Till then you can use [this](https://chat.zulip.org/#narrow/stream/16-desktop/topic/zoom.20out.20issue/near/844538) hacky way to get back.
Let us know if you face an issue in this :)

**Comment by catalin-hritcu** [comment]
Zapping `per_host_zoom_level` here `~/.config/Zulip/Partitions/webviewsession/Preferences` worked indeed as a workaround. Thanks a lot.

**Comment by akashnimare** [comment]
> (Works on some organizations and not on others)

@manavmehta can you tell me on which orgs it doesn't work? All good on CZO.

**Comment by catalin-hritcu** [comment]
Here is the org for which I'm having problems: https://fstar.zulipchat.com

**Comment by manavmehta** [comment]
@akashnimare Actually, it's not about some particular org. It doesn't work for me on CZO. But works perfectly for kamandprompt.zulipchat.com.
Perhaps it works on last org.

**Comment by akashnimare** [comment]
For me, if you add two orgs, it only works on the first one.

**Comment by manavmehta** [comment]
@akashnimare probably we should look into it, right after context menu? Seems really important.
The main issue being it shoes different behaviors on different systems, smh
