### ISSUE TITLE
Clicking on Zulip icon in macOS dock makes the window disappear

### ISSUE THREAD

**Issue by varkor** [zulip/zulip-desktop#914]
I just upgraded to Zulip v5.0.0 on macOS Sierra and now the window toggles between visible and invisible every time I click on its icon in the dock. Presumably this is a bug instead of a "feature", but it is very frustrating. (This was very confusing at first, when I tried switching to it by clicking on the icon, it wouldn't be there.)

**Comment by fritzhardy** [comment]
Also on MacOS Catalina 10.15.3.

**Comment by akashnimare** [comment]
I see. This was added in [here](https://github.com/zulip/zulip-desktop/commit/9490265a03f22ada300ff13aadbef368058eddda). If it's not useful we'll remove this feature. More info on this [here](https://chat.zulip.org/#narrow/stream/16-desktop/topic/macos.20app.20not.20displaying.20any.20windows).

**Comment by varkor** [comment]
@akashnimare: this is a really confusing behaviour — I couldn't understand why Zulip was frequently disappearing. If you switch apps by clicking on the icon, half the time Zulip won't be there when you try to switch to it. It took me a while to figure out what was happening. I'm positive this is causing consternation for others too. I think this needs to be reverted and backported to a minor version soon: it's a significant reduction in UX.

**Comment by cognusion** [comment]
I've heard from 3 mac users at our site that this is confusing.

**Comment by timabbott** [comment]
I'm not familiar with the details of how this works, but we've gotten a lot of complaints about this (here and elsewhere), which makes me think we should either revert or rework this to work how users expect.

**Comment by varkor** [comment]
If you absolutely wanted to keep this behaviour in some form, it could be acceptable to toggle the visibility of Zulip if Zulip is currently the topmost window, in the current space *and* focused. This would make it much more obvious what was going on. However, I personally don't see why this behaviour is desirable in the first place (you can already hide applications with Command-H and clicking-to-hide is not a common macOS convention).

**Comment by virtuaris** [comment]
This behaviour is at least annoying. In daily work it simply means i always have to click the dock icon twice to get the Zulip window and that for 10k times (exaggerated of course). This is the only application which behaves that way. Just my 5ct.

**Comment by akashnimare** [comment]
@varkor this is what I'm planning -

* Remove the toggle behaviour which triggers after clicking on the dock icon
* Do not hide window on clicking dock (just show it if it's hidden)

Is that correct?

**Comment by akashnimare** [comment]
`Pushed` some changes -
 
<img src="https://cl.ly/8bd033e45ae3/download/Screen%20Recording%202020-04-03%20at%2012.46%20PM.gif">

**Comment by varkor** [comment]
@akashnimare: this looks good to me :)

**Comment by kanunnikau** [comment]
> If you absolutely wanted to keep this behaviour in some form, it could be acceptable to toggle the visibility of Zulip if Zulip is currently the topmost window, in the current space _and_ focused. This would make it much more obvious what was going on. However, I personally don't see why this behaviour is desirable in the first place (you can already hide applications with Command-H and clicking-to-hide is not a common macOS convention).

I have just discovered (due to this Zulip bug) that there is Alt+Click in macOS. It does exactly the thing that was intended here - to toggle visibility of current app. Try to play with Alt+Clicking on Zulip - it will jump between showing Zulip and your previously opened app. If you had a lot of apps opened and not minimised there will be a lot of clicking, apps flashing, and then you will arrive at the desktop. Trippy :)

**Comment by akashnimare** [comment]
We have fixed this in master. Will push a new release soon which will contain the fix. Thanks, everyone!

**Comment by toph-allen** [comment]
Just came here to post this — thanks for fixing this!

**Comment by stuartbryson** [comment]
Just came here to post this as well.

If it's helpful, I was going to make reference to the Apple Human Interface guidelines as well:

As far as I can tell, the dock icon is currently configured to toggle visibility of the Zulip application. If Zulip is visible, clicking on the dock icon will hide Zulip. If Zulip is hidden, clicking on the dock icon will show it. More jarringly, if Zulip is visible by behind other windows, clicking on the app icon will first bring Zulip to the front, and then hide Zulip completely. This results in a "flash" before it gets hidden.

Apple has clear [guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/dock/) on what clicking the dock icon should do: "Activate a window when the user clicks your app’s icon in the Dock. If your app is already running with open windows, activate the front open window or the last minimized window. If your app isn’t already running or is running without any open windows, open your main window or a new document window."

**Comment by rhusar** [comment]
Thanks for the fix/behavior revert. Given this type of issue is hit many times a day (I am actually considering using zulip in a browser tab in the meantime) is there any ETA on 5.0.1 release or a pre-release at least?

**Comment by akashnimare** [comment]
@rhusar we are in the middle of pushing a new release `v5.1.0`. It should be up in a day :)

**Comment by rhusar** [comment]
@akashnimare Perfection! Thanks a lot.

**Comment by toph-allen** [comment]
Thanks — I’m so glad to have this working as expected again :)

**Comment by akashnimare** [comment]
Update - we just pushed [v5.1.0](https://zulipchat.com/apps/) which has the fix for this issue, the app should be able to auto-update itself :)

**Comment by rhusar** [comment]
@akashnimare Just updated, dock behavior works as expected (again!).
