### ISSUE TITLE
Trouble installing Zulip on Linux Debian Variant

### ISSUE THREAD

**Issue by mihalybaci** [zulip/zulip-desktop#931]
I had some trouble installing the Zulip v5.0.0 on MX Linux, which is an OS based on Debian 10.3. When I attempting to install via the AppImage or the .deb package, the launcher failed silently, and I would get this error from the CLI:

`$ zulip 
[8323:0413/074040.034666:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Zulip/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
`

The file was owned by root, and I was able to solve the issue just by running

`$ sudo chmod 4755 /opt/Zulip/chrome-sandbox`

Zulip is working now, but I thought I would post the issue in case anyone else encounters it.

**Comment by akashnimare** [comment]
Looks similar to https://github.com/zulip/zulip-desktop/issues/912. We have fixed this issue, will push a new release soon.

**Comment by MartinX3** [comment]
@akashnimare I freshly installed 5.7 and got the same issue.
I used chmod to change the file from
`-rwxr-xr-x`
to
`-rwsr-xr-x`
to fix the issue on Arch Linux

**Comment by timabbott** [comment]
@MartinX3 can you open a new issue for that?  Arch Linux is a different platform so I don't think it makes sense to have a potentially similar issue with it tracked here.

**Comment by MartinX3** [comment]
@timabbott thank you for the response :)

I will if I can reproduce it (but now it's workarounded by manually chmod it)
