### ISSUE TITLE
Issue with download and open while viewing image

### ISSUE THREAD

**Issue by swetaj6** [zulip/zulip-desktop#934]
**Operating System** 
Windows 
Linux 
MacOS

**Steps to reproduce:**
Click on image to view it.
Click on Open or download.

Relevant error messages and/or screenshots:
The image loads full screen inside Zulip, but it doesn't download when we click to download. Similarly, the image doesn't load full screen but downloads when we click open.

**Comment by manavmehta** [comment]
@swetaj6 please check #917 and let us know how similar and dissimilar behavior you're seeing :)

**Comment by swetaj6** [comment]
@manavmehta it is kind of similar but with the extension that open and download is working exactly opposite.

**Comment by akashnimare** [comment]
@swetaj6 can you post a gif or something of the issue please?

**Comment by swetaj6** [comment]
@akashnimare 
![Zulip-download-and-open-issue](https://user-images.githubusercontent.com/52969740/79763224-6c0cf200-82e9-11ea-96a2-c86375ecc675.gif)

**Comment by akashnimare** [comment]
@swetaj6 we have narrow down the root cause of this issue will push a fix soon. @andersk this is another case where open and download button behaving exactly opposite.

**Comment by akashnimare** [comment]
Merging into #917. Please track the updates there.
