### ISSUE TITLE
Two clicks required to bring application window in front on MacOS

### ISSUE THREAD

**Issue by andreas-bulling** [zulip/zulip-desktop#937]
Hi,

on MacOS (10.14.4 in my case) with desktop app 5.0.0 I have to click the zulip icon in the tray **twice** to bring the application window in front. Only one click should be required.

**Comment by manavmehta** [comment]
Hey @andreas-bulling 
This issue is actually addressed in #914 & #930 
Fixed in #919 we will be pushing a release real soon.

Would be great if you could confirm your's is the same as the above two
Also if you want, you can build zulip-desktop from source as the latest master has it fixed :)

**Comment by andreas-bulling** [comment]
I'll wait for the new release then and report back if (not) this issue has been fixed. Thanks for your quick reply!

**Comment by abhigyank** [comment]
Closing since fixed.

**Comment by akashnimare** [comment]
@andreas-bulling just released v5.1.0 which contains the fix for the same - 

https://zulipchat.com/apps/

**Comment by andreas-bulling** [comment]
Saw it, thanks!
