### ISSUE TITLE
Images look rotated, because EXIF orientation is ignored

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-desktop#946]
See zulip/zulip#8177 for copious details and background, and in particular https://github.com/zulip/zulip/issues/8177#issuecomment-621214727 for a recent repro. This is a longstanding cause of annoyance for people posting photos on Zulip, depending on what device they use to take the photo.

As described at https://github.com/zulip/zulip/issues/8177#issuecomment-621468621 , this Web-wide issue is finally being fixed in browsers! In particular it's fixed in Chrome 81.

So from Zulip's perspective, the thing remaining to do to fix this problem completely is to ship a release of the desktop app where the embedded browser is Chromium 81 or later.

I don't really know how those updates are managed -- I suppose it's tied to an Electron version? -- so I'm not sure how far off that'd normally be. In any case, posting this here so there's a record of this additional benefit we'll get from this particular update.

**Comment by abhigyank** [comment]
We are currently on the latest Electron (v8.2.3), which ships Chromium 80. Chromium has been bumped to 83 for Electron v9 releases. So we should get it when the stable Electron 9 is released.

**Comment by timabbott** [comment]
That's scheduled for May 19, so not too far in the future. 
 https://www.electronjs.org/docs/tutorial/electron-timelines

**Comment by abhigyank** [comment]
We are on Electron 9 now. Maybe we could close this?

**Comment by timabbott** [comment]
Yep, done!  Thanks for the follow-up @abhigyank!
