### ISSUE TITLE
Single click on a file to download opens download dialog twice

### ISSUE THREAD

**Issue by j0hannesr0th** [zulip/zulip-desktop#947]
If I want to download a file the download dialog opens twice. The first dialog points to my Windows Downloads folder - the second dialog points to my Desktop. Both dialogs are open immidiately and placed directly behind each other (see screenshot).

Ahhh I see there is already a PR. #913 maybe this PR should get a higher priority since it's really annoying if you download a lot of files. Since the covid-19 times we send much more files Zulip...

---

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Opload a file (e.g. *.docx) try to download it - download dialog will open twice
- **Relevant error messages and/or screenshots**:
![grafik](https://user-images.githubusercontent.com/36242595/80676404-f4904d00-8ab6-11ea-9633-8a7a900b7575.png)
![grafik](https://user-images.githubusercontent.com/36242595/80676564-551f8a00-8ab7-11ea-8c17-f642d03c297f.png)

**Comment by manavmehta** [comment]
cc @akashnimare @abhigyank May we finalize the PR?

**Comment by abhigyank** [comment]
Yeah, #913 solves it. @akashnimare can you look into merging it?

**Comment by akashnimare** [comment]
Looks good. Left a comment there.
