### ISSUE TITLE
Help center link incorrect in 5.1.0

### ISSUE THREAD

**Issue by rnicholas** [zulip/zulip-desktop#948]
The URL associated with the Zulip "Help Center" seems to have lost some information between 5.0.0 and 5.1.0 on macOS.
---
- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [X] macOS
- **Clear steps to reproduce the issue**: Click the "Help Center" link in the "Help" menu. 
- **Relevant error messages and/or screenshots**: Incorrectly sends browser to non-existent "/help" instead of "https://zulipchat.com/help/" as in previous versions.

**Comment by akashnimare** [comment]
@rnicholas this works well for me. On https://python.zulipchat.com it opens up - https://python.zulipchat.com/help.

**Comment by rnicholas** [comment]
Good catch. It appears that you must have one of the organizations activated in the sidebar for this to work correctly. If you click "Help Center" while the "About Zulip" (version info) page is in view, the link fails.

Why do we have a separate help URL for each organization? Is this for privately hosted instances? Perhaps when the "about" screen is displayed, this could either default to https://zulipchat.com/help/ or the "Help Center" link could be disabled.

**Comment by timabbott** [comment]
Yeah, privately hosted instances may have different versions of Zulip with different documentation.  But that's already reachable via the "Help" section option in the in-webapp menu; and I think the help for the desktop app in general should go to the global, most up-to-date content.

So I think we should just hardcode `https://zulipchat.com/help/`.
