### ISSUE TITLE
Zulip desktop - laggy and sluggish scrolling

### ISSUE THREAD

**Issue by aminya** [zulip/zulip-desktop#955]
- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:

Zulip is very sluggish and laggy in scrolling. This doesn't exist in the web version (Firefox).

**Comment by timabbott** [comment]
Can you try the webapp in Chrome and see if that's the same scrolling performance for you?

**Comment by aminya** [comment]
It works without any issues in web browsers. I tested using Edge Chromium and Firefox.

**Comment by timabbott** [comment]
Interesting.  We should test with the version of Chromium that powers Electron 8; it's possible this is just an upstream Chromium performance issue that will be fixed when we move to Electron 9 in a few weeks.

**Comment by andersk** [comment]
The app used Electron 8.2.5 (Chromium 80.0.3987.165) when this was reported, and we’re now up to Electron 11.0.3 (Chromium 87.0.4280.67). Is this still an issue?

**Comment by timabbott** [comment]
I think we close this as likely resolved by the Chromium upgrade given that Chromium worked for the user and we're now running Chromium newer than the report.
