### ISSUE TITLE
Application doesn't start at Windows startup

### ISSUE THREAD

**Issue by volo-zyko** [zulip/zulip-desktop#969]
---

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Enable "Start app at login" in Settings and reboot Windows.

**Comment by akashnimare** [comment]
@volo-zyko we did fix this issue in #851, will have to check if it's a regression. Make sure you are on the latest release - https://zulipchat.com/apps.

**Comment by volo-zyko** [comment]
Could it be that "Start app at login" setting isn't correctly handled during application's installation? It's just my guess.

It was enabled after installation and I didn't change it but the application didn't start at logon. However, once I turned it off and turned on I can see there is a Zulip-related key in `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` section. Unfortunately, I'm not 100% sure that it wasn't there before.

I will have to re-install the application and check it once again.

**Comment by abhigyank** [comment]
@akashnimare https://chat.zulip.org/#narrow/stream/16-desktop/topic/BUG.3A.20Start.20app.20at.20Login.20don't.20work

We should have that setting off by default, I guess.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-desktop/pull/972.
