### ISSUE TITLE
Option to Add Root CA

### ISSUE THREAD

**Issue by guillona** [zulip/zulip-desktop#970]
Hello,

I'd like to request an option to easily import a root certificate into the desktop application.  I have installed Zulip into an intranet environment where we have our own root certificates, but it is not clear how to add a new root CA into the desktop application.

Thanks!

**Comment by abhigyank** [comment]
Hey @guillona , can you try https://zulipchat.com/help/custom-certificates#desktop ?

**Comment by guillona** [comment]
Hi @abhigyank, I have indeed tried this and it did not work.  I tried with the root certificate, and the certificate of the zulip server itself. 

The documentation discusses a self-signed certificate, and my use case is different: I have a signed certificate, but not from a globally known CA, so I need to provide a new trusted root.

Thanks!

**Comment by abhigyank** [comment]
Which OS are you on? @guillona

**Comment by guillona** [comment]
Hi, this is on Ubuntu 18.04.4 LTS.

**Comment by janLo** [comment]
We have the same problem in a intranet environment. The solution was to add the root-certificate to chromium or use the certutil (see https://chromium.googlesource.com/chromium/src.git/+/master/docs/linux/cert_management.md) to fill the shared nssdb of the user.
This behavior started with the version 5.2 of the client. Confirmed on Ubuntu and Debian.

**Comment by abhigyank** [comment]
We have permanently moved our app to make use of root-certificate as on Chromium like @janLo suggested. This will be in the latest v5.4.0 releases. Possibly remove support for the cert store inside the app from next release.
Docs - https://chat.zulip.org/help/custom-certificates#desktop

@guillona  if this fixes your issue, we can close this.
