### ISSUE TITLE
UX: The font size of spellchecker should be smaller

### ISSUE THREAD

**Issue by manavmehta** [zulip/zulip-desktop#978]
**Describe the issue**
The `#note` div should be having a smaller font size than the current one for better UX. See the screenshots.

**To Reproduce**
Go to Settings -> General and see below `Enable Spellchecker` option

**Screenshots**
macOS
![mac](https://user-images.githubusercontent.com/31139861/85027772-e8ac3780-b197-11ea-8e4e-ce1482812617.png)

Ubuntu & Windows
![ubuntu](https://user-images.githubusercontent.com/31139861/85027776-eb0e9180-b197-11ea-8cbf-0c68d96a6d36.png)

**Desktop (please complete the following information):**
 - Operating System: macOS, Ubuntu, Windows

**Comment by manavmehta** [comment]
@zulipbot add "good first issue"

**Comment by samyakgaur** [comment]
@manavmehta please could you help me with the file name where this div is mentioned i was unable to find it.

**Comment by manavmehta** [comment]
@samyakgaur The div was added in #967 
A good way in general would be to [grep](https://www.gnu.org/savannah-checkouts/gnu/grep/manual/grep.html) the div.

**Comment by samyakgaur** [comment]
> @samyakgaur The div was added in #967
> A good way in general would be to [grep](https://www.gnu.org/savannah-checkouts/gnu/grep/manual/grep.html) the div.

I had made a really stupid mistake. I didnt notice my fork was behind the master. That is the reason i was unable to find it.
