### ISSUE TITLE
WebSocket Certificate Error with self signed certificate

### ISSUE THREAD

**Issue by sebastianelsner** [zulip/zulip-desktop#983]
Hallo, I am running a Zulip Server 2.1.2 on Ubuntu 18.04 with self-signed certificates in a usually air-gapped environment. The certs were created by Zulip while installing. Wanting to update the server and desktop app (running on CentOS 7 and Windows 10), I now need to provide the app with the cert. This works up to a point where I can log in, but periodically a "Certificate Error" for the WebSocket will pop up. See screenshot.
I can use Zulip from a Webbrowser just fine after accepting the security exception.

![wsssslerror](https://user-images.githubusercontent.com/902798/85224432-a159bd00-b3ca-11ea-8dd8-3ad07a43a485.png)

**Comment by abhigyank** [comment]
@timabbott Any idea from where websocket cert error could come from?

> I can use Zulip from a Webbrowser just fine after accepting the security exception.

We don't typically allow servers with cert security issue, i.e. you'd need to add the certificate to the app. And as you have done that I suppose you can access the server in general (apart from this occasional error) ?

**Comment by timabbott** [comment]
@sebastianelsner have you read
https://zulip.readthedocs.io/en/latest/production/ssl-certificates.html#self-signed-certificate

and made sure your SSL setup gets a good report from ssllabs.com?  The desktop app is stricter about problems with certificates than most browsers will ignore.

**Comment by sebastianelsner** [comment]
@timabbott I checked the docs and this is how we setup the server. We are in an off-line (non-internet) environment, so instead of ssllabs I tested with an offline tool called sslyze (https://github.com/nabla-c0d3/sslyze) and the output seems good. Although I am not 100% sure at which port to point the scanner. Is it  443 for the websockets as well?

**Comment by timabbott** [comment]
My recommendation is actually that you upgrade to the latest Zulip master; we've removed all use of websockets in production (and are close to releasing our next major release) and I expect that'll solve your problem.  

(We'll be releasing an -rc1 in the next couple days).

**Comment by sebastianelsner** [comment]
Thank you for the advice, I will wait for the new release, test this on a clone and report back.

**Comment by abhigyank** [comment]
Fixed in https://github.com/zulip/zulip-desktop/commit/6c37e30233b1066c244d9b1e36dca5e350b75407 .
