### ISSUE TITLE
Copy email address no longer in context menu

### ISSUE THREAD

**Issue by alexanderglueck** [zulip/zulip-desktop#986]
**Describe the bug**
It used to be possible to right-click an email address without selecting text and use the context menu item "Copy Email Address" to copy the email. After upgrading to v5.3.0 the context menu no longer displays this option. 

**To Reproduce**
Right click on an email address on pre 5.3.0 system and on 5.3.0. 

**Expected behavior**

**Screenshots**
Context menu after upgrading to 5.3.0: 
![broken](https://user-images.githubusercontent.com/6459474/85716530-d4fb5680-b6ec-11ea-92b4-7cc8af73eb7c.png)

Context menu from before: 
![working](https://user-images.githubusercontent.com/6459474/85716576-e2b0dc00-b6ec-11ea-8318-1d6344da18a7.png)

**Desktop (please complete the following information):**
 - Operating System: 
 Windows 10 (1909)
 - Zulip Desktop Version:
v5.3.0

**Additional context**

**Comment by abhigyank** [comment]
We did an update of our context menu in this release, so this is quite possible. @manavmehta  Can you look into this?

**Comment by manavmehta** [comment]
Sure the option can be added. We'll try to push it in the next release :)

**Comment by abhigyank** [comment]
@alexanderglueck Please check the new release, it should have this feature back! :)

**Comment by alexanderglueck** [comment]
Just tested the new release and it works again. Thanks!
