### ISSUE TITLE
ignoreCerts setting not working

### ISSUE THREAD

**Issue by juergenhemelt** [zulip/zulip-desktop#988]
Setting in config/domain.json does not work anymore in v5.3.0 I get a net::ERR_CERT_AUTHORITY_INVALID for the websocket-URL wss://...

**Comment by abhigyank** [comment]
#983 related.

**Comment by abhigyank** [comment]
We have actually removed ignore certs option in the latest release. https://github.com/zulip/zulip-desktop/commit/d661895545783dcf62e1ec184521c7784654cf8c

**Comment by SashLi** [comment]
Same here, added certificate but get error because of wss URL. Is there any way to bring back the "old" ignore certs option. That was running more smoothly. One other thing if noticed: You cannot use the root certifcate of a CA, it always need the server certificate itself.

**Comment by abhigyank** [comment]
If you have already added the server - you can add root CAs as respected by Chromium  - https://sites.google.com/a/chromium.org/dev/Home/chromium-security/root-ca-policy - 
Microsoft Windows: [Microsoft Root Certificate Program](https://aka.ms/rootcert). 
Apple OS X: [Apple Root Certificate Program](http://www.apple.com/certificateauthority/ca_program.html)
Linux - Chrome Certificate Store. 

@andersk  The handler on `certificate-error` for now works only with `https://` I suppose, and hence not working with `wss://` links? Is this right?
