### ISSUE TITLE
Bigger font size by default

### ISSUE THREAD

**Issue by digitalethics** [zulip/zulip-desktop#995]
I know that we can zoom in and out but this isn't very welcoming for newcomers and significantly limits wider Zulip adoption among non-technical communities. The easiest fix would be to introduce a **bigger font size by default**. A more sophisticated solution would be to **automatically adjust font size** based on the user's desktop resolution. I'm not sure if the latter is possible technically or actually desired (privacy reason to "read" a user's desktop resolution) and should be discussed.

From a user interface perspective adding a **button to select font sizes** by numbers or to decrease or increase it via a +/- selector would be desirable.

**Comment by abhigyank** [comment]
@timabbott Should this go to the Web-App?

**Comment by timabbott** [comment]
Yes but making the font size larger is already an open priority issue, tracked e.g. at https://github.com/zulip/zulip/pull/9769

(It's old but one of the top planned priorities after the 3.0 release next week).
