### ISSUE TITLE
Message composition menu pops up when clicking on reactions

### ISSUE THREAD

**Issue by LeSeulArtichaut** [zulip/zulip-desktop#997]
**Describe the bug**
When clicking on a reaction, either to add or remove it, the message composition menu pops up just like if you clicked on the message itself.

**To Reproduce**
Add a reaction on any message, then remove it by clicking on the reaction's icon.

**Expected behavior**
The message composition menu should not pop up. This is the behaviour of previous Zulip versions.

**Desktop (please complete the following information):**
 - Operating System: macOS 10.15
 - Zulip Desktop Version: 5.2.0

**Comment by manavmehta** [comment]
@LeSeulArtichaut can you provide some gif or video?
cc @akashnimare @abhigyank 

Edit: Reproducible - never thought of this behavior, thanks for pointing out.

**Comment by LeSeulArtichaut** [comment]
Here's a GIF on the desktop client (Electron) :
![zulip-desktop997](https://user-images.githubusercontent.com/38361244/87358684-9d066700-c566-11ea-9407-e360304b5d24.gif)

However I can also reproduce this bug in the browser, both in Brave and Firefox.

**Comment by abhigyank** [comment]
Fixed in https://github.com/zulip/zulip/pull/15783 .
